//! Emit Rust source (model / read / write) from the resolved [`ModelIr`].
//! Mirrors the spike's hand-written `generated.rs` + `readwrite.rs` shapes.

use std::fmt::Write as _;

use crate::classify::Kind;
use crate::model_ir::{Field, ModelIr, RefEnum, SimpleEnt};

const HEADER: &str = "// @generated by codegen. DO NOT EDIT.\n// Schema-faithful model + generic 2-pass read + topo write.\n\n";

/// Field Rust type for a `Kind` (+ optional / derivable wrapper). A derivable
/// slot (conditionally `*`) is modeled as `Option<T>` (`None` => `*`).
fn field_type(ir: &ModelIr, f: &Field) -> String {
    let base = kind_type(ir, &f.kind);
    if f.optional || f.derivable {
        format!("Option<{base}>")
    } else {
        base
    }
}

fn kind_type(ir: &ModelIr, k: &Kind) -> String {
    match k {
        Kind::Ref(t) => ir.ref_enums[t].rust.clone(),
        Kind::Vec(inner) => format!("Vec<{}>", kind_type(ir, inner)),
        Kind::Real => "f64".into(),
        Kind::Int => "i64".into(),
        Kind::Bool => "bool".into(),
        Kind::Logical => "Logical".into(),
        Kind::Str => "String".into(),
        Kind::Binary => "String".into(),
        Kind::Enum(a) => ir.enums[a].rust.clone(),
        Kind::MeasureSelect(_) => "MeasureValue".into(),
        Kind::StringSelect(_) => "StringSelectValue".into(),
    }
}

/// Sanitize a field name into a valid Rust ident (handles `ref`, dup names).
fn field_ident(name: &str, used: &mut std::collections::BTreeMap<String, u32>) -> String {
    let raw = match name {
        "ref" | "type" | "self" | "loop" | "box" | "move" => format!("r#{name}"),
        _ => name.to_string(),
    };
    let n = used.entry(name.to_string()).or_insert(0);
    let out = if *n == 0 { raw } else { format!("{raw}_{n}") };
    *n += 1;
    out
}

/// Build the (ident, field) list for a struct/part, deduping names.
fn idents(fields: &[Field]) -> Vec<(String, &Field)> {
    let mut used = std::collections::BTreeMap::new();
    fields
        .iter()
        .map(|f| (field_ident(&f.name, &mut used), f))
        .collect()
}

// ===========================================================================
// model.rs
// ===========================================================================

pub fn emit_model(ir: &ModelIr) -> String {
    let mut s = String::from(HEADER);

    // Arena + helpers.
    s.push_str(
        r#"#[derive(Debug)]
pub struct Arena<T> { pub items: Vec<T> }
impl<T> Default for Arena<T> { fn default() -> Self { Arena { items: Vec::new() } } }
impl<T> Arena<T> {
    pub fn push(&mut self, v: T) -> usize { let i = self.items.len(); self.items.push(v); i }
    pub fn get(&self, i: usize) -> &T { &self.items[i] }
}

/// EXPRESS LOGICAL (.T./.F./.U.).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Logical { True, False, Unknown }
impl Logical {
    pub fn parse(s: &str) -> Option<Self> {
        Some(match s { "T" => Self::True, "F" => Self::False, "U" | "UNKNOWN" => Self::Unknown, _ => return None })
    }
    pub fn token(self) -> &'static str {
        match self { Self::True => ".T.", Self::False => ".F.", Self::Unknown => ".U." }
    }
}

/// select-of-scalars: `Some(type_name)` = typed member `TYPE(v)`; `None` = bare.
#[derive(Debug, Clone, PartialEq)]
pub struct MeasureValue { pub type_name: Option<String>, pub value: f64 }

/// select-of-named-strings (e.g. SELECT(identifier, message)): `Some(type_name)`
/// = typed member `TYPE('s')`; `None` = bare string.
#[derive(Debug, Clone, PartialEq)]
pub struct StringSelectValue { pub type_name: Option<String>, pub value: String }

"#,
    );

    // ENUMs.
    let mut enums: Vec<_> = ir.enums.values().collect();
    enums.sort_by(|a, b| a.rust.cmp(&b.rust));
    for e in enums {
        writeln!(s, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]").unwrap();
        writeln!(s, "pub enum {} {{", e.rust).unwrap();
        for (_, v) in &e.members {
            writeln!(s, "    {v},").unwrap();
        }
        writeln!(s, "}}").unwrap();
        writeln!(s, "impl {} {{", e.rust).unwrap();
        writeln!(
            s,
            "    pub fn parse(s: &str) -> Option<Self> {{ Some(match s {{"
        )
        .unwrap();
        for (tok, v) in &e.members {
            writeln!(s, "        \"{tok}\" => Self::{v},").unwrap();
        }
        writeln!(s, "        _ => return None }}) }}").unwrap();
        writeln!(s, "    pub fn token(self) -> &'static str {{ match self {{").unwrap();
        for (tok, v) in &e.members {
            writeln!(s, "        Self::{v} => \".{tok}.\",").unwrap();
        }
        writeln!(s, "    }} }}\n}}\n").unwrap();
    }

    // Id newtypes.
    for se in &ir.simples {
        writeln!(
            s,
            "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct {}Id(pub usize);",
            se.rust
        )
        .unwrap();
    }
    if ir.has_part_bag {
        writeln!(
            s,
            "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct ComplexUnitId(pub usize);"
        )
        .unwrap();
    }
    s.push('\n');

    // AnyId: one variant per arena (read idmap value).
    writeln!(s, "#[derive(Debug, Clone, Copy)]\npub enum AnyId {{").unwrap();
    for se in &ir.simples {
        writeln!(s, "    {}({}Id),", se.rust, se.rust).unwrap();
    }
    if ir.has_part_bag {
        writeln!(s, "    ComplexUnit(ComplexUnitId),").unwrap();
    }
    writeln!(s, "}}\n").unwrap();

    // Ref enums.
    let mut refs: Vec<_> = ir.ref_enums.values().collect();
    refs.sort_by(|a, b| a.rust.cmp(&b.rust));
    for re in refs {
        emit_ref_enum(&mut s, re);
    }

    // Simple structs.
    for se in &ir.simples {
        writeln!(
            s,
            "#[derive(Debug, Clone, PartialEq)]\npub struct {} {{",
            se.rust
        )
        .unwrap();
        for (id, f) in idents(&se.fields) {
            if f.derived {
                continue;
            }
            writeln!(s, "    pub {id}: {},", field_type(ir, f)).unwrap();
        }
        writeln!(s, "}}\n").unwrap();
    }

    // Part-bag.
    if ir.has_part_bag {
        writeln!(
            s,
            "#[derive(Debug, Clone, PartialEq)]\npub enum UnitPart {{"
        )
        .unwrap();
        for p in &ir.parts {
            let kept: Vec<_> = idents(&p.fields)
                .into_iter()
                .filter(|(_, f)| !f.derived)
                .collect();
            if kept.is_empty() {
                writeln!(s, "    {},", p.rust).unwrap();
            } else {
                write!(s, "    {} {{ ", p.rust).unwrap();
                for (id, f) in &kept {
                    write!(s, "{id}: {}, ", field_type(ir, f)).unwrap();
                }
                writeln!(s, "}},").unwrap();
            }
        }
        writeln!(s, "}}\n").unwrap();
        writeln!(
            s,
            "#[derive(Debug, Clone, PartialEq)]\npub struct ComplexUnit {{ pub parts: Vec<UnitPart> }}\n"
        )
        .unwrap();
    }

    // Top-level Model.
    writeln!(s, "#[derive(Debug, Default)]\npub struct Model {{").unwrap();
    for se in &ir.simples {
        writeln!(s, "    pub {}: Arena<{}>,", arena_field(&se.rust), se.rust).unwrap();
    }
    if ir.has_part_bag {
        writeln!(s, "    pub complex_units: Arena<ComplexUnit>,").unwrap();
    }
    writeln!(s, "}}").unwrap();

    s
}

fn emit_ref_enum(s: &mut String, re: &RefEnum) {
    // No `Copy`: an aggregate arm holds a `Vec` (not Copy), and dropping Copy
    // uniformly keeps the generated emit/read code simple (clone at the few
    // deref sites; compiler flags any missed). Clone/Eq still derived.
    writeln!(
        s,
        "#[derive(Debug, Clone, PartialEq, Eq)]\npub enum {} {{",
        re.rust
    )
    .unwrap();
    for (variant, target) in &re.simple_arms {
        writeln!(s, "    {variant}({target}Id),").unwrap();
    }
    // Aggregate arms for SELECT(.., LIST OF E, SET OF E): hold Vec<{E}Ref>
    // (list/set collapse — wire-identical `(...)`).
    for (variant, elt_ref, _wire) in &re.aggregate {
        writeln!(s, "    {variant}(Vec<{elt_ref}>),").unwrap();
    }
    // Enum arms for SELECT(.., some_enum): hold the (Copy) generated enum; on the
    // wire a `.TOKEN.` literal, discriminated from a `#ref` at read time.
    for (variant, enum_rust, _wire) in &re.enum_arms {
        writeln!(s, "    {variant}({enum_rust}),").unwrap();
    }
    if re.has_complex {
        writeln!(s, "    Complex(ComplexUnitId),").unwrap();
    }
    // An enum with no arms at all (all ref targets out of closure, e.g. excluded)
    // would be uninhabited and make its referrer unconstructible. Such referrers
    // always escape the round-trip subset, so this variant is a never-resolved,
    // never-emitted placeholder that just keeps the generated code constructible.
    if re.simple_arms.is_empty()
        && re.aggregate.is_empty()
        && re.enum_arms.is_empty()
        && !re.has_complex
    {
        writeln!(s, "    Unresolved,").unwrap();
    }
    writeln!(s, "}}").unwrap();
    // resolve from AnyId
    writeln!(s, "impl {} {{", re.rust).unwrap();
    writeln!(s, "    pub fn from_any(a: AnyId) -> Self {{ match a {{").unwrap();
    for (variant, target) in &re.simple_arms {
        writeln!(s, "        AnyId::{target}(i) => Self::{variant}(i),").unwrap();
    }
    if re.has_complex {
        writeln!(s, "        AnyId::ComplexUnit(i) => Self::Complex(i),").unwrap();
    }
    writeln!(
        s,
        "        other => panic!(\"{} ref -> {{other:?}}\"),",
        re.rust
    )
    .unwrap();
    writeln!(s, "    }} }}\n}}\n").unwrap();
}

/// snake_case plural-ish arena field name for a struct rust name.
pub fn arena_field(rust: &str) -> String {
    let mut out = String::new();
    for (i, c) in rust.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out.push('s');
    out
}

// ===========================================================================
// read.rs — generic 2-pass.
// ===========================================================================

/// Does a kind carry an entity ref (resolved in pass 2)?
fn has_ref(k: &Kind) -> bool {
    match k {
        Kind::Ref(_) => true,
        Kind::Vec(inner) => has_ref(inner),
        _ => false,
    }
}

pub fn emit_read(ir: &ModelIr) -> String {
    let mut s = String::from(HEADER);
    s.push_str("use std::collections::BTreeMap;\nuse step_io::{Attribute, RawEntity, RawEntityPart};\nuse super::model::*;\n\n");

    // scalar readers
    s.push_str(
        r#"// Strict scalar readers: the pre-read `normalize` layer has already rewritten
// non-standard values to their standard form (or dropped the entity), so a
// reader seeing an off-kind value is a normalize-rule gap (panic, not silent).
fn as_real(a: &Attribute) -> f64 {
    match a { Attribute::Real(r) => *r, other => panic!("expected real, got {other:?}") }
}
fn as_int(a: &Attribute) -> i64 {
    match a { Attribute::Integer(i) => *i, other => panic!("expected int, got {other:?}") }
}
fn as_str(a: &Attribute) -> String {
    match a { Attribute::String(s) => s.clone(), other => panic!("expected string, got {other:?}") }
}
fn as_logical(a: &Attribute) -> Logical {
    match a { Attribute::Enum(s) => Logical::parse(s).expect("logical"), other => panic!("expected logical, got {other:?}") }
}
fn as_ref_id(a: &Attribute) -> u64 {
    match a { Attribute::EntityRef(n) => *n, other => panic!("expected ref, got {other:?}") }
}
fn read_measure_value(a: &Attribute) -> MeasureValue {
    // A measure's numeric literal sits nested inside a Typed/bare attribute, so
    // it is not a top-level slot the normalize layer rewrites; accept the REAL
    // value written as either a real or an integer literal here.
    fn measure_real(a: &Attribute) -> f64 {
        match a { Attribute::Real(r) => *r, Attribute::Integer(i) => *i as f64, other => panic!("expected measure real, got {other:?}") }
    }
    match a {
        Attribute::Typed { type_name, value } => MeasureValue { type_name: Some(type_name.clone()), value: measure_real(value) },
        Attribute::Real(_) | Attribute::Integer(_) => MeasureValue { type_name: None, value: measure_real(a) },
        other => panic!("expected measure_value, got {other:?}"),
    }
}
fn read_string_select(a: &Attribute) -> StringSelectValue {
    // A named string select member is a Typed literal `TYPE('s')`; a bare string
    // is unwrapped. (Mirrors read_measure_value for the string case.)
    fn str_of(a: &Attribute) -> String {
        match a { Attribute::String(s) => s.clone(), other => panic!("expected select string, got {other:?}") }
    }
    match a {
        Attribute::Typed { type_name, value } => StringSelectValue { type_name: Some(type_name.clone()), value: str_of(value) },
        Attribute::String(s) => StringSelectValue { type_name: None, value: s.clone() },
        other => panic!("expected string_select, got {other:?}"),
    }
}

"#,
    );

    // ---- simple entity name table (closure subset filter) ----
    let simple_names: Vec<String> = ir
        .simples
        .iter()
        .map(|se| format!("\"{}\"", se.name))
        .collect();
    writeln!(
        s,
        "pub const SIMPLE_NAMES: &[&str] = &[{}];",
        simple_names.join(", ")
    )
    .unwrap();

    // ---- dispatch table for complex part-bag ----
    if ir.has_part_bag {
        let names: Vec<String> = ir.parts.iter().map(|p| format!("\"{}\"", p.name)).collect();
        writeln!(
            s,
            "pub const COMPLEX_PART_NAMES: &[&str] = &[{}];",
            names.join(", ")
        )
        .unwrap();
        s.push_str("pub fn is_complex_unit(parts: &[RawEntityPart]) -> bool { !parts.is_empty() && parts.iter().all(|p| COMPLEX_PART_NAMES.contains(&p.name.as_str())) }\n\n");
    } else {
        s.push_str("pub const COMPLEX_PART_NAMES: &[&str] = &[];\npub fn is_complex_unit(_parts: &[RawEntityPart]) -> bool { false }\n\n");
    }

    // subset membership predicate used by the round-trip filter.
    s.push_str("pub fn in_subset(ent: &RawEntity) -> bool {\n    match ent {\n        RawEntity::Simple { name, .. } => SIMPLE_NAMES.contains(&name.as_str()),\n        RawEntity::Complex { parts, .. } => is_complex_unit(parts),\n    }\n}\n\n");

    // ---- read() ----
    s.push_str("pub fn read(map: &BTreeMap<u64, RawEntity>) -> (Model, BTreeMap<u64, AnyId>) {\n");
    s.push_str("    let mut model = Model::default();\n");
    s.push_str("    let mut idmap: BTreeMap<u64, AnyId> = BTreeMap::new();\n");
    // pending lists for pass 2
    for se in &ir.simples {
        if se.fields.iter().any(|f| has_ref(&f.kind)) {
            writeln!(
                s,
                "    let mut pending_{}: Vec<({}Id, u64)> = Vec::new();",
                arena_field(&se.rust),
                se.rust
            )
            .unwrap();
        }
    }
    if ir.has_part_bag {
        s.push_str("    let mut pending_complex: Vec<(ComplexUnitId, u64)> = Vec::new();\n");
    }

    s.push_str("    for (&id, ent) in map {\n        match ent {\n");
    // simple dispatch arms (exact name match)
    for se in &ir.simples {
        let af = arena_field(&se.rust);
        let has_r = se.fields.iter().any(|f| has_ref(&f.kind));
        writeln!(
            s,
            "            RawEntity::Simple {{ name, attributes, .. }} if name == \"{}\" => {{",
            se.name
        )
        .unwrap();
        // pass1 bind
        emit_pass1_bind(&mut s, ir, se, has_r);
        writeln!(
            s,
            "                let aid = {}Id(model.{af}.push(v));",
            se.rust
        )
        .unwrap();
        writeln!(
            s,
            "                idmap.insert(id, AnyId::{}(aid));",
            se.rust
        )
        .unwrap();
        if has_r {
            writeln!(s, "                pending_{af}.push((aid, id));").unwrap();
        }
        s.push_str("            }\n");
    }
    // complex dispatch
    if ir.has_part_bag {
        s.push_str("            RawEntity::Complex { parts, .. } if is_complex_unit(parts) => {\n");
        s.push_str("                let bag = read_complex_parts_norefs(parts);\n");
        s.push_str("                let aid = ComplexUnitId(model.complex_units.push(ComplexUnit { parts: bag }));\n");
        s.push_str("                idmap.insert(id, AnyId::ComplexUnit(aid));\n");
        s.push_str("                pending_complex.push((aid, id));\n");
        s.push_str("            }\n");
    }
    s.push_str("            _ => {}\n        }\n    }\n");

    // ---- pass 2 ----
    for se in &ir.simples {
        if !se.fields.iter().any(|f| has_ref(&f.kind)) {
            continue;
        }
        let af = arena_field(&se.rust);
        writeln!(s, "    for (aid, raw) in pending_{af} {{").unwrap();
        writeln!(
            s,
            "        if let Some(RawEntity::Simple {{ attributes, .. }}) = map.get(&raw) {{"
        )
        .unwrap();
        writeln!(
            s,
            "            resolve_{af}(&mut model, aid, attributes, &idmap);"
        )
        .unwrap();
        s.push_str("        }\n    }\n");
    }
    if ir.has_part_bag {
        s.push_str("    for (aid, raw) in pending_complex {\n");
        s.push_str("        if let Some(RawEntity::Complex { parts, .. }) = map.get(&raw) {\n");
        s.push_str(
            "            resolve_complex(&mut model, aid, parts, &idmap);\n        }\n    }\n",
        );
    }
    s.push_str("    (model, idmap)\n}\n\n");

    // ---- resolve fns ----
    for se in &ir.simples {
        if se.fields.iter().any(|f| has_ref(&f.kind)) {
            emit_resolve(&mut s, ir, se);
        }
    }
    if ir.has_part_bag {
        emit_complex_read(&mut s, ir);
    }

    s
}

/// pass1: build the struct value, binding non-ref fields; ref fields get a
/// placeholder. `attributes` is the bound name.
fn emit_pass1_bind(s: &mut String, ir: &ModelIr, se: &SimpleEnt, _has_r: bool) {
    writeln!(s, "                let v = {} {{", se.rust).unwrap();
    let mut idx = 0usize;
    for (id, f) in idents(&se.fields) {
        if f.derived {
            idx += 1; // slot kept on wire, no field
            continue;
        }
        let expr = if has_ref(&f.kind) {
            ref_placeholder(ir, &f.kind, f.optional || f.derivable)
        } else if f.derivable {
            // scalar derivable slot: None placeholder (resolved at bind below).
            bind_derivable_scalar(ir, &f.kind, &format!("attributes[{idx}]"))
        } else {
            bind_scalar(ir, &f.kind, f.optional, &format!("attributes[{idx}]"))
        };
        writeln!(s, "                    {id}: {expr},").unwrap();
        idx += 1;
    }
    s.push_str("                };\n");
}

/// Bind a derivable (conditionally `*`) scalar: `*` => None, else Some(value).
fn bind_derivable_scalar(ir: &ModelIr, k: &Kind, attr: &str) -> String {
    let val = bind_scalar(ir, k, false, attr);
    format!("match &{attr} {{ Attribute::Derived => None, _ => Some({val}) }}")
}

/// Placeholder value for a ref field (patched in pass 2).
fn ref_placeholder(ir: &ModelIr, k: &Kind, optional: bool) -> String {
    let inner = match k {
        Kind::Ref(t) => {
            let re = &ir.ref_enums[t];
            // pick any arm for the placeholder
            if let Some((variant, target)) = re.simple_arms.first() {
                format!("{}::{}({}Id(usize::MAX))", re.rust, variant, target)
            } else if re.has_complex {
                format!("{}::Complex(ComplexUnitId(usize::MAX))", re.rust)
            } else if let Some((variant, _, _)) = re.aggregate.first() {
                // aggregate-only select (no single arm): empty-vec placeholder.
                format!("{}::{}(Vec::new())", re.rust, variant)
            } else if let Some((variant, enum_rust, _)) = re.enum_arms.first() {
                // enum-only select (no single arm): first enum member placeholder.
                let member = ir
                    .enums
                    .values()
                    .find(|e| &e.rust == enum_rust)
                    .and_then(|e| e.members.first())
                    .map(|(_, v)| v.clone())
                    .expect("enum arm has members");
                format!("{}::{}({}::{})", re.rust, variant, enum_rust, member)
            } else {
                // empty ref-enum (all targets excluded): referrer always escapes.
                format!("{}::Unresolved", re.rust)
            }
        }
        Kind::Vec(_) => "Vec::new()".to_string(),
        _ => unreachable!(),
    };
    if optional {
        // Option<Ref> or Option<Vec<Ref>>: None placeholder; pass 2 sets Some.
        "None".to_string()
    } else {
        inner
    }
}

/// Read a scalar/enum/measure field from a single attribute expression.
fn bind_scalar(ir: &ModelIr, k: &Kind, optional: bool, attr: &str) -> String {
    let body = match k {
        Kind::Real => format!("as_real(&{attr})"),
        Kind::Int => format!("as_int(&{attr})"),
        Kind::Str => format!("as_str(&{attr})"),
        Kind::Bool => format!("matches!(&{attr}, Attribute::Enum(s) if s == \"T\")"),
        Kind::Logical => format!("as_logical(&{attr})"),
        Kind::Binary => format!("as_str(&{attr})"),
        Kind::MeasureSelect(_) => format!("read_measure_value(&{attr})"),
        Kind::StringSelect(_) => format!("read_string_select(&{attr})"),
        Kind::Enum(a) => {
            let ty = &ir.enums[a].rust;
            format!(
                "match &{attr} {{ Attribute::Enum(s) => {ty}::parse(s).expect(\"{a}\"), other => panic!(\"enum {a}: {{other:?}}\") }}"
            )
        }
        Kind::Vec(inner) => return bind_scalar_vec(ir, inner, optional, attr),
        Kind::Ref(_) => unreachable!(),
    };
    if optional {
        format!("match &{attr} {{ Attribute::Unset => None, _ => Some({body}) }}")
    } else {
        body
    }
}

fn bind_scalar_vec(ir: &ModelIr, inner: &Kind, optional: bool, attr: &str) -> String {
    let elem = scalar_vec_elem(ir, inner);
    // Strict: a required list is always a List (normalize rewrote a non-standard
    // `$` to `()`); an optional list is None on `$`, Some(list) otherwise.
    if optional {
        format!(
            "match &{attr} {{ Attribute::Unset => None, Attribute::List(l) => Some(l.iter().map(|e| {elem}).collect()), other => panic!(\"opt vec: {{other:?}}\") }}"
        )
    } else {
        format!(
            "match &{attr} {{ Attribute::List(l) => l.iter().map(|e| {elem}).collect(), other => panic!(\"vec: {{other:?}}\") }}"
        )
    }
}

/// Read-element expr for a `Vec` inner kind, binding over `e` (an `&Attribute`).
/// Recurses for nested vecs (e.g. `weights_data: LIST OF LIST OF REAL`).
fn scalar_vec_elem(ir: &ModelIr, inner: &Kind) -> String {
    match inner {
        Kind::Real => "as_real(e)".to_string(),
        Kind::Int => "as_int(e)".to_string(),
        Kind::Str => "as_str(e)".to_string(),
        Kind::Logical => "as_logical(e)".to_string(),
        Kind::Enum(a) => format!(
            "match e {{ Attribute::Enum(s) => {}::parse(s).expect(\"{a}\"), o => panic!(\"{{o:?}}\") }}",
            ir.enums[a].rust
        ),
        Kind::Vec(inner2) => {
            let e2 = scalar_vec_elem(ir, inner2);
            format!(
                "match e {{ Attribute::List(l) => l.iter().map(|e| {e2}).collect::<Vec<_>>(), o => panic!(\"nested vec: {{o:?}}\") }}"
            )
        }
        _ => "as_real(e)".to_string(),
    }
}

/// pass2: resolve the ref fields of a simple entity.
fn emit_resolve(s: &mut String, ir: &ModelIr, se: &SimpleEnt) {
    let af = arena_field(&se.rust);
    writeln!(
        s,
        "fn resolve_{af}(model: &mut Model, aid: {}Id, attrs: &[Attribute], idmap: &BTreeMap<u64, AnyId>) {{",
        se.rust
    )
    .unwrap();
    let mut idx = 0usize;
    for (id, f) in idents(&se.fields) {
        if f.derived {
            idx += 1;
            continue;
        }
        if has_ref(&f.kind) {
            let expr = resolve_ref_expr(
                ir,
                &f.kind,
                f.optional,
                f.derivable,
                &format!("attrs[{idx}]"),
            );
            writeln!(s, "    let {id}_v = {expr};").unwrap();
        }
        idx += 1;
    }
    writeln!(s, "    let it = &mut model.{af}.items[aid.0];").unwrap();
    for (id, f) in idents(&se.fields) {
        if f.derived || !has_ref(&f.kind) {
            continue;
        }
        writeln!(s, "    it.{id} = {id}_v;").unwrap();
    }
    s.push_str("}\n\n");
}

/// Resolve one ref value from an `&Attribute` expression `aref` (already a
/// reference). Discriminates a named enum/aggregate select member (Typed literal
/// `WIRE(.TOKEN.)` / `WIRE((#a,#b))`) from a bare entity `#ref`. Shared by
/// single-ref fields and Vec elements so both handle Typed-wrapped members.
fn resolve_ref_one(re: &RefEnum, aref: &str) -> String {
    let single = format!(
        "{}::from_any(*idmap.get(&as_ref_id({aref})).expect(\"ref\"))",
        re.rust
    );
    let mut arms: Vec<String> = Vec::new();
    for (ev, enum_rust, wire) in &re.enum_arms {
        arms.push(format!(
            "Attribute::Typed {{ type_name, value }} if type_name == \"{wire}\" => {}::{}(match value.as_ref() {{ Attribute::Enum(s) => {}::parse(s).expect(\"{}\"), other => panic!(\"enum {wire}: {{other:?}}\") }}),",
            re.rust, ev, enum_rust, enum_rust
        ));
    }
    for (agg_variant, elt_ref, wire) in &re.aggregate {
        arms.push(format!(
            "Attribute::Typed {{ type_name, value }} if type_name == \"{wire}\" => {}::{}(match value.as_ref() {{ Attribute::List(l) => l.iter().map(|e| {}::from_any(*idmap.get(&as_ref_id(e)).expect(\"ref\"))).collect(), other => panic!(\"agg list {wire}: {{other:?}}\") }}),",
            re.rust, agg_variant, elt_ref
        ));
    }
    if arms.is_empty() {
        single
    } else {
        format!("match {aref} {{ {} _ => {single} }}", arms.join(" "))
    }
}

fn resolve_ref_expr(ir: &ModelIr, k: &Kind, optional: bool, derivable: bool, attr: &str) -> String {
    match k {
        Kind::Ref(t) => {
            let re = &ir.ref_enums[t];
            let one = resolve_ref_one(re, &format!("&{attr}"));
            if derivable {
                format!("match &{attr} {{ Attribute::Derived => None, _ => Some({one}) }}")
            } else if optional {
                format!("match &{attr} {{ Attribute::Unset => None, _ => Some({one}) }}")
            } else {
                one
            }
        }
        Kind::Vec(inner) => {
            let body = resolve_ref_vec(ir, inner, attr);
            // An OPTIONAL ref-list that is `$`/`*` is None (not Some(empty)) — else
            // `$` round-trips to `()`. (resolve_ref_vec maps a present list/normalized
            // `$`→[] for the required case.)
            if derivable {
                format!("match &{attr} {{ Attribute::Derived => None, _ => Some({body}) }}")
            } else if optional {
                format!("match &{attr} {{ Attribute::Unset => None, _ => Some({body}) }}")
            } else {
                body
            }
        }
        _ => unreachable!(),
    }
}

/// Resolve a (possibly nested) `Vec<...Ref>` from a list attribute expression.
fn resolve_ref_vec(ir: &ModelIr, inner: &Kind, attr: &str) -> String {
    let elem = match inner {
        // `e` is already `&Attribute` (from l.iter()); helper handles Typed-
        // wrapped enum/aggregate members alongside the bare entity ref.
        Kind::Ref(t) => resolve_ref_one(&ir.ref_enums[t], "e"),
        Kind::Vec(i2) => resolve_ref_vec(ir, i2, "e"),
        _ => unreachable!("non-ref nested vec in ref resolve"),
    };
    // No `Unset => Vec::new()`: an optional ref-list is unwrapped to None by the
    // caller (resolve_ref_expr) and a required one is normalized `$`→`()` before
    // read, so `$` reaching here is a normalize gap — surface it (panic) rather
    // than silently producing an empty list.
    format!(
        "match &{attr} {{ Attribute::List(l) => l.iter().map(|e| {elem}).collect(), other => panic!(\"vec ref: {{other:?}}\") }}"
    )
}

/// Complex part-bag read (norefs pass1 + resolve_complex pass2).
fn emit_complex_read(s: &mut String, ir: &ModelIr) {
    // pass1: bind non-ref part attrs
    s.push_str("fn read_complex_parts_norefs(parts: &[RawEntityPart]) -> Vec<UnitPart> {\n");
    s.push_str("    parts.iter().map(|p| match p.name.as_str() {\n");
    for p in &ir.parts {
        let kept: Vec<_> = idents(&p.fields).into_iter().collect();
        let nonderived: Vec<_> = kept.iter().filter(|(_, f)| !f.derived).collect();
        if nonderived.is_empty() {
            writeln!(s, "        \"{}\" => UnitPart::{},", p.name, p.rust).unwrap();
            continue;
        }
        write!(s, "        \"{}\" => UnitPart::{} {{ ", p.name, p.rust).unwrap();
        let mut idx = 0usize;
        for (id, f) in &kept {
            if f.derived {
                idx += 1;
                continue;
            }
            let expr = if has_ref(&f.kind) {
                ref_placeholder(ir, &f.kind, f.optional || f.derivable)
            } else if f.derivable {
                bind_derivable_scalar(ir, &f.kind, &format!("p.attributes[{idx}]"))
            } else {
                bind_scalar(ir, &f.kind, f.optional, &format!("p.attributes[{idx}]"))
            };
            write!(s, "{id}: {expr}, ").unwrap();
            idx += 1;
        }
        s.push_str("},\n");
    }
    s.push_str(
        "        other => panic!(\"unknown complex part: {other}\"),\n    }).collect()\n}\n\n",
    );

    // pass2: patch ref part attrs
    s.push_str("fn resolve_complex(model: &mut Model, aid: ComplexUnitId, parts: &[RawEntityPart], idmap: &BTreeMap<u64, AnyId>) {\n");
    s.push_str("    let bag = &mut model.complex_units.items[aid.0];\n");
    s.push_str("    for (slot, p) in bag.parts.iter_mut().zip(parts.iter()) {\n");
    s.push_str("        match slot {\n");
    for p in &ir.parts {
        let kept: Vec<_> = idents(&p.fields).into_iter().collect();
        let refkept: Vec<_> = kept
            .iter()
            .enumerate()
            .filter(|(_, (_, f))| !f.derived && has_ref(&f.kind))
            .collect();
        if refkept.is_empty() {
            continue;
        }
        // need positional indices into p.attributes (counting derived too)
        let binding: Vec<String> = kept
            .iter()
            .filter(|(_, f)| !f.derived && has_ref(&f.kind))
            .map(|(id, _)| id.clone())
            .collect();
        writeln!(
            s,
            "            UnitPart::{} {{ {}, .. }} => {{",
            p.rust,
            binding.join(", ")
        )
        .unwrap();
        let mut idx = 0usize;
        for (id, f) in &kept {
            if f.derived {
                idx += 1;
                continue;
            }
            if has_ref(&f.kind) {
                let expr = resolve_ref_expr(
                    ir,
                    &f.kind,
                    f.optional,
                    f.derivable,
                    &format!("p.attributes[{idx}]"),
                );
                writeln!(s, "                *{id} = {expr};").unwrap();
            }
            idx += 1;
        }
        s.push_str("            }\n");
    }
    // Catch-all for parts without ref attrs (and the no-arm case): always needed.
    s.push_str("            _ => {}\n");
    s.push_str("        }\n    }\n}\n");
}

// ===========================================================================
// write.rs — topo write.
// ===========================================================================

pub fn emit_write(ir: &ModelIr) -> String {
    let mut s = String::from(HEADER);
    s.push_str("use super::model::*;\n\n");

    // real formatter (STEP decimal-point form), copied from the spike.
    s.push_str(
        r#"fn real(v: f64) -> String {
    // Normalize signed zero to "0." (matches step-io writer/lexical.rs; -0.0 and
    // +0.0 are the same value/point). The round-trip gate canonicalizes signed
    // zero in merkle (`(r+0.0).to_bits()`), so this is NORM, not LOSS.
    if v == 0.0 { return "0.".to_string(); }
    if v == v.trunc() && v.is_finite() && v.abs() < 1e15 { return format!("{}.", v as i64); }
    let s = format!("{v:E}");
    if let Some(epos) = s.find('E') {
        let (mant, exp) = s.split_at(epos);
        let mant = if mant.contains('.') { mant.to_string() } else { format!("{mant}.") };
        format!("{mant}{exp}")
    } else { s }
}
fn measure(m: &MeasureValue) -> String {
    match &m.type_name { Some(t) => format!("{t}({})", real(m.value)), None => real(m.value) }
}
fn string_select(m: &StringSelectValue) -> String {
    match &m.type_name { Some(t) => format!("{t}({})", step_str(&m.value)), None => step_str(&m.value) }
}
/// Part 21 string literal: single-quoted, inner `'` doubled to `''` (matches
/// step-io `writer/lexical.rs::format_string`). Non-ASCII passes through raw.
fn step_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() { if ch == '\'' { out.push('\''); } out.push(ch); }
    out.push('\'');
    out
}

"#,
    );

    // Writer struct.
    s.push_str(
        "pub struct Writer<'a> {\n    model: &'a Model,\n    next: u64,\n    out: String,\n",
    );
    for se in &ir.simples {
        writeln!(s, "    {}: Vec<Option<u64>>,", ids_field(&se.rust)).unwrap();
    }
    if ir.has_part_bag {
        s.push_str("    complex_ids: Vec<Option<u64>>,\n");
    }
    s.push_str("}\n\n");

    // new()
    s.push_str("impl<'a> Writer<'a> {\n    pub fn new(model: &'a Model) -> Self {\n        Writer {\n            model, next: 1, out: String::new(),\n");
    for se in &ir.simples {
        writeln!(
            s,
            "            {}: vec![None; model.{}.items.len()],",
            ids_field(&se.rust),
            arena_field(&se.rust)
        )
        .unwrap();
    }
    if ir.has_part_bag {
        s.push_str("            complex_ids: vec![None; model.complex_units.items.len()],\n");
    }
    s.push_str("        }\n    }\n\n");
    s.push_str("    fn fresh(&mut self) -> u64 { let n = self.next; self.next += 1; n }\n\n");

    // emit_<entity> per simple
    for se in &ir.simples {
        emit_write_simple(&mut s, ir, se);
    }
    // ref-enum -> emit dispatch
    let mut refs: Vec<_> = ir.ref_enums.values().collect();
    refs.sort_by(|a, b| a.rust.cmp(&b.rust));
    for re in refs {
        emit_write_ref(&mut s, re);
    }
    if ir.has_part_bag {
        emit_write_complex(&mut s, ir);
    }

    // emit_all
    s.push_str("    pub fn emit_all(mut self) -> String {\n");
    if ir.has_part_bag {
        s.push_str("        for i in 0..self.model.complex_units.items.len() { self.emit_complex(ComplexUnitId(i)); }\n");
    }
    for se in &ir.simples {
        writeln!(
            s,
            "        for i in 0..self.model.{}.items.len() {{ self.emit_{}({}Id(i)); }}",
            arena_field(&se.rust),
            arena_field(&se.rust),
            se.rust
        )
        .unwrap();
    }
    s.push_str("        self.out\n    }\n}\n\n");

    // wrap_step
    s.push_str(
        "pub fn wrap_step(data_body: &str) -> String {\n    format!(\n        \"ISO-10303-21;\\nHEADER;\\nFILE_DESCRIPTION((''),'2;1');\\n\\\n         FILE_NAME('','',(''),(''),'','','');\\n\\\n         FILE_SCHEMA(('AUTOMOTIVE_DESIGN'));\\nENDSEC;\\nDATA;\\n{data_body}ENDSEC;\\n\\\n         END-ISO-10303-21;\\n\"\n    )\n}\n",
    );

    s
}

fn ids_field(rust: &str) -> String {
    format!("{}_ids", arena_field(rust).trim_end_matches('s'))
}

/// Emit a simple entity's topo `emit_<entity>` method.
fn emit_write_simple(s: &mut String, ir: &ModelIr, se: &SimpleEnt) {
    let af = arena_field(&se.rust);
    let idsf = ids_field(&se.rust);
    writeln!(
        s,
        "    fn emit_{af}(&mut self, id: {}Id) -> u64 {{",
        se.rust
    )
    .unwrap();
    writeln!(
        s,
        "        if let Some(n) = self.{idsf}[id.0] {{ return n; }}"
    )
    .unwrap();
    // Take a clone of the item so we can recurse to emit deps without borrow issues.
    writeln!(s, "        let it = self.model.{af}.get(id.0).clone();").unwrap();
    // emit dep refs first; collect rendered attr strings in order
    let kept = idents(&se.fields);
    let mut parts: Vec<String> = Vec::new();
    for (id, f) in &kept {
        if f.derived {
            parts.push("\"*\".to_string()".to_string());
            continue;
        }
        let access = format!("it.{id}");
        parts.push(render_attr(ir, &f.kind, f.optional, f.derivable, &access));
    }
    // Allocate self id AFTER deps (topo).
    writeln!(s, "        let n = self.fresh();").unwrap();
    writeln!(s, "        self.{idsf}[id.0] = Some(n);").unwrap();
    // Build the attr render lines.
    // We rendered deps inline above as let-bindings appended to `s`; here we
    // join the pre-stored attr expressions.
    writeln!(
        s,
        "        let attrs: Vec<String> = vec![{}];",
        parts.join(", ")
    )
    .unwrap();
    writeln!(
        s,
        "        self.out.push_str(&format!(\"#{{n}} = {}({{}});\\n\", attrs.join(\",\")));",
        se.name
    )
    .unwrap();
    s.push_str("        n\n    }\n\n");
}

/// Render one attribute to a `String` expression. `access` is the field
/// accessor. An optional field renders `None` as `$`; a derivable field renders
/// `None` as `*`.
fn render_attr(ir: &ModelIr, k: &Kind, optional: bool, derivable: bool, access: &str) -> String {
    let wrapped = optional || derivable;
    let none_tok = if derivable { "*" } else { "$" };
    match k {
        Kind::Ref(t) => {
            let re = &ir.ref_enums[t];
            if wrapped {
                format!(
                    "match &{access} {{ Some(r) => {}, None => \"{none_tok}\".to_string() }}",
                    render_ref_value(re, "r")
                )
            } else {
                render_ref_value(re, &format!("&{access}"))
            }
        }
        Kind::Vec(inner) => {
            let elem = render_vec_elem(ir, inner);
            let body = format!(
                "format!(\"({{}})\", {access}.iter().map(|e| {elem}).collect::<Vec<_>>().join(\",\"))"
            );
            if wrapped {
                format!(
                    "match &{access} {{ Some(v) => format!(\"({{}})\", v.iter().map(|e| {elem}).collect::<Vec<_>>().join(\",\")), None => \"{none_tok}\".to_string() }}"
                )
            } else {
                body
            }
        }
        scalar => {
            let body = render_scalar(ir, scalar, access);
            if wrapped {
                format!(
                    "match &{access} {{ Some(x) => {}, None => \"{none_tok}\".to_string() }}",
                    render_scalar_ref(ir, scalar, "x")
                )
            } else {
                body
            }
        }
    }
}

/// Render a ref-enum value (given by a `&{re.rust}` expression `v`) to a String
/// expr: `#n` for a single arm; `(#a,#b)` for an aggregate arm. ref-enums are
/// non-Copy, so the dispatch clones the value it hands to `emit_*`.
fn render_ref_value(re: &RefEnum, v: &str) -> String {
    let m = ref_method(&re.rust);
    let mut arms: Vec<String> = Vec::new();
    for (aggv, elt_ref, wire) in &re.aggregate {
        let em = ref_method(elt_ref);
        // named aggregate -> Typed literal `WIRE((#a,#b))`.
        arms.push(format!(
            "{rust}::{aggv}(vs) => format!(\"{wire}(({{}}))\", vs.iter().map(|e| format!(\"#{{}}\", self.emit_{em}(e.clone()))).collect::<Vec<_>>().join(\",\")),",
            rust = re.rust
        ));
    }
    for (ev, _, wire) in &re.enum_arms {
        // named enum select member -> Typed literal `WIRE(.TOKEN.)` (token() has dots).
        arms.push(format!(
            "{rust}::{ev}(e) => format!(\"{wire}({{}})\", e.token()),",
            rust = re.rust
        ));
    }
    if arms.is_empty() {
        format!("format!(\"#{{}}\", self.emit_{m}(({v}).clone()))")
    } else {
        format!(
            "match {v} {{ {} other => format!(\"#{{}}\", self.emit_{m}(other.clone())) }}",
            arms.join(" ")
        )
    }
}

fn render_scalar(_ir: &ModelIr, k: &Kind, access: &str) -> String {
    match k {
        Kind::Real => format!("real({access})"),
        Kind::Int => format!("format!(\"{{}}\", {access})"),
        Kind::Str => format!("step_str(&{access})"),
        Kind::Bool => format!("(if {access} {{ \".T.\" }} else {{ \".F.\" }}).to_string()"),
        Kind::Logical => format!("{access}.token().to_string()"),
        Kind::Binary => format!("format!(\"'{{}}'\", {access})"),
        Kind::MeasureSelect(_) => format!("measure(&{access})"),
        Kind::StringSelect(_) => format!("string_select(&{access})"),
        Kind::Enum(_) => format!("{access}.token().to_string()"),
        _ => unreachable!(),
    }
}

/// Same as render_scalar but for a `&T` binding (optional Some case).
fn render_scalar_ref(_ir: &ModelIr, k: &Kind, access: &str) -> String {
    match k {
        Kind::Real => format!("real(*{access})"),
        Kind::Int => format!("format!(\"{{}}\", {access})"),
        Kind::Str => format!("step_str({access})"),
        Kind::Bool => format!("(if *{access} {{ \".T.\" }} else {{ \".F.\" }}).to_string()"),
        Kind::Logical => format!("{access}.token().to_string()"),
        Kind::Binary => format!("format!(\"'{{}}'\", {access})"),
        Kind::MeasureSelect(_) => format!("measure({access})"),
        Kind::StringSelect(_) => format!("string_select({access})"),
        Kind::Enum(_) => format!("{access}.token().to_string()"),
        _ => unreachable!(),
    }
}

fn render_vec_elem(ir: &ModelIr, inner: &Kind) -> String {
    match inner {
        Kind::Ref(t) => {
            let re = &ir.ref_enums[t];
            render_ref_value(re, "e")
        }
        Kind::Vec(i2) => {
            // nested list (e.g. control_points_list grid). Rebind inner elem to `e`.
            let inner_elem = render_vec_elem(ir, i2);
            format!(
                "{{ let row: Vec<String> = e.iter().map(|e| {inner_elem}).collect(); format!(\"({{}})\", row.join(\",\")) }}"
            )
        }
        Kind::Real => "real(*e)".to_string(),
        Kind::Int => "format!(\"{e}\")".to_string(),
        Kind::Str => "step_str(e)".to_string(),
        Kind::Logical => "e.token().to_string()".to_string(),
        Kind::Enum(_) => "e.token().to_string()".to_string(),
        _ => "real(*e)".to_string(),
    }
}

fn ref_method(re_rust: &str) -> String {
    // CurveRef -> ref_curve  (method name for the ref dispatch)
    let base = re_rust.trim_end_matches("Ref");
    let mut out = String::new();
    for (i, c) in base.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    format!("ref_{out}")
}

/// Emit the ref-enum dispatch method (emit the right arena's item).
fn emit_write_ref(s: &mut String, re: &RefEnum) {
    writeln!(
        s,
        "    fn emit_{}(&mut self, r: {}) -> u64 {{ match r {{",
        ref_method(&re.rust),
        re.rust
    )
    .unwrap();
    for (variant, target) in &re.simple_arms {
        writeln!(
            s,
            "        {}::{variant}(i) => self.emit_{}(i),",
            re.rust,
            arena_field(target)
        )
        .unwrap();
    }
    if re.has_complex {
        writeln!(
            s,
            "        {}::Complex(i) => self.emit_complex(i),",
            re.rust
        )
        .unwrap();
    }
    // Aggregate/enum arms are rendered (as `(...)` / `.TOKEN.`) by
    // render_ref_value before this single-id dispatch is reached, so they never
    // arrive here.
    for (variant, _, _) in &re.aggregate {
        writeln!(
            s,
            "        {}::{variant}(_) => panic!(\"emit aggregate ref via single dispatch\"),",
            re.rust
        )
        .unwrap();
    }
    for (variant, _, _) in &re.enum_arms {
        writeln!(
            s,
            "        {}::{variant}(_) => panic!(\"emit enum ref via single dispatch\"),",
            re.rust
        )
        .unwrap();
    }
    if re.simple_arms.is_empty()
        && re.aggregate.is_empty()
        && re.enum_arms.is_empty()
        && !re.has_complex
    {
        // empty ref-enum: the Unresolved placeholder is never emitted (referrer
        // escapes), but the match must be exhaustive.
        writeln!(
            s,
            "        {}::Unresolved => panic!(\"emit unresolved ref\"),",
            re.rust
        )
        .unwrap();
    }
    s.push_str("    } }\n\n");
}

/// Emit the complex part-bag topo method.
fn emit_write_complex(s: &mut String, ir: &ModelIr) {
    s.push_str("    fn emit_complex(&mut self, id: ComplexUnitId) -> u64 {\n");
    s.push_str("        if let Some(n) = self.complex_ids[id.0] { return n; }\n");
    s.push_str("        let cu = self.model.complex_units.get(id.0).clone();\n");
    s.push_str("        let mut part_txt: Vec<String> = Vec::with_capacity(cu.parts.len());\n");
    s.push_str("        for part in &cu.parts {\n            part_txt.push(match part {\n");
    for p in &ir.parts {
        let kept = idents(&p.fields);
        let nonderived: Vec<_> = kept.iter().filter(|(_, f)| !f.derived).collect();
        if kept.is_empty() {
            writeln!(
                s,
                "                UnitPart::{} => \"{}()\".to_string(),",
                p.rust, p.name
            )
            .unwrap();
            continue;
        }
        // bind all kept (incl derived rendered as *)
        let binders: Vec<String> = nonderived.iter().map(|(id, _)| id.clone()).collect();
        write!(
            s,
            "                UnitPart::{} {{ {} }} => {{",
            p.rust,
            if binders.is_empty() {
                ".. ".to_string()
            } else {
                format!("{}, ..", binders.join(", "))
            }
        )
        .unwrap();
        // render each attr in positional order
        let mut rendered: Vec<String> = Vec::new();
        for (id, f) in &kept {
            if f.derived {
                rendered.push("\"*\".to_string()".to_string());
            } else {
                rendered.push(render_part_attr(ir, &f.kind, f.optional, f.derivable, id));
            }
        }
        write!(s, " let a: Vec<String> = vec![{}];", rendered.join(", ")).unwrap();
        writeln!(s, " format!(\"{}({{}})\", a.join(\",\")) }},", p.name).unwrap();
    }
    s.push_str("            });\n        }\n");
    s.push_str("        let n = self.fresh();\n        self.complex_ids[id.0] = Some(n);\n");
    s.push_str("        self.out.push_str(&format!(\"#{n} = ( {} );\\n\", part_txt.join(\" \")));\n        n\n    }\n\n");
}

/// Render a complex part attribute (the binder `id` is a `&T` reference).
fn render_part_attr(ir: &ModelIr, k: &Kind, optional: bool, derivable: bool, id: &str) -> String {
    let wrapped = optional || derivable;
    let none_tok = if derivable { "*" } else { "$" };
    match k {
        Kind::Ref(t) => {
            let re = &ir.ref_enums[t];
            if wrapped {
                format!(
                    "match {id} {{ Some(r) => {}, None => \"{none_tok}\".to_string() }}",
                    render_ref_value(re, "r")
                )
            } else {
                render_ref_value(re, id)
            }
        }
        Kind::Vec(inner) => {
            let elem = render_vec_elem(ir, inner);
            if wrapped {
                format!(
                    "match {id} {{ Some(v) => format!(\"({{}})\", v.iter().map(|e| {elem}).collect::<Vec<_>>().join(\",\")), None => \"{none_tok}\".to_string() }}"
                )
            } else {
                format!(
                    "format!(\"({{}})\", {id}.iter().map(|e| {elem}).collect::<Vec<_>>().join(\",\"))"
                )
            }
        }
        scalar => {
            if wrapped {
                format!(
                    "match {id} {{ Some(x) => {}, None => \"{none_tok}\".to_string() }}",
                    render_scalar_ref(ir, scalar, "x")
                )
            } else {
                render_scalar_ref(ir, scalar, id)
            }
        }
    }
}

// ===========================================================================
// normalize.rs — strict-input normalization (slot-kind general rules).
// Runs on the raw graph BEFORE the strict read: rewrites non-standard values to
// standard (record a NormCase note), or — when not normalizable (required ref =
// `$`) — drops the entity (its referrers cascade-drop via the round-trip subset
// escape filter). The model/read stay strict; nothing here bends them.
// ===========================================================================

/// Top-level slot kind tag for the normalize rule table.
fn sk_variant(k: &Kind) -> &'static str {
    match k {
        Kind::Real => "Real",
        Kind::Int => "Int",
        Kind::Str => "Str",
        Kind::Binary => "Bin",
        Kind::Bool => "Bool",
        Kind::Logical => "Log",
        Kind::Enum(_) => "Enum",
        Kind::Ref(_) => "Ref",
        Kind::Vec(_) => "Vec",
        Kind::MeasureSelect(_) => "Meas",
        // string-select required `$` -> req-str<-$ normalizes to "" (read as bare).
        Kind::StringSelect(_) => "Str",
    }
}

fn emit_slot_table<'a>(
    s: &mut String,
    fname: &str,
    ents: impl Iterator<Item = (&'a String, &'a Vec<Field>)>,
) {
    writeln!(s, "fn {fname}(n: &str) -> &'static [Slot] {{").unwrap();
    s.push_str("    match n {\n");
    for (name, fields) in ents {
        let slots: Vec<String> = fields
            .iter()
            .map(|f| {
                let k = sk_variant(&f.kind);
                let req = !(f.optional || f.derivable);
                format!("Slot{{k:Sk::{k},req:{req},der:{}}}", f.derived)
            })
            .collect();
        writeln!(s, "        \"{}\" => &[{}],", name, slots.join(",")).unwrap();
    }
    s.push_str("        _ => &[],\n    }\n}\n\n");
}

pub fn emit_normalize(ir: &ModelIr) -> String {
    let mut s = String::from(HEADER);
    s.push_str("use std::collections::BTreeMap;\nuse step_io::{Attribute, RawEntity};\n\n");
    s.push_str(
        r#"#[derive(Clone, Copy)]
enum Sk { Real, Int, Str, Bin, Bool, Log, Enum, Ref, Vec, Meas }
#[derive(Clone, Copy)]
struct Slot { k: Sk, req: bool, der: bool }

/// Value-level canonical: signed-zero -0.0 -> +0.0, recursively (incl. lists).
fn canon(a: &mut Attribute) {
    match a {
        Attribute::Real(r) => { if *r == 0.0 { *r = 0.0_f64; } }
        Attribute::List(v) => { for e in v.iter_mut() { canon(e); } }
        Attribute::Typed { value, .. } => canon(value),
        _ => {}
    }
}

enum Na { Keep, Set(Attribute, &'static str), Drop(&'static str) }

/// Slot-kind general rules (single rule per slot, output is the final standard
/// value). Value rules (int<->real) apply regardless of req; the `$`/`*` rules
/// apply per req/derived.
fn norm_attr(s: Slot, a: &Attribute) -> Na {
    if s.der {
        // a derived slot is always `*` on the wire; force it (drops a redundant
        // explicit value or a non-standard `()`/`$`).
        return if matches!(a, Attribute::Derived) { Na::Keep }
               else { Na::Set(Attribute::Derived, "derived->*") };
    }
    match (s.k, a) {
        (Sk::Real, Attribute::Integer(i)) => Na::Set(Attribute::Real(*i as f64), "int->real"),
        (Sk::Int, Attribute::Real(r)) if r.fract() == 0.0 => {
            Na::Set(Attribute::Integer(*r as i64), "real->int")
        }
        (Sk::Int, Attribute::Real(_)) => Na::Drop("int<-fractional-real"),
        (Sk::Str | Sk::Bin, Attribute::Unset) if s.req => {
            Na::Set(Attribute::String(String::new()), "req-str<-$")
        }
        (Sk::Vec, Attribute::Unset) if s.req => Na::Set(Attribute::List(Vec::new()), "req-vec<-$"),
        (Sk::Ref, Attribute::Unset) if s.req => Na::Drop("req-ref<-$"),
        _ => Na::Keep,
    }
}

fn norm_attrs(slots: &[Slot], attrs: &mut Vec<Attribute>, warns: &mut Vec<&'static str>) -> bool {
    for (i, a) in attrs.iter_mut().enumerate() {
        canon(a);
        if let Some(s) = slots.get(i).copied() {
            match norm_attr(s, a) {
                Na::Keep => {}
                Na::Set(na, w) => { *a = na; warns.push(w); }
                Na::Drop(w) => { warns.push(w); return false; }
            }
        }
    }
    true
}

/// Normalize the raw graph in place. Returns the surviving map (non-normalizable
/// entities removed; their referrers cascade-drop later via the subset escape
/// filter) and the NormCase notes (one per rewrite/drop).
pub fn normalize(mut map: BTreeMap<u64, RawEntity>) -> (BTreeMap<u64, RawEntity>, Vec<&'static str>) {
    let mut warns: Vec<&'static str> = Vec::new();
    let mut drop_ids: Vec<u64> = Vec::new();
    for (&id, ent) in map.iter_mut() {
        let keep = match ent {
            RawEntity::Simple { name, attributes, .. } => {
                norm_attrs(simple_slots(name), attributes, &mut warns)
            }
            RawEntity::Complex { parts, .. } => {
                let mut ok = true;
                for p in parts.iter_mut() {
                    if !norm_attrs(part_slots(&p.name), &mut p.attributes, &mut warns) {
                        ok = false;
                        break;
                    }
                }
                ok
            }
        };
        if !keep {
            drop_ids.push(id);
        }
    }
    for id in drop_ids {
        map.remove(&id);
    }
    (map, warns)
}

"#,
    );
    emit_slot_table(
        &mut s,
        "simple_slots",
        ir.simples.iter().map(|se| (&se.name, &se.fields)),
    );
    emit_slot_table(
        &mut s,
        "part_slots",
        ir.parts.iter().map(|p| (&p.name, &p.fields)),
    );
    s
}
