//! Emit Rust source (model / read / write) from the resolved [`ModelIr`].

use std::fmt::Write as _;

use crate::classify::Kind;
use crate::model_ir::{Field, ModelIr, RefEnum, SimpleEnt};

const HEADER: &str = "// @generated by codegen. DO NOT EDIT.\n// Schema-faithful model + generic 2-pass read + topo write.\n\n";

/// Field Rust type for a `Kind` (+ optional / derivable wrapper). A derivable
/// slot (conditionally `*`) is modeled as `Option<T>` (`None` => `*`).
fn field_type(ir: &ModelIr, f: &Field) -> String {
    let base = kind_type(ir, &f.kind);
    if f.optional || f.derivable {
        format!("Option<{base}>")
    } else {
        base
    }
}

fn kind_type(ir: &ModelIr, k: &Kind) -> String {
    match k {
        Kind::Ref(t) => ir.ref_enums[t].rust.clone(),
        Kind::Vec(inner) => format!("Vec<{}>", kind_type(ir, inner)),
        Kind::Real => "f64".into(),
        Kind::Int => "i64".into(),
        Kind::Bool => "bool".into(),
        Kind::Logical => "Logical".into(),
        Kind::Str => "String".into(),
        Kind::Binary => "String".into(),
        Kind::Enum(a) => ir.enums[a].rust.clone(),
        Kind::MeasureSelect(_) => "MeasureValue".into(),
        Kind::StringSelect(_) => "StringSelectValue".into(),
        Kind::IntSelect(_) => "IntMeasureValue".into(),
    }
}

/// Sanitize a field name into a valid Rust ident (handles `ref`, dup names).
fn field_ident(name: &str, used: &mut std::collections::BTreeMap<String, u32>) -> String {
    let raw = match name {
        "ref" | "type" | "self" | "loop" | "box" | "move" => format!("r#{name}"),
        _ => name.to_string(),
    };
    let n = used.entry(name.to_string()).or_insert(0);
    let out = if *n == 0 { raw } else { format!("{raw}_{n}") };
    *n += 1;
    out
}

/// Build the (ident, field) list for a struct/part, deduping names.
fn idents(fields: &[Field]) -> Vec<(String, &Field)> {
    let mut used = std::collections::BTreeMap::new();
    fields
        .iter()
        .map(|f| (field_ident(&f.name, &mut used), f))
        .collect()
}

// ===========================================================================
// model.rs
// ===========================================================================

pub fn emit_model(ir: &ModelIr) -> String {
    let mut s = String::from(HEADER);

    // Arena + helpers.
    s.push_str(
        r#"#[derive(Debug)]
pub struct Arena<T> { pub items: Vec<T> }
impl<T> Default for Arena<T> { fn default() -> Self { Arena { items: Vec::new() } } }
impl<T> Arena<T> {
    pub fn push(&mut self, v: T) -> usize { let i = self.items.len(); self.items.push(v); i }
    pub fn get(&self, i: usize) -> &T { &self.items[i] }
}

/// EXPRESS LOGICAL (.T./.F./.U.).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Logical { True, False, Unknown }
impl Logical {
    pub fn parse(s: &str) -> Option<Self> {
        Some(match s { "T" => Self::True, "F" => Self::False, "U" | "UNKNOWN" => Self::Unknown, _ => return None })
    }
    pub fn token(self) -> &'static str {
        match self { Self::True => ".T.", Self::False => ".F.", Self::Unknown => ".U." }
    }
}

/// select-of-scalars: `Some(type_name)` = typed member `TYPE(v)`; `None` = bare.
/// `value` is int-or-real because EXPRESS `number` members (count_measure,
/// numeric_measure) admit both; the token is preserved (2 stays 2, not 2.0).
#[derive(Debug, Clone, PartialEq)]
pub enum MeasureScalar { Int(i64), Real(f64) }
impl MeasureScalar { pub fn as_f64(&self) -> f64 { match self { Self::Int(i) => *i as f64, Self::Real(r) => *r } } }
#[derive(Debug, Clone, PartialEq)]
pub struct MeasureValue { pub type_name: Option<String>, pub value: MeasureScalar }

/// select-of-named-strings (e.g. SELECT(identifier, message)): `Some(type_name)`
/// = typed member `TYPE('s')`; `None` = bare string.
#[derive(Debug, Clone, PartialEq)]
pub struct StringSelectValue { pub type_name: Option<String>, pub value: String }

/// select-of-named-integers (e.g. SELECT(u_direction_count, v_direction_count)):
/// `Some(type_name)` = typed member `TYPE(2)`; `None` = bare integer. Integer-
/// valued so counts are not widened to reals.
#[derive(Debug, Clone, PartialEq)]
pub struct IntMeasureValue { pub type_name: Option<String>, pub value: i64 }

"#,
    );

    // ENUMs.
    let mut enums: Vec<_> = ir.enums.values().collect();
    enums.sort_by(|a, b| a.rust.cmp(&b.rust));
    for e in enums {
        writeln!(s, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]").unwrap();
        writeln!(s, "pub enum {} {{", e.rust).unwrap();
        for (_, v) in &e.members {
            writeln!(s, "    {v},").unwrap();
        }
        writeln!(s, "}}").unwrap();
        writeln!(s, "impl {} {{", e.rust).unwrap();
        writeln!(
            s,
            "    pub fn parse(s: &str) -> Option<Self> {{ Some(match s {{"
        )
        .unwrap();
        for (tok, v) in &e.members {
            writeln!(s, "        \"{tok}\" => Self::{v},").unwrap();
        }
        writeln!(s, "        _ => return None }}) }}").unwrap();
        writeln!(s, "    pub fn token(self) -> &'static str {{ match self {{").unwrap();
        for (tok, v) in &e.members {
            writeln!(s, "        Self::{v} => \".{tok}.\",").unwrap();
        }
        writeln!(s, "    }} }}\n}}\n").unwrap();
    }

    // Id newtypes.
    for se in &ir.simples {
        writeln!(
            s,
            "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub struct {}Id(pub usize);",
            se.rust
        )
        .unwrap();
    }
    if ir.has_part_bag {
        writeln!(
            s,
            "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub struct ComplexUnitId(pub usize);"
        )
        .unwrap();
    }
    s.push('\n');

    // AnyId: one variant per arena (read idmap value).
    writeln!(
        s,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub enum AnyId {{"
    )
    .unwrap();
    for se in &ir.simples {
        writeln!(s, "    {}({}Id),", se.rust, se.rust).unwrap();
    }
    if ir.has_part_bag {
        writeln!(s, "    ComplexUnit(ComplexUnitId),").unwrap();
    }
    writeln!(s, "}}\n").unwrap();

    // Ref enums.
    let mut refs: Vec<_> = ir.ref_enums.values().collect();
    refs.sort_by(|a, b| a.rust.cmp(&b.rust));
    for re in refs {
        emit_ref_enum(&mut s, re);
    }

    // Simple structs.
    for se in &ir.simples {
        writeln!(
            s,
            "#[derive(Debug, Clone, PartialEq)]\npub struct {} {{",
            se.rust
        )
        .unwrap();
        for (id, f) in idents(&se.fields) {
            if f.derived {
                continue;
            }
            writeln!(s, "    pub {id}: {},", field_type(ir, f)).unwrap();
        }
        writeln!(s, "}}\n").unwrap();
    }

    // Part-bag.
    if ir.has_part_bag {
        writeln!(
            s,
            "#[derive(Debug, Clone, PartialEq)]\npub enum UnitPart {{"
        )
        .unwrap();
        for p in &ir.parts {
            let kept: Vec<_> = idents(&p.fields)
                .into_iter()
                .filter(|(_, f)| !f.derived)
                .collect();
            if kept.is_empty() {
                writeln!(s, "    {},", p.rust).unwrap();
            } else {
                write!(s, "    {} {{ ", p.rust).unwrap();
                for (id, f) in &kept {
                    write!(s, "{id}: {}, ", field_type(ir, f)).unwrap();
                }
                writeln!(s, "}},").unwrap();
            }
        }
        writeln!(s, "}}\n").unwrap();
        writeln!(
            s,
            "#[derive(Debug, Clone, PartialEq)]\npub struct ComplexUnit {{ pub parts: Vec<UnitPart> }}\n"
        )
        .unwrap();
    }

    // Top-level StepModel.
    writeln!(s, "#[derive(Debug, Default)]\npub struct StepModel {{").unwrap();
    for se in &ir.simples {
        writeln!(s, "    pub {}: Arena<{}>,", arena_field(&se.rust), se.rust).unwrap();
    }
    if ir.has_part_bag {
        writeln!(s, "    pub complex_units: Arena<ComplexUnit>,").unwrap();
    }
    writeln!(s, "}}").unwrap();

    s
}

/// Payload type for a scalar ref-enum arm. Reuses the select-of-scalars values,
/// which carry `type_name: Option` so the typed (`WIRE(5.)`) vs bare (`5.`) wire
/// form round-trips. (Only Real/Str scalar members occur; others surface here.)
fn scalar_rust_ty(k: &Kind) -> &'static str {
    match k {
        Kind::Real => "f64",
        Kind::Str => "String",
        _ => unreachable!("unsupported scalar arm kind: {k:?}"),
    }
}

fn emit_ref_enum(s: &mut String, re: &RefEnum) {
    // No `Copy` (aggregate arm holds a `Vec`) and no `Eq` (a scalar arm may hold
    // an `f64`, which is not `Eq`). PartialEq/Clone are enough — the model derives
    // only PartialEq. Clone at the few deref sites; compiler flags any missed.
    writeln!(
        s,
        "#[derive(Debug, Clone, PartialEq)]\npub enum {} {{",
        re.rust
    )
    .unwrap();
    for (variant, target) in &re.simple_arms {
        writeln!(s, "    {variant}({target}Id),").unwrap();
    }
    // Aggregate arms for SELECT(.., LIST OF E, SET OF E): hold Vec<{E}Ref>
    // (list/set collapse — wire-identical `(...)`).
    for (variant, elt_ref, _wire) in &re.aggregate {
        writeln!(s, "    {variant}(Vec<{elt_ref}>),").unwrap();
    }
    // Enum arms for SELECT(.., some_enum): hold the (Copy) generated enum; on the
    // wire a `.TOKEN.` literal, discriminated from a `#ref` at read time.
    for (variant, enum_rust, _wire) in &re.enum_arms {
        writeln!(s, "    {variant}({enum_rust}),").unwrap();
    }
    // Scalar arms for SELECT(.., parameter_value): hold the bare scalar value
    // (f64 / String). The wire form is always the typed literal `WIRE(value)`;
    // the form is not stored (write re-derives it from the arm's wire name).
    for (variant, sk, _wire) in &re.scalar_arms {
        writeln!(s, "    {variant}({}),", scalar_rust_ty(sk)).unwrap();
    }
    if re.has_complex {
        writeln!(s, "    Complex(ComplexUnitId),").unwrap();
    }
    // An enum with no arms at all (all ref targets out of closure, e.g. excluded)
    // would be uninhabited and make its referrer unconstructible. Such referrers
    // always escape the round-trip subset, so this variant is a never-resolved,
    // never-emitted placeholder that just keeps the generated code constructible.
    if re.simple_arms.is_empty()
        && re.aggregate.is_empty()
        && re.enum_arms.is_empty()
        && re.scalar_arms.is_empty()
        && !re.has_complex
    {
        writeln!(s, "    Unresolved,").unwrap();
    }
    writeln!(s, "}}").unwrap();
    // resolve from AnyId
    writeln!(s, "impl {} {{", re.rust).unwrap();
    writeln!(
        s,
        "    pub fn from_any(a: AnyId) -> Result<Self, String> {{ match a {{"
    )
    .unwrap();
    for (variant, target) in &re.simple_arms {
        writeln!(s, "        AnyId::{target}(i) => Ok(Self::{variant}(i)),").unwrap();
    }
    if re.has_complex {
        writeln!(s, "        AnyId::ComplexUnit(i) => Ok(Self::Complex(i)),").unwrap();
    }
    writeln!(
        s,
        "        other => Err(format!(\"expected {} target, got {{other:?}}\")),",
        re.rust
    )
    .unwrap();
    writeln!(s, "    }} }}\n}}\n").unwrap();
}

/// snake_case plural-ish arena field name for a struct rust name.
pub fn arena_field(rust: &str) -> String {
    let mut out = String::new();
    for (i, c) in rust.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out.push('s');
    out
}

// ===========================================================================
// read.rs — generic 2-pass.
// ===========================================================================

/// Does a kind carry an entity ref (resolved in pass 2)?
fn has_ref(k: &Kind) -> bool {
    match k {
        Kind::Ref(_) => true,
        Kind::Vec(inner) => has_ref(inner),
        _ => false,
    }
}

pub fn emit_read(ir: &ModelIr, crate_path: &str) -> String {
    let mut s = String::from(HEADER);
    s.push_str(&format!(
        "use std::collections::BTreeMap;\nuse {crate_path}::{{Attribute, RawEntity, RawEntityPart}};\nuse super::model::*;\n\n"
    ));

    // scalar readers (fallible)
    s.push_str(
        r#"// Strict scalar readers (fallible): the pre-read `normalize` layer rewrites
// non-standard values to standard form (or drops the entity); a reader seeing
// an off-kind value returns Err(<ctx>-tagged reason) so the caller drops just
// that entity (never panic). `ctx` is the "<ENTITY>.<field>" location literal.
fn req<'a>(attrs: &'a [Attribute], idx: usize, ctx: &str) -> Result<&'a Attribute, String> {
    attrs.get(idx).ok_or_else(|| format!("{ctx}: arity (missing attr {idx})"))
}
fn as_real(a: &Attribute, ctx: &str) -> Result<f64, String> {
    match a { Attribute::Real(r) => Ok(*r), other => Err(format!("{ctx}: expected real, got {other:?}")) }
}
fn as_int(a: &Attribute, ctx: &str) -> Result<i64, String> {
    match a { Attribute::Integer(i) => Ok(*i), other => Err(format!("{ctx}: expected int, got {other:?}")) }
}
fn as_str(a: &Attribute, ctx: &str) -> Result<String, String> {
    match a { Attribute::String(s) => Ok(s.clone()), other => Err(format!("{ctx}: expected string, got {other:?}")) }
}
fn as_logical(a: &Attribute, ctx: &str) -> Result<Logical, String> {
    match a { Attribute::Enum(s) => Logical::parse(s).ok_or_else(|| format!("{ctx}: bad logical {s:?}")), other => Err(format!("{ctx}: expected logical, got {other:?}")) }
}
fn as_ref_id(a: &Attribute, ctx: &str) -> Result<u64, String> {
    match a { Attribute::EntityRef(n) => Ok(*n), other => Err(format!("{ctx}: expected ref, got {other:?}")) }
}
fn read_measure_value(a: &Attribute, ctx: &str) -> Result<MeasureValue, String> {
    // A measure's numeric literal sits nested inside a Typed/bare attribute, so
    // it is not a top-level slot the normalize layer rewrites; preserve the
    // original token (integer vs real) — `number` members admit either.
    fn measure_scalar(a: &Attribute, ctx: &str) -> Result<MeasureScalar, String> {
        match a { Attribute::Real(r) => Ok(MeasureScalar::Real(*r)), Attribute::Integer(i) => Ok(MeasureScalar::Int(*i)), other => Err(format!("{ctx}: expected measure scalar, got {other:?}")) }
    }
    match a {
        Attribute::Typed { type_name, value } => Ok(MeasureValue { type_name: Some(type_name.clone()), value: measure_scalar(value, ctx)? }),
        Attribute::Real(_) | Attribute::Integer(_) => Ok(MeasureValue { type_name: None, value: measure_scalar(a, ctx)? }),
        other => Err(format!("{ctx}: expected measure_value, got {other:?}")),
    }
}
fn read_string_select(a: &Attribute, ctx: &str) -> Result<StringSelectValue, String> {
    // A named string select member is a Typed literal `TYPE('s')`; a bare string
    // is unwrapped. (Mirrors read_measure_value for the string case.)
    fn str_of(a: &Attribute, ctx: &str) -> Result<String, String> {
        match a { Attribute::String(s) => Ok(s.clone()), other => Err(format!("{ctx}: expected select string, got {other:?}")) }
    }
    match a {
        Attribute::Typed { type_name, value } => Ok(StringSelectValue { type_name: Some(type_name.clone()), value: str_of(value, ctx)? }),
        Attribute::String(s) => Ok(StringSelectValue { type_name: None, value: s.clone() }),
        other => Err(format!("{ctx}: expected string_select, got {other:?}")),
    }
}
fn read_int_measure_value(a: &Attribute, ctx: &str) -> Result<IntMeasureValue, String> {
    // Integer-valued select-of-scalars (mirrors read_measure_value but keeps the
    // value as i64). A non-standard real literal is truncated (NORM).
    fn int_of(a: &Attribute, ctx: &str) -> Result<i64, String> {
        match a { Attribute::Integer(i) => Ok(*i), Attribute::Real(r) => Ok(*r as i64), other => Err(format!("{ctx}: expected measure int, got {other:?}")) }
    }
    match a {
        Attribute::Typed { type_name, value } => Ok(IntMeasureValue { type_name: Some(type_name.clone()), value: int_of(value, ctx)? }),
        Attribute::Integer(_) | Attribute::Real(_) => Ok(IntMeasureValue { type_name: None, value: int_of(a, ctx)? }),
        other => Err(format!("{ctx}: expected int_measure_value, got {other:?}")),
    }
}

"#,
    );

    // ---- simple entity name table (closure subset filter) ----
    let simple_names: Vec<String> = ir
        .simples
        .iter()
        .map(|se| format!("\"{}\"", se.name))
        .collect();
    writeln!(
        s,
        "pub const SIMPLE_NAMES: &[&str] = &[{}];",
        simple_names.join(", ")
    )
    .unwrap();

    // ---- dispatch table for complex part-bag ----
    if ir.has_part_bag {
        let names: Vec<String> = ir.parts.iter().map(|p| format!("\"{}\"", p.name)).collect();
        writeln!(
            s,
            "pub const COMPLEX_PART_NAMES: &[&str] = &[{}];",
            names.join(", ")
        )
        .unwrap();
        s.push_str("pub fn is_complex_unit(parts: &[RawEntityPart]) -> bool { !parts.is_empty() && parts.iter().all(|p| COMPLEX_PART_NAMES.contains(&p.name.as_str())) }\n\n");
    } else {
        s.push_str("pub const COMPLEX_PART_NAMES: &[&str] = &[];\npub fn is_complex_unit(_parts: &[RawEntityPart]) -> bool { false }\n\n");
    }

    // subset membership predicate used by the round-trip filter.
    s.push_str("pub fn in_subset(ent: &RawEntity) -> bool {\n    match ent {\n        RawEntity::Simple { name, .. } => SIMPLE_NAMES.contains(&name.as_str()),\n        RawEntity::Complex { parts, .. } => is_complex_unit(parts),\n    }\n}\n\n");

    // ---- per-slot ref allow-list (nonstandard-ref detection) ----
    // For each ref slot of each entity/part: the standard target types this slot
    // admits (`allowed` = the ref-enum's simple arms as UPPER wire names, plus
    // `complex_ok` for a part-bag target). A ref whose target type is in the
    // closure but not in this list sits in a slot that does not admit it = a
    // schema-violating (nonstandard) reference.
    s.push_str("#[derive(Clone, Copy)]\npub struct RefSlot { pub idx: usize, pub name: &'static str, pub allowed: &'static [&'static str], pub complex_ok: bool, pub is_vec: bool }\n\n");
    let rust_to_name: std::collections::HashMap<&str, &str> = ir
        .simples
        .iter()
        .map(|se| (se.rust.as_str(), se.name.as_str()))
        .collect();
    emit_ref_slot_table(
        &mut s,
        "ref_slots",
        ir,
        &rust_to_name,
        ir.simples.iter().map(|se| (&se.name, &se.fields)),
    );
    emit_ref_slot_table(
        &mut s,
        "complex_ref_slots",
        ir,
        &rust_to_name,
        ir.parts.iter().map(|p| (&p.name, &p.fields)),
    );

    // ---- build_* fns (pass1, fallible) ----
    for se in &ir.simples {
        emit_build(&mut s, ir, se);
    }

    // ---- read() ----
    s.push_str(
        "pub fn read(map: &BTreeMap<u64, RawEntity>) -> (StepModel, BTreeMap<u64, AnyId>, Vec<(u64, String)>) {\n",
    );
    s.push_str("    let mut model = StepModel::default();\n");
    s.push_str("    let mut idmap: BTreeMap<u64, AnyId> = BTreeMap::new();\n");
    s.push_str("    let mut read_drops: Vec<(u64, String)> = Vec::new();\n");
    // pending lists for pass 2
    for se in &ir.simples {
        if se.fields.iter().any(|f| has_ref(&f.kind)) {
            writeln!(
                s,
                "    let mut pending_{}: Vec<({}Id, u64)> = Vec::new();",
                arena_field(&se.rust),
                se.rust
            )
            .unwrap();
        }
    }
    if ir.has_part_bag {
        s.push_str("    let mut pending_complex: Vec<(ComplexUnitId, u64)> = Vec::new();\n");
    }

    s.push_str("    for (&id, ent) in map {\n        match ent {\n");
    // simple dispatch arms (exact name match) — pass1 build is fallible; an
    // unreadable own-attr drops just this entity (no panic, surfaced as reason).
    for se in &ir.simples {
        let af = arena_field(&se.rust);
        let has_r = se.fields.iter().any(|f| has_ref(&f.kind));
        writeln!(
            s,
            "            RawEntity::Simple {{ name, attributes, .. }} if name == \"{}\" => {{",
            se.name
        )
        .unwrap();
        writeln!(s, "                match build_{af}(attributes) {{").unwrap();
        s.push_str("                    Ok(v) => {\n");
        writeln!(
            s,
            "                        let aid = {}Id(model.{af}.push(v));",
            se.rust
        )
        .unwrap();
        writeln!(
            s,
            "                        idmap.insert(id, AnyId::{}(aid));",
            se.rust
        )
        .unwrap();
        if has_r {
            writeln!(s, "                        pending_{af}.push((aid, id));").unwrap();
        }
        s.push_str("                    }\n");
        s.push_str("                    Err(e) => read_drops.push((id, e)),\n");
        s.push_str("                }\n");
        s.push_str("            }\n");
    }
    // complex dispatch
    if ir.has_part_bag {
        s.push_str("            RawEntity::Complex { parts, .. } if is_complex_unit(parts) => {\n");
        s.push_str("                match read_complex_parts_norefs(parts) {\n");
        s.push_str("                    Ok(bag) => {\n");
        s.push_str("                        let aid = ComplexUnitId(model.complex_units.push(ComplexUnit { parts: bag }));\n");
        s.push_str("                        idmap.insert(id, AnyId::ComplexUnit(aid));\n");
        s.push_str("                        pending_complex.push((aid, id));\n");
        s.push_str("                    }\n");
        s.push_str("                    Err(e) => read_drops.push((id, e)),\n");
        s.push_str("                }\n");
        s.push_str("            }\n");
    }
    s.push_str("            _ => {}\n        }\n    }\n");

    // ---- pass 2 (fallible ref resolution) ----
    for se in &ir.simples {
        if !se.fields.iter().any(|f| has_ref(&f.kind)) {
            continue;
        }
        let af = arena_field(&se.rust);
        writeln!(s, "    for (aid, raw) in pending_{af} {{").unwrap();
        writeln!(
            s,
            "        if let Some(RawEntity::Simple {{ attributes, .. }}) = map.get(&raw) {{"
        )
        .unwrap();
        writeln!(
            s,
            "            if let Err(e) = resolve_{af}(&mut model, aid, attributes, &idmap) {{ read_drops.push((raw, e)); }}"
        )
        .unwrap();
        s.push_str("        }\n    }\n");
    }
    if ir.has_part_bag {
        s.push_str("    for (aid, raw) in pending_complex {\n");
        s.push_str("        if let Some(RawEntity::Complex { parts, .. }) = map.get(&raw) {\n");
        s.push_str(
            "            if let Err(e) = resolve_complex(&mut model, aid, parts, &idmap) { read_drops.push((raw, e)); }\n        }\n    }\n",
        );
    }
    s.push_str("    (model, idmap, read_drops)\n}\n\n");

    // ---- resolve fns ----
    for se in &ir.simples {
        if se.fields.iter().any(|f| has_ref(&f.kind)) {
            emit_resolve(&mut s, ir, se);
        }
    }
    if ir.has_part_bag {
        emit_complex_read(&mut s, ir);
    }

    s
}

/// pass1 builder fn (fallible): `fn build_{af}(attributes) -> Result<{Ent}, String>`.
/// Binds non-ref fields from own attributes (ref fields get a placeholder patched
/// in pass2). A short/off-kind own attribute returns Err(<ctx> reason) so the
/// caller drops just this entity (no panic). `ctx` = "<ENTITY>.<field>".
fn emit_build(s: &mut String, ir: &ModelIr, se: &SimpleEnt) {
    let af = arena_field(&se.rust);
    writeln!(
        s,
        "fn build_{af}(attributes: &[Attribute]) -> Result<{}, String> {{",
        se.rust
    )
    .unwrap();
    writeln!(s, "    Ok({} {{", se.rust).unwrap();
    let mut idx = 0usize;
    for (id, f) in idents(&se.fields) {
        if f.derived {
            idx += 1; // slot kept on wire, no field
            continue;
        }
        let expr = if has_ref(&f.kind) {
            ref_placeholder(ir, &f.kind, f.optional || f.derivable)
        } else {
            let ctx = format!("{}.{}", se.name, id);
            // `.get(idx).ok_or(..)?` (no raw indexing) guards arity per slot.
            let access = format!("req(attributes, {idx}, {ctx:?})?");
            if f.derivable {
                bind_derivable_scalar(ir, &f.kind, &access, &ctx)
            } else {
                bind_scalar(ir, &f.kind, f.optional, &access, &ctx)
            }
        };
        writeln!(s, "        {id}: {expr},").unwrap();
        idx += 1;
    }
    s.push_str("    })\n}\n\n");
}

/// Bind a derivable (conditionally `*`) scalar: `*` => None, else Some(value).
/// `access` evaluates to `&Attribute`.
fn bind_derivable_scalar(ir: &ModelIr, k: &Kind, access: &str, ctx: &str) -> String {
    format!(
        "match {access} {{ Attribute::Derived => None, other => Some(({})?) }}",
        scalar_fallible(ir, k, "other", ctx)
    )
}

/// Placeholder value for a ref field (patched in pass 2).
fn ref_placeholder(ir: &ModelIr, k: &Kind, optional: bool) -> String {
    let inner = match k {
        Kind::Ref(t) => {
            let re = &ir.ref_enums[t];
            // pick any arm for the placeholder
            if let Some((variant, target)) = re.simple_arms.first() {
                format!("{}::{}({}Id(usize::MAX))", re.rust, variant, target)
            } else if re.has_complex {
                format!("{}::Complex(ComplexUnitId(usize::MAX))", re.rust)
            } else if let Some((variant, _, _)) = re.aggregate.first() {
                // aggregate-only select (no single arm): empty-vec placeholder.
                format!("{}::{}(Vec::new())", re.rust, variant)
            } else if let Some((variant, enum_rust, _)) = re.enum_arms.first() {
                // enum-only select (no single arm): first enum member placeholder.
                let member = ir
                    .enums
                    .values()
                    .find(|e| &e.rust == enum_rust)
                    .and_then(|e| e.members.first())
                    .map(|(_, v)| v.clone())
                    .expect("enum arm has members");
                format!("{}::{}({}::{})", re.rust, variant, enum_rust, member)
            } else if let Some((variant, sk, _wire)) = re.scalar_arms.first() {
                // scalar-only select (no entity arm): default-value placeholder.
                let dflt = match sk {
                    Kind::Real => "0.0",
                    Kind::Str => "String::new()",
                    _ => unreachable!("unsupported scalar arm kind"),
                };
                format!("{}::{}({dflt})", re.rust, variant)
            } else {
                // empty ref-enum (all targets excluded): referrer always escapes.
                format!("{}::Unresolved", re.rust)
            }
        }
        Kind::Vec(_) => "Vec::new()".to_string(),
        _ => unreachable!(),
    };
    if optional {
        // Option<Ref> or Option<Vec<Ref>>: None placeholder; pass 2 sets Some.
        "None".to_string()
    } else {
        inner
    }
}

/// Read a scalar/enum/measure/vec field value from a `&Attribute` access expr.
/// `access` evaluates to `&Attribute`; the result yields the field value,
/// propagating Err via `?` to the enclosing `Result`-returning build fn.
fn bind_scalar(ir: &ModelIr, k: &Kind, optional: bool, access: &str, ctx: &str) -> String {
    if optional {
        // OPTIONAL: `$` => None; else read the present attribute.
        format!(
            "match {access} {{ Attribute::Unset => None, other => Some(({})?) }}",
            scalar_fallible(ir, k, "other", ctx)
        )
    } else {
        format!("({})?", scalar_fallible(ir, k, access, ctx))
    }
}

/// A `Result<T, String>` expression reading scalar kind `k` from `a` (a
/// `&Attribute` expr). Used both at field level (caller adds `?`) and as a Vec
/// element (collected into `Result<Vec<_>, String>`). `ctx` = "<ENTITY>.<field>".
fn scalar_fallible(ir: &ModelIr, k: &Kind, a: &str, ctx: &str) -> String {
    match k {
        Kind::Real => format!("as_real({a}, {ctx:?})"),
        Kind::Int => format!("as_int({a}, {ctx:?})"),
        Kind::Str | Kind::Binary => format!("as_str({a}, {ctx:?})"),
        Kind::Bool => {
            format!("Ok::<bool, String>(matches!({a}, Attribute::Enum(s) if s == \"T\"))")
        }
        Kind::Logical => format!("as_logical({a}, {ctx:?})"),
        Kind::MeasureSelect(_) => format!("read_measure_value({a}, {ctx:?})"),
        Kind::StringSelect(_) => format!("read_string_select({a}, {ctx:?})"),
        Kind::IntSelect(_) => format!("read_int_measure_value({a}, {ctx:?})"),
        Kind::Enum(name) => {
            let ty = &ir.enums[name].rust;
            format!(
                "match {a} {{ Attribute::Enum(s) => {ty}::parse(s).ok_or_else(|| format!(\"{ctx}: bad enum {{s:?}}\")), o => Err(format!(\"{ctx}: expected enum, got {{o:?}}\")) }}"
            )
        }
        Kind::Vec(inner) => {
            let elem = scalar_fallible(ir, inner, "e", ctx);
            format!(
                "match {a} {{ Attribute::List(l) => l.iter().map(|e| {elem}).collect::<Result<Vec<_>, String>>(), o => Err(format!(\"{ctx}: expected list, got {{o:?}}\")) }}"
            )
        }
        Kind::Ref(_) => unreachable!(),
    }
}

/// pass2: resolve the ref fields of a simple entity (fallible).
fn emit_resolve(s: &mut String, ir: &ModelIr, se: &SimpleEnt) {
    let af = arena_field(&se.rust);
    writeln!(
        s,
        "fn resolve_{af}(model: &mut StepModel, aid: {}Id, attrs: &[Attribute], idmap: &BTreeMap<u64, AnyId>) -> Result<(), String> {{",
        se.rust
    )
    .unwrap();
    let mut idx = 0usize;
    for (id, f) in idents(&se.fields) {
        if f.derived {
            idx += 1;
            continue;
        }
        if has_ref(&f.kind) {
            let ctx = format!("{}.{}", se.name, id);
            // `.get(idx).ok_or(..)?` guards arity for ref slots too (a short
            // entity missing only a ref slot passes pass1, would panic here).
            let access = format!("req(attrs, {idx}, {ctx:?})?");
            let expr = resolve_ref_expr(ir, &f.kind, f.optional, f.derivable, &access, &ctx);
            writeln!(s, "    let {id}_v = {expr};").unwrap();
        }
        idx += 1;
    }
    writeln!(s, "    let it = &mut model.{af}.items[aid.0];").unwrap();
    for (id, f) in idents(&se.fields) {
        if f.derived || !has_ref(&f.kind) {
            continue;
        }
        writeln!(s, "    it.{id} = {id}_v;").unwrap();
    }
    s.push_str("    Ok(())\n}\n\n");
}

/// A `Result<{RefEnum}, String>` expression resolving one ref from `aref` (a
/// `&Attribute`). Discriminates a named enum/aggregate/scalar select member
/// (Typed literal `WIRE(.TOKEN.)` / `WIRE((#a,#b))` / `WIRE(v)`) from a bare
/// entity `#ref`. Wrapped in an IIFE so its internal `?` are contained, making it
/// usable both at field level (caller adds `?`) and as a Vec element (collected).
fn resolve_ref_one(re: &RefEnum, aref: &str, ctx: &str) -> String {
    let single = format!(
        "{}::from_any(*idmap.get(&as_ref_id({aref}, {ctx:?})?).ok_or_else(|| format!(\"{ctx}: dangling ref\"))?).map_err(|e| format!(\"{ctx}: {{e}}\"))?",
        re.rust
    );
    let mut arms: Vec<String> = Vec::new();
    for (ev, enum_rust, wire) in &re.enum_arms {
        arms.push(format!(
            "Attribute::Typed {{ type_name, value }} if type_name == \"{wire}\" => {}::{}(match value.as_ref() {{ Attribute::Enum(s) => {}::parse(s).ok_or_else(|| format!(\"{ctx}: bad enum {wire} {{s:?}}\"))?, o => return Err(format!(\"{ctx}: enum {wire}: {{o:?}}\")) }}),",
            re.rust, ev, enum_rust
        ));
    }
    for (agg_variant, elt_ref, wire) in &re.aggregate {
        arms.push(format!(
            "Attribute::Typed {{ type_name, value }} if type_name == \"{wire}\" => {}::{}(match value.as_ref() {{ Attribute::List(l) => l.iter().map(|e| {}::from_any(*idmap.get(&as_ref_id(e, {ctx:?})?).ok_or_else(|| format!(\"{ctx}: dangling ref\"))?)).collect::<Result<Vec<_>, String>>()?, o => return Err(format!(\"{ctx}: agg list {wire}: {{o:?}}\")) }}),",
            re.rust, agg_variant, elt_ref
        ));
    }
    // Scalar arms: the standard wire form is the Typed literal `WIRE(value)`. A
    // non-standard bare scalar is rewritten to typed by normalize before read, so
    // a bare scalar reaching here falls through to `_ => single` (Err, surfaced).
    for (sv, sk, wire) in &re.scalar_arms {
        let (reader, accessor) = match sk {
            Kind::Real => ("read_measure_value", ".as_f64()"),
            Kind::Str => ("read_string_select", ""),
            _ => unreachable!("unsupported scalar arm kind"),
        };
        arms.push(format!(
            "Attribute::Typed {{ type_name, .. }} if type_name == \"{wire}\" => {}::{}({reader}({aref}, {ctx:?})?.value{accessor}),",
            re.rust, sv
        ));
    }
    let body = if arms.is_empty() {
        single
    } else {
        format!("match {aref} {{ {} _ => {single} }}", arms.join(" "))
    };
    format!("(|| -> Result<{}, String> {{ Ok({body}) }})()", re.rust)
}

/// A field-value expression (propagating Err via `?`) resolving a ref / Vec<ref>
/// field. `access` evaluates to `&Attribute`, bound once to a local `a`.
fn resolve_ref_expr(
    ir: &ModelIr,
    k: &Kind,
    optional: bool,
    derivable: bool,
    access: &str,
    ctx: &str,
) -> String {
    let body = match k {
        Kind::Ref(t) => resolve_ref_one(&ir.ref_enums[t], "a", ctx),
        Kind::Vec(inner) => resolve_ref_vec(ir, inner, "a", ctx),
        _ => unreachable!(),
    };
    if derivable {
        format!(
            "{{ let a = {access}; match a {{ Attribute::Derived => None, _ => Some(({body})?) }} }}"
        )
    } else if optional {
        format!(
            "{{ let a = {access}; match a {{ Attribute::Unset => None, _ => Some(({body})?) }} }}"
        )
    } else {
        format!("{{ let a = {access}; ({body})? }}")
    }
}

/// A `Result<Vec<...>, String>` expression resolving a (possibly nested)
/// `Vec<...Ref>` from `a` (a `&Attribute`).
fn resolve_ref_vec(ir: &ModelIr, inner: &Kind, a: &str, ctx: &str) -> String {
    let elem = match inner {
        // `e` is already `&Attribute` (from l.iter()).
        Kind::Ref(t) => resolve_ref_one(&ir.ref_enums[t], "e", ctx),
        Kind::Vec(i2) => resolve_ref_vec(ir, i2, "e", ctx),
        _ => unreachable!("non-ref nested vec in ref resolve"),
    };
    format!(
        "match {a} {{ Attribute::List(l) => l.iter().map(|e| {elem}).collect::<Result<Vec<_>, String>>(), o => Err(format!(\"{ctx}: expected ref list, got {{o:?}}\")) }}"
    )
}

/// Complex part-bag read (norefs pass1 + resolve_complex pass2), both fallible.
fn emit_complex_read(s: &mut String, ir: &ModelIr) {
    // pass1: bind non-ref part attrs
    s.push_str(
        "fn read_complex_parts_norefs(parts: &[RawEntityPart]) -> Result<Vec<UnitPart>, String> {\n",
    );
    s.push_str(
        "    parts.iter().map(|p| -> Result<UnitPart, String> { Ok(match p.name.as_str() {\n",
    );
    for p in &ir.parts {
        let kept: Vec<_> = idents(&p.fields).into_iter().collect();
        let nonderived: Vec<_> = kept.iter().filter(|(_, f)| !f.derived).collect();
        if nonderived.is_empty() {
            writeln!(s, "        \"{}\" => UnitPart::{},", p.name, p.rust).unwrap();
            continue;
        }
        write!(s, "        \"{}\" => UnitPart::{} {{ ", p.name, p.rust).unwrap();
        let mut idx = 0usize;
        for (id, f) in &kept {
            if f.derived {
                idx += 1;
                continue;
            }
            let expr = if has_ref(&f.kind) {
                ref_placeholder(ir, &f.kind, f.optional || f.derivable)
            } else {
                let ctx = format!("{}.{}", p.name, id);
                let access = format!("req(&p.attributes, {idx}, {ctx:?})?");
                if f.derivable {
                    bind_derivable_scalar(ir, &f.kind, &access, &ctx)
                } else {
                    bind_scalar(ir, &f.kind, f.optional, &access, &ctx)
                }
            };
            write!(s, "{id}: {expr}, ").unwrap();
            idx += 1;
        }
        s.push_str("},\n");
    }
    s.push_str(
        "        other => return Err(format!(\"unknown complex part: {other}\")),\n    }) }).collect::<Result<Vec<_>, String>>()\n}\n\n",
    );

    // pass2: patch ref part attrs
    s.push_str("fn resolve_complex(model: &mut StepModel, aid: ComplexUnitId, parts: &[RawEntityPart], idmap: &BTreeMap<u64, AnyId>) -> Result<(), String> {\n");
    s.push_str("    let bag = &mut model.complex_units.items[aid.0];\n");
    s.push_str("    for (slot, p) in bag.parts.iter_mut().zip(parts.iter()) {\n");
    s.push_str("        match slot {\n");
    for p in &ir.parts {
        let kept: Vec<_> = idents(&p.fields).into_iter().collect();
        let refkept: Vec<_> = kept
            .iter()
            .enumerate()
            .filter(|(_, (_, f))| !f.derived && has_ref(&f.kind))
            .collect();
        if refkept.is_empty() {
            continue;
        }
        // need positional indices into p.attributes (counting derived too)
        let binding: Vec<String> = kept
            .iter()
            .filter(|(_, f)| !f.derived && has_ref(&f.kind))
            .map(|(id, _)| id.clone())
            .collect();
        writeln!(
            s,
            "            UnitPart::{} {{ {}, .. }} => {{",
            p.rust,
            binding.join(", ")
        )
        .unwrap();
        let mut idx = 0usize;
        for (id, f) in &kept {
            if f.derived {
                idx += 1;
                continue;
            }
            if has_ref(&f.kind) {
                let ctx = format!("{}.{}", p.name, id);
                let access = format!("req(&p.attributes, {idx}, {ctx:?})?");
                let expr = resolve_ref_expr(ir, &f.kind, f.optional, f.derivable, &access, &ctx);
                writeln!(s, "                *{id} = {expr};").unwrap();
            }
            idx += 1;
        }
        s.push_str("            }\n");
    }
    // Catch-all for parts without ref attrs (and the no-arm case): always needed.
    s.push_str("            _ => {}\n");
    s.push_str("        }\n    }\n    Ok(())\n}\n");
}

// ===========================================================================
// write.rs — topo write.
// ===========================================================================

pub fn emit_write(ir: &ModelIr) -> String {
    let mut s = String::from(HEADER);
    s.push_str("use super::model::*;\n\n");

    // real formatter (STEP decimal-point form).
    s.push_str(
        r#"fn real(v: f64) -> String {
    // Normalize signed zero to "0." (matches step-io writer/lexical.rs; -0.0 and
    // +0.0 are the same value/point). The round-trip gate canonicalizes signed
    // zero in merkle (`(r+0.0).to_bits()`), so this is NORM, not LOSS.
    if v == 0.0 { return "0.".to_string(); }
    if v == v.trunc() && v.is_finite() && v.abs() < 1e15 { return format!("{}.", v as i64); }
    let s = format!("{v:E}");
    if let Some(epos) = s.find('E') {
        let (mant, exp) = s.split_at(epos);
        let mant = if mant.contains('.') { mant.to_string() } else { format!("{mant}.") };
        format!("{mant}{exp}")
    } else { s }
}
fn measure(m: &MeasureValue) -> String {
    let v = match &m.value { MeasureScalar::Int(i) => format!("{i}"), MeasureScalar::Real(r) => real(*r) };
    match &m.type_name { Some(t) => format!("{t}({v})"), None => v }
}
fn int_measure(m: &IntMeasureValue) -> String {
    match &m.type_name { Some(t) => format!("{t}({})", m.value), None => format!("{}", m.value) }
}
fn string_select(m: &StringSelectValue) -> String {
    match &m.type_name { Some(t) => format!("{t}({})", step_str(&m.value)), None => step_str(&m.value) }
}
/// Part 21 string literal: single-quoted, inner `'` doubled to `''` (matches
/// step-io `writer/lexical.rs::format_string`). Non-ASCII passes through raw.
fn step_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() { if ch == '\'' { out.push('\''); } out.push(ch); }
    out.push('\'');
    out
}

"#,
    );

    // Writer struct.
    s.push_str(
        "pub struct Writer<'a> {\n    model: &'a StepModel,\n    next: u64,\n    out: String,\n",
    );
    for se in &ir.simples {
        writeln!(s, "    {}: Vec<Option<u64>>,", ids_field(&se.rust)).unwrap();
    }
    if ir.has_part_bag {
        s.push_str("    complex_ids: Vec<Option<u64>>,\n");
    }
    s.push_str("}\n\n");

    // new()
    s.push_str("impl<'a> Writer<'a> {\n    pub fn new(model: &'a StepModel) -> Self {\n        Writer {\n            model, next: 1, out: String::new(),\n");
    for se in &ir.simples {
        writeln!(
            s,
            "            {}: vec![None; model.{}.items.len()],",
            ids_field(&se.rust),
            arena_field(&se.rust)
        )
        .unwrap();
    }
    if ir.has_part_bag {
        s.push_str("            complex_ids: vec![None; model.complex_units.items.len()],\n");
    }
    s.push_str("        }\n    }\n\n");
    s.push_str("    fn fresh(&mut self) -> u64 { let n = self.next; self.next += 1; n }\n\n");

    // AnyId-keyed step_id get/set, reusing the per-arena `_ids` caches.
    s.push_str("    fn get_id(&self, any: AnyId) -> Option<u64> { match any {\n");
    for se in &ir.simples {
        writeln!(
            s,
            "        AnyId::{}(i) => self.{}[i.0],",
            se.rust,
            ids_field(&se.rust)
        )
        .unwrap();
    }
    if ir.has_part_bag {
        s.push_str("        AnyId::ComplexUnit(i) => self.complex_ids[i.0],\n");
    }
    s.push_str("    } }\n\n");
    s.push_str("    fn set_id(&mut self, any: AnyId, n: u64) { match any {\n");
    for se in &ir.simples {
        writeln!(
            s,
            "        AnyId::{}(i) => self.{}[i.0] = Some(n),",
            se.rust,
            ids_field(&se.rust)
        )
        .unwrap();
    }
    if ir.has_part_bag {
        s.push_str("        AnyId::ComplexUnit(i) => self.complex_ids[i.0] = Some(n),\n");
    }
    s.push_str("    } }\n\n");

    // id_of_<refenum> (ref-enum -> already-assigned step_id) + deps_<refenum>
    // (ref-enum -> AnyId deps). Aggregate arms hold a Vec of element refs.
    let mut refs: Vec<_> = ir.ref_enums.values().collect();
    refs.sort_by(|a, b| a.rust.cmp(&b.rust));
    for re in &refs {
        emit_ref_id_of(&mut s, re);
        emit_ref_deps(&mut s, re);
    }

    // deps_of / render_one (per simple + complex).
    emit_deps_of(&mut s, ir);
    emit_render_one(&mut s, ir);

    // emit_all: iterative 2-pass (pass1 = post-order id assignment via explicit
    // stack with self-edge skip; pass2 = render in id order). No recursion.
    emit_all_iter(&mut s, ir);

    // wrap_step
    s.push_str(
        "pub fn wrap_step(data_body: &str) -> String {\n    format!(\n        \"ISO-10303-21;\\nHEADER;\\nFILE_DESCRIPTION((''),'2;1');\\n\\\n         FILE_NAME('','',(''),(''),'','','');\\n\\\n         FILE_SCHEMA(('AUTOMOTIVE_DESIGN'));\\nENDSEC;\\nDATA;\\n{data_body}ENDSEC;\\n\\\n         END-ISO-10303-21;\\n\"\n    )\n}\n",
    );

    s
}

fn ids_field(rust: &str) -> String {
    format!("{}_ids", arena_field(rust).trim_end_matches('s'))
}

/// Collect the AnyId deps of a single attribute into `out` (pass-1 numbering).
/// Returns None when the attr holds no entity ref (scalar/enum/measure). When
/// `by_ref` the accessor is already a reference (a complex part binder); else it
/// is a field place needing `&`.
fn collect_deps(
    ir: &ModelIr,
    k: &Kind,
    optional: bool,
    access: &str,
    by_ref: bool,
) -> Option<String> {
    let amp = if by_ref { "" } else { "&" };
    match k {
        Kind::Ref(t) => {
            let dm = ref_method(&ir.ref_enums[t].rust);
            Some(if optional {
                format!("if let Some(r) = {amp}{access} {{ Self::deps_{dm}(r, out); }}")
            } else {
                format!("Self::deps_{dm}({amp}{access}, out);")
            })
        }
        Kind::Vec(inner) => {
            let elem = collect_deps_elem(ir, inner)?;
            Some(if optional {
                format!("if let Some(v) = {amp}{access} {{ for e in v {{ {elem} }} }}")
            } else {
                format!("for e in {amp}{access} {{ {elem} }}")
            })
        }
        _ => None,
    }
}

/// Collect AnyId deps from a Vec element bound to `e`. None if no ref inside.
fn collect_deps_elem(ir: &ModelIr, k: &Kind) -> Option<String> {
    match k {
        Kind::Ref(t) => {
            let dm = ref_method(&ir.ref_enums[t].rust);
            Some(format!("Self::deps_{dm}(e, out);"))
        }
        Kind::Vec(inner) => {
            let inner = collect_deps_elem(ir, inner)?;
            Some(format!("for e in e {{ {inner} }}"))
        }
        _ => None,
    }
}

/// Emit `deps_of(any, out)`: push the AnyId deps of an entity (simple or complex
/// part-bag). Self-edges are filtered by the driver, not here.
fn emit_deps_of(s: &mut String, ir: &ModelIr) {
    s.push_str("    fn deps_of(&self, any: AnyId, out: &mut Vec<AnyId>) { match any {\n");
    for se in &ir.simples {
        let af = arena_field(&se.rust);
        let kept = idents(&se.fields);
        let mut body = String::new();
        for (id, f) in &kept {
            if f.derived {
                continue;
            }
            if let Some(stmt) = collect_deps(
                ir,
                &f.kind,
                f.optional || f.derivable,
                &format!("it.{id}"),
                false,
            ) {
                body.push_str(&stmt);
                body.push(' ');
            }
        }
        if body.is_empty() {
            writeln!(s, "        AnyId::{}(_) => {{}},", se.rust).unwrap();
        } else {
            writeln!(
                s,
                "        AnyId::{}(id) => {{ let it = self.model.{}.get(id.0); {} }},",
                se.rust, af, body
            )
            .unwrap();
        }
    }
    if ir.has_part_bag {
        s.push_str(
            "        AnyId::ComplexUnit(id) => { let cu = self.model.complex_units.get(id.0); for part in &cu.parts { match part {\n",
        );
        for p in &ir.parts {
            let kept = idents(&p.fields);
            let mut binders: Vec<String> = Vec::new();
            let mut stmts = String::new();
            for (id, f) in &kept {
                if f.derived {
                    continue;
                }
                if let Some(stmt) = collect_deps(ir, &f.kind, f.optional || f.derivable, id, true) {
                    binders.push(id.clone());
                    stmts.push_str(&stmt);
                    stmts.push(' ');
                }
            }
            if stmts.is_empty() {
                continue;
            }
            writeln!(
                s,
                "            UnitPart::{} {{ {}, .. }} => {{ {} }},",
                p.rust,
                binders.join(", "),
                stmts
            )
            .unwrap();
        }
        s.push_str("            _ => {}\n        } } },\n");
    }
    s.push_str("    } }\n\n");
}

/// Emit `render_one(any) -> String`: render one entity line, resolving refs by
/// id-lookup (no recursion; all ids pre-assigned in pass 1).
fn emit_render_one(s: &mut String, ir: &ModelIr) {
    s.push_str("    fn render_one(&self, any: AnyId) -> String { match any {\n");
    for se in &ir.simples {
        let af = arena_field(&se.rust);
        let kept = idents(&se.fields);
        let uses_it = kept.iter().any(|(_, f)| !f.derived);
        let mut parts: Vec<String> = Vec::new();
        for (id, f) in &kept {
            if f.derived {
                parts.push("\"*\".to_string()".to_string());
                continue;
            }
            parts.push(render_attr(
                ir,
                &f.kind,
                f.optional,
                f.derivable,
                &format!("it.{id}"),
            ));
        }
        let binder = if uses_it { "id" } else { "_" };
        let it_bind = if uses_it {
            format!("let it = self.model.{af}.get(id.0); ")
        } else {
            String::new()
        };
        writeln!(
            s,
            "        AnyId::{}({binder}) => {{ {it_bind}let n = self.get_id(any).expect(\"id assigned\"); let attrs: Vec<String> = vec![{}]; format!(\"#{{n}} = {}({{}});\\n\", attrs.join(\",\")) }},",
            se.rust,
            parts.join(", "),
            se.name
        )
        .unwrap();
    }
    if ir.has_part_bag {
        s.push_str(
            "        AnyId::ComplexUnit(id) => { let cu = self.model.complex_units.get(id.0); let n = self.get_id(any).expect(\"id assigned\"); let mut part_txt: Vec<String> = Vec::with_capacity(cu.parts.len()); for part in &cu.parts { part_txt.push(match part {\n",
        );
        for p in &ir.parts {
            let kept = idents(&p.fields);
            let nonderived: Vec<_> = kept.iter().filter(|(_, f)| !f.derived).collect();
            if kept.is_empty() {
                writeln!(
                    s,
                    "                UnitPart::{} => \"{}()\".to_string(),",
                    p.rust, p.name
                )
                .unwrap();
                continue;
            }
            let binders: Vec<String> = nonderived.iter().map(|(id, _)| id.clone()).collect();
            write!(
                s,
                "                UnitPart::{} {{ {} }} => {{",
                p.rust,
                if binders.is_empty() {
                    ".. ".to_string()
                } else {
                    format!("{}, ..", binders.join(", "))
                }
            )
            .unwrap();
            let mut rendered: Vec<String> = Vec::new();
            for (id, f) in &kept {
                if f.derived {
                    rendered.push("\"*\".to_string()".to_string());
                } else {
                    rendered.push(render_part_attr(ir, &f.kind, f.optional, f.derivable, id));
                }
            }
            write!(s, " let a: Vec<String> = vec![{}];", rendered.join(", ")).unwrap();
            writeln!(s, " format!(\"{}({{}})\", a.join(\",\")) }},", p.name).unwrap();
        }
        s.push_str(
            "            });\n        } format!(\"#{n} = ( {} );\\n\", part_txt.join(\" \")) },\n",
        );
    }
    s.push_str("    } }\n\n");
}

/// Render one attribute to a `String` expression. `access` is the field
/// accessor. An optional field renders `None` as `$`; a derivable field renders
/// `None` as `*`.
fn render_attr(ir: &ModelIr, k: &Kind, optional: bool, derivable: bool, access: &str) -> String {
    let wrapped = optional || derivable;
    let none_tok = if derivable { "*" } else { "$" };
    match k {
        Kind::Ref(t) => {
            let re = &ir.ref_enums[t];
            if wrapped {
                format!(
                    "match &{access} {{ Some(r) => {}, None => \"{none_tok}\".to_string() }}",
                    render_ref_value(re, "r")
                )
            } else {
                render_ref_value(re, &format!("&{access}"))
            }
        }
        Kind::Vec(inner) => {
            let elem = render_vec_elem(ir, inner);
            let body = format!(
                "format!(\"({{}})\", {access}.iter().map(|e| {elem}).collect::<Vec<_>>().join(\",\"))"
            );
            if wrapped {
                format!(
                    "match &{access} {{ Some(v) => format!(\"({{}})\", v.iter().map(|e| {elem}).collect::<Vec<_>>().join(\",\")), None => \"{none_tok}\".to_string() }}"
                )
            } else {
                body
            }
        }
        scalar => {
            let body = render_scalar(ir, scalar, access);
            if wrapped {
                format!(
                    "match &{access} {{ Some(x) => {}, None => \"{none_tok}\".to_string() }}",
                    render_scalar_ref(ir, scalar, "x")
                )
            } else {
                body
            }
        }
    }
}

/// Render a ref-enum value (given by a `&{re.rust}` expression `v`) to a String
/// expr: `#n` for a single arm; `(#a,#b)` for an aggregate arm. ref-enums are
/// non-Copy, so the dispatch clones the value it hands to `emit_*`.
fn render_ref_value(re: &RefEnum, v: &str) -> String {
    let m = ref_method(&re.rust);
    let mut arms: Vec<String> = Vec::new();
    for (aggv, elt_ref, wire) in &re.aggregate {
        let em = ref_method(elt_ref);
        // named aggregate -> Typed literal `WIRE((#a,#b))`.
        arms.push(format!(
            "{rust}::{aggv}(vs) => format!(\"{wire}(({{}}))\", vs.iter().map(|e| format!(\"#{{}}\", self.id_of_{em}(e))).collect::<Vec<_>>().join(\",\")),",
            rust = re.rust
        ));
    }
    for (ev, _, wire) in &re.enum_arms {
        // named enum select member -> Typed literal `WIRE(.TOKEN.)` (token() has dots).
        arms.push(format!(
            "{rust}::{ev}(e) => format!(\"{wire}({{}})\", e.token()),",
            rust = re.rust
        ));
    }
    for (sv, sk, wire) in &re.scalar_arms {
        // named scalar select member -> always the standard Typed literal
        // `WIRE(value)` (a bare-on-read value is normalized to this on write).
        let val = match sk {
            Kind::Real => "real(*x)",
            Kind::Str => "step_str(x)",
            _ => unreachable!("unsupported scalar arm kind"),
        };
        arms.push(format!(
            "{rust}::{sv}(x) => format!(\"{wire}({{}})\", {val}),",
            rust = re.rust
        ));
    }
    if arms.is_empty() {
        format!("format!(\"#{{}}\", self.id_of_{m}({v}))")
    } else {
        format!(
            "match {v} {{ {} other => format!(\"#{{}}\", self.id_of_{m}(other)) }}",
            arms.join(" ")
        )
    }
}

fn render_scalar(_ir: &ModelIr, k: &Kind, access: &str) -> String {
    match k {
        Kind::Real => format!("real({access})"),
        Kind::Int => format!("format!(\"{{}}\", {access})"),
        Kind::Str => format!("step_str(&{access})"),
        Kind::Bool => format!("(if {access} {{ \".T.\" }} else {{ \".F.\" }}).to_string()"),
        Kind::Logical => format!("{access}.token().to_string()"),
        Kind::Binary => format!("format!(\"'{{}}'\", {access})"),
        Kind::MeasureSelect(_) => format!("measure(&{access})"),
        Kind::StringSelect(_) => format!("string_select(&{access})"),
        Kind::IntSelect(_) => format!("int_measure(&{access})"),
        Kind::Enum(_) => format!("{access}.token().to_string()"),
        _ => unreachable!(),
    }
}

/// Same as render_scalar but for a `&T` binding (optional Some case).
fn render_scalar_ref(_ir: &ModelIr, k: &Kind, access: &str) -> String {
    match k {
        Kind::Real => format!("real(*{access})"),
        Kind::Int => format!("format!(\"{{}}\", {access})"),
        Kind::Str => format!("step_str({access})"),
        Kind::Bool => format!("(if *{access} {{ \".T.\" }} else {{ \".F.\" }}).to_string()"),
        Kind::Logical => format!("{access}.token().to_string()"),
        Kind::Binary => format!("format!(\"'{{}}'\", {access})"),
        Kind::MeasureSelect(_) => format!("measure({access})"),
        Kind::StringSelect(_) => format!("string_select({access})"),
        Kind::IntSelect(_) => format!("int_measure({access})"),
        Kind::Enum(_) => format!("{access}.token().to_string()"),
        _ => unreachable!(),
    }
}

fn render_vec_elem(ir: &ModelIr, inner: &Kind) -> String {
    match inner {
        Kind::Ref(t) => {
            let re = &ir.ref_enums[t];
            render_ref_value(re, "e")
        }
        Kind::Vec(i2) => {
            // nested list (e.g. control_points_list grid). Rebind inner elem to `e`.
            let inner_elem = render_vec_elem(ir, i2);
            format!(
                "{{ let row: Vec<String> = e.iter().map(|e| {inner_elem}).collect(); format!(\"({{}})\", row.join(\",\")) }}"
            )
        }
        Kind::Real => "real(*e)".to_string(),
        Kind::Int => "format!(\"{e}\")".to_string(),
        Kind::Str => "step_str(e)".to_string(),
        Kind::Logical => "e.token().to_string()".to_string(),
        Kind::Enum(_) => "e.token().to_string()".to_string(),
        Kind::MeasureSelect(_) => "measure(e)".to_string(),
        Kind::StringSelect(_) => "string_select(e)".to_string(),
        Kind::IntSelect(_) => "int_measure(e)".to_string(),
        _ => "real(*e)".to_string(),
    }
}

fn ref_method(re_rust: &str) -> String {
    // CurveRef -> ref_curve  (method name for the ref dispatch)
    let base = re_rust.trim_end_matches("Ref");
    let mut out = String::new();
    for (i, c) in base.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    format!("ref_{out}")
}

/// Emit `id_of_<ref>`: ref-enum -> the step_id already assigned to its target
/// (lookup in the arena `_ids` caches). The iterative replacement for the old
/// recursive emit dispatch. Aggregate/enum/scalar arms are rendered inline by
/// render_ref_value, so they never reach single-id lookup.
fn emit_ref_id_of(s: &mut String, re: &RefEnum) {
    writeln!(
        s,
        "    fn id_of_{}(&self, r: &{}) -> u64 {{ match r {{",
        ref_method(&re.rust),
        re.rust
    )
    .unwrap();
    for (variant, target) in &re.simple_arms {
        writeln!(
            s,
            "        {}::{variant}(i) => self.{}[i.0].expect(\"dep id assigned\"),",
            re.rust,
            ids_field(target)
        )
        .unwrap();
    }
    if re.has_complex {
        writeln!(
            s,
            "        {}::Complex(i) => self.complex_ids[i.0].expect(\"dep id assigned\"),",
            re.rust
        )
        .unwrap();
    }
    for (variant, _, _) in &re.aggregate {
        writeln!(
            s,
            "        {}::{variant}(_) => panic!(\"aggregate via single id_of\"),",
            re.rust
        )
        .unwrap();
    }
    for (variant, _, _) in &re.enum_arms {
        writeln!(
            s,
            "        {}::{variant}(_) => panic!(\"enum via single id_of\"),",
            re.rust
        )
        .unwrap();
    }
    for (variant, _, _) in &re.scalar_arms {
        writeln!(
            s,
            "        {}::{variant}(_) => panic!(\"scalar via single id_of\"),",
            re.rust
        )
        .unwrap();
    }
    if re.simple_arms.is_empty()
        && re.aggregate.is_empty()
        && re.enum_arms.is_empty()
        && re.scalar_arms.is_empty()
        && !re.has_complex
    {
        writeln!(
            s,
            "        {}::Unresolved => panic!(\"id_of unresolved\"),",
            re.rust
        )
        .unwrap();
    }
    s.push_str("    } }\n\n");
}

/// Emit `deps_<ref>`: ref-enum -> push its AnyId deps (for pass-1 numbering).
/// Aggregate arms recurse into element refs; enum/scalar arms carry no entity dep.
fn emit_ref_deps(s: &mut String, re: &RefEnum) {
    writeln!(
        s,
        "    fn deps_{}(r: &{}, out: &mut Vec<AnyId>) {{ match r {{",
        ref_method(&re.rust),
        re.rust
    )
    .unwrap();
    for (variant, target) in &re.simple_arms {
        writeln!(
            s,
            "        {}::{variant}(i) => out.push(AnyId::{}(*i)),",
            re.rust, target
        )
        .unwrap();
    }
    if re.has_complex {
        writeln!(
            s,
            "        {}::Complex(i) => out.push(AnyId::ComplexUnit(*i)),",
            re.rust
        )
        .unwrap();
    }
    for (variant, elt_ref, _) in &re.aggregate {
        writeln!(
            s,
            "        {}::{variant}(vs) => {{ for e in vs {{ Self::deps_{}(e, out); }} }},",
            re.rust,
            ref_method(elt_ref)
        )
        .unwrap();
    }
    for (variant, _, _) in &re.enum_arms {
        writeln!(s, "        {}::{variant}(_) => {{}},", re.rust).unwrap();
    }
    for (variant, _, _) in &re.scalar_arms {
        writeln!(s, "        {}::{variant}(_) => {{}},", re.rust).unwrap();
    }
    if re.simple_arms.is_empty()
        && re.aggregate.is_empty()
        && re.enum_arms.is_empty()
        && re.scalar_arms.is_empty()
        && !re.has_complex
    {
        writeln!(s, "        {}::Unresolved => {{}},", re.rust).unwrap();
    }
    s.push_str("    } }\n\n");
}

/// Emit `emit_all`: iterative 2-pass topo write. Pass 1 assigns step_ids by an
/// explicit-stack post-order DFS (deps before dependents; self-edges skipped;
/// multi-node cycle back-edges pre-numbered as forward-refs). Pass 2 renders in
/// id order. No recursion -> stack depth is independent of graph depth.
fn emit_all_iter(s: &mut String, ir: &ModelIr) {
    s.push_str("    pub fn emit_all(mut self) -> String {\n");
    s.push_str("        let mut order: Vec<AnyId> = Vec::new();\n");
    s.push_str("        let mut roots: Vec<AnyId> = Vec::new();\n");
    if ir.has_part_bag {
        s.push_str("        for i in 0..self.model.complex_units.items.len() { roots.push(AnyId::ComplexUnit(ComplexUnitId(i))); }\n");
    }
    for se in &ir.simples {
        writeln!(
            s,
            "        for i in 0..self.model.{}.items.len() {{ roots.push(AnyId::{}({}Id(i))); }}",
            arena_field(&se.rust),
            se.rust,
            se.rust
        )
        .unwrap();
    }
    s.push_str(
        r#"        let mut stack: Vec<(AnyId, bool)> = Vec::new();
        let mut on_path: std::collections::HashSet<AnyId> = std::collections::HashSet::new();
        for root in roots {
            if self.get_id(root).is_some() { continue; }
            stack.push((root, false));
            while let Some((any, post)) = stack.pop() {
                if post {
                    on_path.remove(&any);
                    if self.get_id(any).is_none() {
                        let n = self.fresh();
                        self.set_id(any, n);
                        order.push(any);
                    }
                    continue;
                }
                if self.get_id(any).is_some() { continue; }
                if on_path.contains(&any) {
                    // multi-node cycle back-edge: pre-number as a forward-ref.
                    let n = self.fresh();
                    self.set_id(any, n);
                    order.push(any);
                    continue;
                }
                on_path.insert(any);
                stack.push((any, true));
                let mut deps: Vec<AnyId> = Vec::new();
                self.deps_of(any, &mut deps);
                for d in deps.into_iter().rev() {
                    if d == any { continue; }
                    if self.get_id(d).is_some() { continue; }
                    stack.push((d, false));
                }
            }
        }
        for any in &order {
            let line = self.render_one(*any);
            self.out.push_str(&line);
        }
        self.out
    }
}

"#,
    );
}

/// Render a complex part attribute (the binder `id` is a `&T` reference).
fn render_part_attr(ir: &ModelIr, k: &Kind, optional: bool, derivable: bool, id: &str) -> String {
    let wrapped = optional || derivable;
    let none_tok = if derivable { "*" } else { "$" };
    match k {
        Kind::Ref(t) => {
            let re = &ir.ref_enums[t];
            if wrapped {
                format!(
                    "match {id} {{ Some(r) => {}, None => \"{none_tok}\".to_string() }}",
                    render_ref_value(re, "r")
                )
            } else {
                render_ref_value(re, id)
            }
        }
        Kind::Vec(inner) => {
            let elem = render_vec_elem(ir, inner);
            if wrapped {
                format!(
                    "match {id} {{ Some(v) => format!(\"({{}})\", v.iter().map(|e| {elem}).collect::<Vec<_>>().join(\",\")), None => \"{none_tok}\".to_string() }}"
                )
            } else {
                format!(
                    "format!(\"({{}})\", {id}.iter().map(|e| {elem}).collect::<Vec<_>>().join(\",\"))"
                )
            }
        }
        scalar => {
            if wrapped {
                format!(
                    "match {id} {{ Some(x) => {}, None => \"{none_tok}\".to_string() }}",
                    render_scalar_ref(ir, scalar, "x")
                )
            } else {
                render_scalar_ref(ir, scalar, id)
            }
        }
    }
}

// ===========================================================================
// normalize.rs — strict-input normalization (slot-kind general rules).
// Runs on the raw graph BEFORE the strict read: rewrites non-standard values to
// standard (record a NormCase note), or — when not normalizable (required ref =
// `$`) — drops the entity (its referrers cascade-drop via the round-trip subset
// escape filter). The model/read stay strict; nothing here bends them.
// ===========================================================================

/// Top-level slot kind tag for the normalize rule table.
fn sk_variant(k: &Kind) -> &'static str {
    match k {
        Kind::Real => "Real",
        Kind::Int => "Int",
        Kind::Str => "Str",
        Kind::Binary => "Bin",
        Kind::Bool => "Bool",
        Kind::Logical => "Log",
        Kind::Enum(_) => "Enum",
        Kind::Ref(_) => "Ref",
        Kind::Vec(_) => "Vec",
        Kind::MeasureSelect(_) => "Meas",
        // string-select required `$` -> req-str<-$ normalizes to "" (read as bare).
        Kind::StringSelect(_) => "Str",
        // int-select: same Unchanged normalize as measure; integer is preserved
        // by read_int_measure_value / int_measure (no int->real coercion).
        Kind::IntSelect(_) => "Meas",
    }
}

/// The UPPER wire name to normalize a bare scalar member to, for a ref/aggregate
/// slot whose target SELECT has exactly one scalar arm (unambiguous). None
/// otherwise (no scalar arm, or >=2 — a bare literal would be ambiguous).
fn scalar_wire_of(ir: &ModelIr, k: &Kind) -> Option<String> {
    let target = match k {
        Kind::Ref(t) => t,
        Kind::Vec(inner) => match inner.as_ref() {
            Kind::Ref(t) => t,
            _ => return None,
        },
        _ => return None,
    };
    match ir.ref_enums.get(target)?.scalar_arms.as_slice() {
        [(_, _, wire)] => Some(wire.clone()),
        _ => None,
    }
}

/// Emit a `fn {fname}(n: &str) -> &'static [RefSlot]` table: one RefSlot per ref
/// slot (`Ref` / `Vec<Ref>`), carrying the slot index, the admitted target type
/// UPPER names (the ref-enum's simple arms), complex-target flag, and vec flag.
/// Non-ref slots are omitted.
fn emit_ref_slot_table<'a>(
    s: &mut String,
    fname: &str,
    ir: &ModelIr,
    rust_to_name: &std::collections::HashMap<&str, &str>,
    ents: impl Iterator<Item = (&'a String, &'a Vec<Field>)>,
) {
    writeln!(s, "pub fn {fname}(n: &str) -> &'static [RefSlot] {{").unwrap();
    s.push_str("    match n {\n");
    for (name, fields) in ents {
        let slots: Vec<String> = fields
            .iter()
            .enumerate()
            .filter_map(|(idx, f)| {
                let (target, is_vec) = match &f.kind {
                    Kind::Ref(t) => (t.as_str(), false),
                    Kind::Vec(inner) => match inner.as_ref() {
                        Kind::Ref(t) => (t.as_str(), true),
                        _ => return None,
                    },
                    _ => return None,
                };
                let re = ir.ref_enums.get(target)?;
                let allowed: Vec<String> = re
                    .simple_arms
                    .iter()
                    .filter_map(|(_, rust)| rust_to_name.get(rust.as_str()))
                    .map(|n| format!("\"{n}\""))
                    .collect();
                Some(format!(
                    "RefSlot{{idx:{idx},name:\"{}\",allowed:&[{}],complex_ok:{},is_vec:{is_vec}}}",
                    f.name,
                    allowed.join(","),
                    re.has_complex,
                ))
            })
            .collect();
        if !slots.is_empty() {
            writeln!(s, "        \"{}\" => &[{}],", name, slots.join(",")).unwrap();
        }
    }
    s.push_str("        _ => &[],\n    }\n}\n\n");
}

fn emit_slot_table<'a>(
    s: &mut String,
    fname: &str,
    ir: &ModelIr,
    simple: bool,
    ents: impl Iterator<Item = (&'a String, &'a Vec<Field>)>,
) {
    writeln!(s, "fn {fname}(n: &str) -> &'static [Slot] {{").unwrap();
    s.push_str("    match n {\n");
    for (name, fields) in ents {
        let slots: Vec<String> = fields
            .iter()
            .map(|f| {
                let k = sk_variant(&f.kind);
                // A `derivable` field is `*` only in the COMPLEX (part-bag) form,
                // where a deriving sibling is present; in the STANDALONE (simple)
                // form it is an explicit, required value. So in simple_slots a
                // derivable field is required (a non-standard `$` normalizes like
                // any required field, e.g. req-str<-$); in part_slots it stays
                // non-required (the `*` case).
                let req = if simple {
                    !f.optional
                } else {
                    !(f.optional || f.derivable)
                };
                let swire = match scalar_wire_of(ir, &f.kind) {
                    Some(w) => format!("Some(\"{w}\")"),
                    None => "None".to_string(),
                };
                format!(
                    "Slot{{k:Sk::{k},req:{req},der:{},swire:{swire}}}",
                    f.derived
                )
            })
            .collect();
        writeln!(s, "        \"{}\" => &[{}],", name, slots.join(",")).unwrap();
    }
    s.push_str("        _ => &[],\n    }\n}\n\n");
}

pub fn emit_normalize(ir: &ModelIr, crate_path: &str) -> String {
    let mut s = String::from(HEADER);
    s.push_str(&format!(
        "use std::collections::BTreeMap;\nuse {crate_path}::{{Attribute, RawEntity}};\n\n"
    ));
    s.push_str(
        r#"#[derive(Clone, Copy)]
enum Sk { Real, Int, Str, Bin, Bool, Log, Enum, Ref, Vec, Meas }
#[derive(Clone, Copy)]
struct Slot { k: Sk, req: bool, der: bool, swire: Option<&'static str> }

/// Value-level canonical: signed-zero -0.0 -> +0.0, recursively (incl. lists).
fn canon(a: &mut Attribute) {
    match a {
        Attribute::Real(r) => { if *r == 0.0 { *r = 0.0_f64; } }
        Attribute::List(v) => { for e in v.iter_mut() { canon(e); } }
        Attribute::Typed { value, .. } => canon(value),
        _ => {}
    }
}

/// A non-standard bare scalar select member (`5.` / `'x'`) -> the standard Typed
/// literal `WIRE(value)`. Only the single-scalar-arm case (unambiguous wire) is
/// normalized here; entity refs (`#n`) and already-typed values are left alone.
fn wrap_bare_scalar(a: &mut Attribute, wire: &'static str) -> bool {
    match a {
        Attribute::Real(_) | Attribute::Integer(_) | Attribute::String(_) => {
            let inner = std::mem::replace(a, Attribute::Unset);
            *a = Attribute::Typed { type_name: wire.to_string(), value: Box::new(inner) };
            true
        }
        _ => false,
    }
}

/// Result of normalizing one slot value. Unchanged = already standard; Rewrite =
/// fixed to a standard value (kept, "fix"); Drop = non-normalizable (entity removed,
/// "drop"). The fix/drop split feeds the two surface channels (norm vs drops).
enum NormAction { Unchanged, Rewrite(Attribute, &'static str), Drop(&'static str) }

/// Slot-kind general rules (single rule per slot, output is the final standard
/// value). Value rules (int<->real) apply regardless of req; the `$`/`*` rules
/// apply per req/derived.
fn norm_attr(s: Slot, a: &Attribute) -> NormAction {
    if s.der {
        // a derived slot is always `*` on the wire; force it (drops a redundant
        // explicit value or a non-standard `()`/`$`).
        return if matches!(a, Attribute::Derived) { NormAction::Unchanged }
               else { NormAction::Rewrite(Attribute::Derived, "derived->*") };
    }
    match (s.k, a) {
        (Sk::Real, Attribute::Integer(i)) => NormAction::Rewrite(Attribute::Real(*i as f64), "int->real"),
        (Sk::Int, Attribute::Real(r)) if r.fract() == 0.0 => {
            NormAction::Rewrite(Attribute::Integer(*r as i64), "real->int")
        }
        (Sk::Int, Attribute::Real(_)) => NormAction::Drop("int<-fractional-real"),
        (Sk::Str | Sk::Bin, Attribute::Unset) if s.req => {
            NormAction::Rewrite(Attribute::String(String::new()), "req-str<-$")
        }
        (Sk::Vec, Attribute::Unset) if s.req => NormAction::Rewrite(Attribute::List(Vec::new()), "req-vec<-$"),
        (Sk::Ref, Attribute::Unset) if s.req => NormAction::Drop("req-ref<-$"),
        _ => NormAction::Unchanged,
    }
}

/// Normalize one entity's attrs. Rewrites push to `warns` (norm channel); a
/// non-normalizable slot sets `drop_out` to its reason and returns false (the
/// entity is removed — slot-local drop, surfaced on the drops channel).
fn norm_attrs(slots: &[Slot], attrs: &mut Vec<Attribute>, warns: &mut Vec<&'static str>, drop_out: &mut Option<&'static str>) -> bool {
    for (i, a) in attrs.iter_mut().enumerate() {
        canon(a);
        if let Some(s) = slots.get(i).copied() {
            // nested select-scalar normalization: a ref/aggregate slot whose target
            // SELECT has a single scalar arm — rewrite bare members to typed.
            if let Some(wire) = s.swire {
                match s.k {
                    Sk::Vec => {
                        if let Attribute::List(v) = a {
                            for e in v.iter_mut() {
                                if wrap_bare_scalar(e, wire) { warns.push("select-scalar bare->typed"); }
                            }
                        }
                    }
                    Sk::Ref => {
                        if wrap_bare_scalar(a, wire) { warns.push("select-scalar bare->typed"); }
                    }
                    _ => {}
                }
            }
            match norm_attr(s, a) {
                NormAction::Unchanged => {}
                NormAction::Rewrite(na, w) => { *a = na; warns.push(w); }
                NormAction::Drop(w) => { *drop_out = Some(w); return false; }
            }
        }
    }
    true
}

/// Normalize the raw graph in place. Returns the surviving map (non-normalizable
/// entities removed; their referrers cascade-drop later via the drop pass) plus
/// two separate channels: `warns` = rewrite notes (fix, kept), `slot_drops` =
/// `(id, reason)` per entity removed here (surfaced as drops).
pub fn normalize(mut map: BTreeMap<u64, RawEntity>) -> (BTreeMap<u64, RawEntity>, Vec<&'static str>, Vec<(u64, &'static str)>) {
    let mut warns: Vec<&'static str> = Vec::new();
    let mut slot_drops: Vec<(u64, &'static str)> = Vec::new();
    for (&id, ent) in map.iter_mut() {
        let mut drop_reason: Option<&'static str> = None;
        let keep = match ent {
            RawEntity::Simple { name, attributes, .. } => {
                norm_attrs(simple_slots(name), attributes, &mut warns, &mut drop_reason)
            }
            RawEntity::Complex { parts, .. } => {
                let mut ok = true;
                for p in parts.iter_mut() {
                    if !norm_attrs(part_slots(&p.name), &mut p.attributes, &mut warns, &mut drop_reason) {
                        ok = false;
                        break;
                    }
                }
                ok
            }
        };
        if !keep {
            slot_drops.push((id, drop_reason.unwrap_or("slot-local")));
        }
    }
    for (id, _) in &slot_drops {
        map.remove(id);
    }
    (map, warns, slot_drops)
}

"#,
    );
    emit_slot_table(
        &mut s,
        "simple_slots",
        ir,
        true,
        ir.simples.iter().map(|se| (&se.name, &se.fields)),
    );
    emit_slot_table(
        &mut s,
        "part_slots",
        ir,
        false,
        ir.parts.iter().map(|p| (&p.name, &p.fields)),
    );
    s
}
