//! `codegen` generator binary. Reads `schema/early.toml` + `schema/mapping.toml`,
//! computes the units/geometry/topology schema closure, and emits a
//! schema-faithful model + generic 2-pass read + topo write into
//! `codegen/src/generated/`. Run: `cargo run -p codegen --bin codegen`.

mod classify;
mod emit;
mod mapping;
mod model_ir;
mod schema;

use std::collections::BTreeSet;
use std::process::Command;

use classify::Resolver;
use model_ir::{ModelIr, build_closure};
use schema::EarlyToml;

fn main() {
    let root = concat!(env!("CARGO_MANIFEST_DIR"), "/..");
    let schema: EarlyToml = toml::from_str(
        &std::fs::read_to_string(format!("{root}/schema/early.toml")).expect("read early.toml"),
    )
    .expect("parse early.toml");
    let mapping: mapping::Mapping = toml::from_str(
        &std::fs::read_to_string(format!("{root}/schema/mapping.toml")).expect("read mapping.toml"),
    )
    .expect("parse mapping.toml");

    let res = Resolver { schema: &schema };

    // Domain seeds -> single combined closure.
    let mut seeds: Vec<String> = Vec::new();
    for (_dom, list) in &mapping.codegen.domains {
        seeds.extend(list.iter().cloned());
    }
    let closure = build_closure(&schema, &res, &seeds);

    // Complex-part entities (union across domains, intersect closure).
    let mut complex_parts: BTreeSet<String> = BTreeSet::new();
    for (_dom, list) in &mapping.codegen.complex_parts {
        for n in list {
            if closure.contains(n) {
                complex_parts.insert(n.clone());
            }
        }
    }

    // Conditionally-`*` (derivable) attrs from complex cases: a case's
    // `derived = [attr...]` names an attr that is `*` in that case but a value
    // in another (e.g. named_unit.dimensions). Attach each to the part entity
    // that declares it as an own_attr.
    let mut derivable: std::collections::BTreeMap<String, BTreeSet<String>> =
        std::collections::BTreeMap::new();
    for hint in mapping.complex.values() {
        let mut case_derived: Vec<&str> = Vec::new();
        if let Some(cases) = &hint.cases {
            for c in cases.values() {
                for d in &c.derived {
                    case_derived.push(d);
                }
            }
        }
        for d in case_derived {
            for part in &complex_parts {
                if schema.own_attrs(part).iter().any(|a| a.name == d) {
                    derivable
                        .entry(part.clone())
                        .or_default()
                        .insert(d.to_string());
                }
            }
        }
    }

    let ir = ModelIr::build(
        &schema,
        &res,
        &closure,
        &complex_parts,
        &mapping.derived,
        &derivable,
    );

    eprintln!(
        "codegen: closure={} simple={} parts={} ref_enums={} enums={}",
        closure.len(),
        ir.simples.len(),
        ir.parts.len(),
        ir.ref_enums.len(),
        ir.enums.len(),
    );

    let dir = format!("{root}/codegen/src/generated");
    std::fs::create_dir_all(&dir).expect("mkdir generated");
    write_fmt(&format!("{dir}/model.rs"), &emit::emit_model(&ir));
    write_fmt(&format!("{dir}/read.rs"), &emit::emit_read(&ir));
    write_fmt(&format!("{dir}/write.rs"), &emit::emit_write(&ir));
    std::fs::write(
        format!("{dir}/mod.rs"),
        "// @generated by codegen. DO NOT EDIT.\n#![allow(dead_code, clippy::all, clippy::pedantic)]\npub mod model;\npub mod read;\npub mod write;\n",
    )
    .expect("write mod.rs");
    eprintln!("codegen: wrote model/read/write to {dir}");
}

fn write_fmt(path: &str, body: &str) {
    std::fs::write(path, body).expect("write generated file");
    let status = Command::new("rustfmt")
        .args(["--edition", "2024", path])
        .status();
    match status {
        Ok(st) if st.success() => {}
        _ => eprintln!("codegen: rustfmt skipped/failed for {path} (kept raw)"),
    }
}
