//! `codegen` generator binary. Reads `schema/universal.toml` + `schema/mapping.toml`,
//! computes the units/geometry/topology schema closure, and emits a
//! schema-faithful model + generic 2-pass read + topo write into
//! `codegen/src/generated/`. Run: `cargo run -p codegen --bin codegen`.

mod classify;
mod emit;
mod mapping;
mod model_ir;
mod schema;

use std::collections::BTreeSet;
use std::process::Command;

use classify::Resolver;
use model_ir::{ModelIr, build_closure};
use schema::EarlyToml;

fn main() {
    let root = concat!(env!("CARGO_MANIFEST_DIR"), "/..");
    let schema: EarlyToml = toml::from_str(
        &std::fs::read_to_string(format!("{root}/schema/universal.toml"))
            .expect("read universal.toml"),
    )
    .expect("parse universal.toml");
    let mapping: mapping::Mapping = toml::from_str(
        &std::fs::read_to_string(format!("{root}/schema/mapping.toml")).expect("read mapping.toml"),
    )
    .expect("parse mapping.toml");

    let res = Resolver { schema: &schema };

    // Domain seeds -> single combined closure.
    let mut seeds: Vec<String> = Vec::new();
    for list in mapping.codegen.domains.values() {
        seeds.extend(list.iter().cloned());
    }
    let closure = build_closure(&schema, &res, &seeds);

    // Complex-part entities = closure entities flagged is_complex_part in
    // universal.toml (auto-derived from EXPRESS ANDOR; replaces the former hand
    // -written [codegen].complex_parts). complex-only leaves are pulled into the
    // closure via domains seeds (they are not ref-reachable).
    let complex_parts: BTreeSet<String> = closure
        .iter()
        .filter(|n| schema.entity.get(*n).is_some_and(|e| e.is_complex_part))
        .cloned()
        .collect();

    // DERIVE (`*`) markers from universal.toml `derives` (each "super.attr" or
    // "attr"), split into hard vs conditional using `complex_parts`:
    //  - hard `derived`: a non-complex-part (simple-leaf) entity computes the
    //    attr always (e.g. oriented_edge.edge_start) → drop field, render `*`.
    //  - conditional `derivable`: a complex-part supertype P's attr is `*` only
    //    when a deriving sibling part is present (e.g. si_unit derives
    //    SELF\named_unit.dimensions → named_unit.dimensions). Keyed by P.
    let mut derived: std::collections::BTreeMap<String, Vec<String>> =
        std::collections::BTreeMap::new();
    let mut derivable: std::collections::BTreeMap<String, BTreeSet<String>> =
        std::collections::BTreeMap::new();
    for (name, ent) in &schema.entity {
        for d in &ent.derives {
            let (sup, attr) = d
                .rsplit_once('.')
                .map_or((None, d.as_str()), |(s, a)| (Some(s), a));
            // derivable: the SUPER part's attr is `*` only when a deriving
            // sibling part is present (complex form). Keyed by the super part.
            if let Some(s) = sup
                && complex_parts.contains(s)
            {
                derivable
                    .entry(s.to_string())
                    .or_default()
                    .insert(attr.to_string());
            }
            // hard derived: in E's OWN (simple) form the attr is always `*`
            // (E computes it) — applies regardless of E being a complex part too
            // (a complex part may also appear standalone). Only affects E's
            // flattened simple struct; E's part-bag variant uses own_attrs (the
            // inherited derived attr isn't an own attr, so it's a no-op there).
            derived
                .entry(name.clone())
                .or_default()
                .push(attr.to_string());
        }
    }

    let ir = ModelIr::build(
        &schema,
        &res,
        &closure,
        &complex_parts,
        &derived,
        &derivable,
    );

    eprintln!(
        "codegen: closure={} simple={} parts={} ref_enums={} enums={}",
        closure.len(),
        ir.simples.len(),
        ir.parts.len(),
        ir.ref_enums.len(),
        ir.enums.len(),
    );

    let dir = format!("{root}/codegen/src/generated");
    std::fs::create_dir_all(&dir).expect("mkdir generated");
    write_fmt(&format!("{dir}/model.rs"), &emit::emit_model(&ir));
    write_fmt(&format!("{dir}/read.rs"), &emit::emit_read(&ir));
    write_fmt(&format!("{dir}/write.rs"), &emit::emit_write(&ir));
    std::fs::write(
        format!("{dir}/mod.rs"),
        "// @generated by codegen. DO NOT EDIT.\n#![allow(dead_code, unused_variables, clippy::all, clippy::pedantic)]\npub mod model;\npub mod read;\npub mod write;\n",
    )
    .expect("write mod.rs");
    eprintln!("codegen: wrote model/read/write to {dir}");
}

fn write_fmt(path: &str, body: &str) {
    std::fs::write(path, body).expect("write generated file");
    let status = Command::new("rustfmt")
        .args(["--edition", "2024", path])
        .status();
    match status {
        Ok(st) if st.success() => {}
        _ => eprintln!("codegen: rustfmt skipped/failed for {path} (kept raw)"),
    }
}
