//! `bind`: `EntityGraph` (late-bound) → `EarlyModel` (L1). Mechanical
//! attribute extraction only — no SELECT resolution, no flatten, no arena
//! lookups (those are [`lower`](super::lower)'s job). In the fully-migrated
//! design this layer is codegen output; here it is hand-written for the
//! founded-item entities migrated so far.

use crate::early::model::{
    EarlyFillAreaStyle, EarlyMarker, EarlyMarkerSize, EarlyPointStyle, EarlySurfaceSideStyle,
    EarlySurfaceStyleUsage,
};
use crate::ir::attr::{
    check_count, read_entity_ref, read_entity_ref_list, read_enum, read_string_or_unset,
};
use crate::ir::error::ConvertError;
use crate::ir::visualization::{MarkerType, SurfaceSide};
use crate::parser::entity::Attribute;

// Generated by `gen-early` (`super::generated::bind`). Re-exported so the
// handlers keep calling `bind::bind_view_volume` etc. unchanged.
pub(crate) use super::generated::bind::{bind_surface_style_fill_area, bind_view_volume};

/// `FILL_AREA_STYLE(name, fill_styles)` → L1.
pub(crate) fn bind_fill_area_style(
    entity_id: u64,
    attrs: &[Attribute],
) -> Result<EarlyFillAreaStyle, ConvertError> {
    check_count(attrs, 2, entity_id, "FILL_AREA_STYLE")?;
    let name = read_string_or_unset(attrs, 0, entity_id, "name")?.to_owned();
    let fill_styles = read_entity_ref_list(attrs, 1, entity_id, "fill_styles")?;
    Ok(EarlyFillAreaStyle { name, fill_styles })
}

/// `SURFACE_SIDE_STYLE(name, styles)` → L1.
pub(crate) fn bind_surface_side_style(
    entity_id: u64,
    attrs: &[Attribute],
) -> Result<EarlySurfaceSideStyle, ConvertError> {
    check_count(attrs, 2, entity_id, "SURFACE_SIDE_STYLE")?;
    let name = read_string_or_unset(attrs, 0, entity_id, "name")?.to_owned();
    let styles = read_entity_ref_list(attrs, 1, entity_id, "styles")?;
    Ok(EarlySurfaceSideStyle { name, styles })
}

/// `SURFACE_STYLE_USAGE(side, style)` → L1.
pub(crate) fn bind_surface_style_usage(
    entity_id: u64,
    attrs: &[Attribute],
) -> Result<EarlySurfaceStyleUsage, ConvertError> {
    check_count(attrs, 2, entity_id, "SURFACE_STYLE_USAGE")?;
    let side = match read_enum(attrs, 0, entity_id, "side")? {
        "POSITIVE" => SurfaceSide::Front,
        "NEGATIVE" => SurfaceSide::Back,
        _ => SurfaceSide::Both, // BOTH or unknown
    };
    let style = read_entity_ref(attrs, 1, entity_id, "style")?;
    Ok(EarlySurfaceStyleUsage { side, style })
}

/// `POINT_STYLE(name, marker, marker_size, marker_colour)` → L1.
///
/// Returns `Ok(None)` when a SELECT member has an unrecognized form (the
/// previous handler silently dropped these via `return Ok(())`); resolve-time
/// drops (unresolved refs) stay in [`lower`](super::lower).
pub(crate) fn bind_point_style(
    entity_id: u64,
    attrs: &[Attribute],
) -> Result<Option<EarlyPointStyle>, ConvertError> {
    check_count(attrs, 4, entity_id, "POINT_STYLE")?;
    let name = read_string_or_unset(attrs, 0, entity_id, "name")?.to_owned();
    let marker = match &attrs[1] {
        Attribute::EntityRef(n) => EarlyMarker::Predefined(*n),
        // `marker_select`'s `marker_type` member is P21 type-tagged as
        // `MARKER_TYPE(.PLUS.)` (NIST fixtures); a bare `.PLUS.` is also accepted.
        Attribute::Typed { type_name, value } if type_name == "MARKER_TYPE" => {
            let Attribute::Enum(token) = value.as_ref() else {
                return Ok(None);
            };
            EarlyMarker::Type(marker_type_from_token(token))
        }
        Attribute::Enum(token) => EarlyMarker::Type(marker_type_from_token(token)),
        _ => return Ok(None),
    };
    let marker_size = match &attrs[2] {
        Attribute::Typed { type_name, value } => match (type_name.as_str(), value.as_ref()) {
            ("POSITIVE_LENGTH_MEASURE", Attribute::Real(v)) => EarlyMarkerSize::PositiveLength(*v),
            ("POSITIVE_LENGTH_MEASURE", Attribute::Integer(v)) => {
                #[allow(clippy::cast_precision_loss)]
                let f = *v as f64;
                EarlyMarkerSize::PositiveLength(f)
            }
            ("DESCRIPTIVE_MEASURE", Attribute::String(s)) => {
                EarlyMarkerSize::Descriptive(s.clone())
            }
            _ => return Ok(None),
        },
        Attribute::EntityRef(n) => EarlyMarkerSize::MeasureWithUnit(*n),
        _ => return Ok(None),
    };
    let marker_colour = read_entity_ref(attrs, 3, entity_id, "marker_colour")?;
    Ok(Some(EarlyPointStyle {
        name,
        marker,
        marker_size,
        marker_colour,
    }))
}

/// STEP `marker_type` enum token → [`MarkerType`].
fn marker_type_from_token(token: &str) -> MarkerType {
    match token {
        "DOT" => MarkerType::Dot,
        "X" => MarkerType::X,
        "PLUS" => MarkerType::Plus,
        "ASTERISK" => MarkerType::Asterisk,
        "RING" => MarkerType::Ring,
        "SQUARE" => MarkerType::Square,
        "TRIANGLE" => MarkerType::Triangle,
        other => MarkerType::Other(other.to_owned()),
    }
}
