//! `bind`: `EntityGraph` (late-bound) → `EarlyModel` (L1). Mechanical attribute
//! extraction; no SELECT resolution / flatten / arena lookups (those are
//! [`lower`](super::lower)'s job). All bind fns are now generated by `gen-early`
//! (`super::generated::bind`) and re-exported here so the handlers keep their
//! `bind::bind_*` paths unchanged.

pub(crate) use super::generated::bind::{
    bind_address, bind_application_context, bind_approval, bind_approval_date_time,
    bind_approval_person_organization, bind_approval_role, bind_approval_status,
    bind_calendar_date, bind_constructive_geometry_representation_relationship,
    bind_context_dependent_shape_representation, bind_coordinated_universal_time_offset,
    bind_date_and_time, bind_date_time_role, bind_document, bind_document_product_equivalence,
    bind_document_representation_type, bind_document_type, bind_fill_area_style, bind_group,
    bind_identification_role, bind_local_time, bind_mechanical_design_and_draughting_relationship,
    bind_next_assembly_usage_occurrence, bind_object_role, bind_organization, bind_person,
    bind_person_and_organization_role, bind_personal_address, bind_point_style, bind_product,
    bind_product_definition, bind_product_definition_formation,
    bind_product_definition_formation_with_specified_source, bind_product_definition_shape,
    bind_product_definition_with_associated_documents, bind_representation_relationship,
    bind_role_association, bind_security_classification, bind_security_classification_level,
    bind_shape_representation_relationship, bind_surface_side_style, bind_surface_style_fill_area,
    bind_surface_style_usage, bind_view_volume,
};
