//! L1 entity types + the transient `EarlyModel` store. See [module docs](super).
//!
//! The L1 types mirror the EXPRESS schema shape faithfully (no flatten / no
//! unification) — verified against `early.toml` (blueprint `l1_export`).

use std::any::TypeId;
use std::collections::HashMap;

use crate::ir::arena::ArenaId;

// Generated by `gen-early` (see `super::generated`). Re-exported here so the
// hand-written `lower`/`lift`/handlers keep their `crate::early::model::…`
// paths. The `Early*Id` types are **pure `id_cache` keys** (no backing arena —
// unlike `define_id!`): migrated producers register `file id → typed L1 id`,
// and the `index()` addresses [`EarlyModel`]'s L1→L2 correspondence bucket.
pub(crate) use super::generated::model::{
    EarlyAddress, EarlyAdvancedFace, EarlyAllAroundShapeAspect, EarlyAngularLocation,
    EarlyAngularSize, EarlyAngularityTolerance, EarlyAnnotationCurveOccurrence,
    EarlyAnnotationOccurrence, EarlyAnnotationPlane, EarlyAnnotationSymbolOccurrence,
    EarlyAnnotationTextOccurrence, EarlyApplicationContext, EarlyApplicationProtocolDefinition,
    EarlyAppliedApprovalAssignment, EarlyAppliedDateAndTimeAssignment,
    EarlyAppliedDocumentReference, EarlyAppliedExternalIdentificationAssignment,
    EarlyAppliedGroupAssignment, EarlyAppliedPersonAndOrganizationAssignment,
    EarlyAppliedPresentedItem, EarlyAppliedSecurityClassificationAssignment, EarlyApproval,
    EarlyApprovalDateTime, EarlyApprovalPersonOrganization, EarlyApprovalRole, EarlyApprovalStatus,
    EarlyAreaInSet, EarlyAxis1Placement, EarlyAxis2Placement2d, EarlyAxis2Placement3d,
    EarlyBSplineCurveWithKnots, EarlyBSplineSurfaceWithKnots, EarlyBoundedPcurve,
    EarlyBoxCharacteristicSelect, EarlyBrepWithVoids, EarlyCalendarDate, EarlyCameraImage,
    EarlyCameraImage3dWithScale, EarlyCameraModelD3, EarlyCameraModelD3MultiClipping,
    EarlyCameraModelD3WithHlhsr, EarlyCameraUsage, EarlyCartesianPoint, EarlyCcDesignApproval,
    EarlyCcDesignDateAndTimeAssignment, EarlyCcDesignPersonAndOrganizationAssignment,
    EarlyCcDesignSecurityClassification, EarlyCentreOfSymmetry,
    EarlyCharacterizedItemWithinRepresentation, EarlyCircle, EarlyCircularArea,
    EarlyCircularRunoutTolerance, EarlyClosedShell, EarlyColour, EarlyColourRgb,
    EarlyComplexTriangulatedFace, EarlyComplexTriangulatedSurfaceSet, EarlyCompositeCurve,
    EarlyCompositeCurveSegment, EarlyCompositeGroupShapeAspect, EarlyCompositeShapeAspect,
    EarlyCompositeText, EarlyCompoundItemDefinition, EarlyCompoundRepresentationItem,
    EarlyConcentricityTolerance, EarlyConicalSurface, EarlyConstructiveGeometryRepresentation,
    EarlyConstructiveGeometryRepresentationRelationship, EarlyContextDependentOverRidingStyledItem,
    EarlyContextDependentShapeRepresentation, EarlyCoordinatedUniversalTimeOffset,
    EarlyCoordinatesList, EarlyCurveBoundedSurface, EarlyCurveStyle, EarlyCylindricalSurface,
    EarlyCylindricityTolerance, EarlyDateAndTime, EarlyDateTimeRole, EarlyDatum, EarlyDatumFeature,
    EarlyDatumSystem, EarlyDatumTarget, EarlyDefaultModelGeometricView, EarlyDefinedSymbol,
    EarlyDegenerateToroidalSurface, EarlyDerivedUnit, EarlyDerivedUnitElement,
    EarlyDescriptionAttribute, EarlyDescriptiveRepresentationItem,
    EarlyDimensionalCharacteristicRepresentation, EarlyDimensionalExponents,
    EarlyDimensionalLocation, EarlyDimensionalSize, EarlyDirectedDimensionalLocation,
    EarlyDirection, EarlyDirectionCountSelect, EarlyDocument, EarlyDocumentFile,
    EarlyDocumentProductEquivalence, EarlyDocumentRepresentationType, EarlyDocumentType,
    EarlyDraughtingAnnotationOccurrence, EarlyDraughtingCallout, EarlyDraughtingPreDefinedColour,
    EarlyDraughtingPreDefinedCurveFont, EarlyEdgeCurve, EarlyEdgeLoop, EarlyEllipse,
    EarlyExternalSource, EarlyFaceBound, EarlyFaceOuterBound, EarlyFaceSurface,
    EarlyFeatureForDatumTargetRelationship, EarlyFillAreaStyle, EarlyFillAreaStyleColour,
    EarlyFillAreaStyleId, EarlyFlatnessTolerance, EarlyGeneralProperty,
    EarlyGeneralPropertyAssociation, EarlyGeometricCurveSet, EarlyGeometricSet,
    EarlyGeometricToleranceRelationship, EarlyGroup, EarlyHyperbola, EarlyIdAttribute,
    EarlyIdentificationRole, EarlyInvisibility, EarlyItemDefinedTransformation,
    EarlyItemIdentifiedRepresentationUsage, EarlyItemIdentifiedRepresentationUsageSelect,
    EarlyKnotType, EarlyLeaderCurve, EarlyLeaderDirectedCallout, EarlyLeaderTerminator,
    EarlyLengthMeasureWithUnit, EarlyLine, EarlyLocalTime, EarlyMakeFromUsageOption,
    EarlyManifoldSolidBrep, EarlyMappedItem, EarlyMarker, EarlyMarkerSize,
    EarlyMassMeasureWithUnit, EarlyMeasureQualification, EarlyMeasureValue, EarlyMeasureWithUnit,
    EarlyMechanicalDesignAndDraughtingRelationship,
    EarlyMechanicalDesignGeometricPresentationRepresentation, EarlyModelGeometricView,
    EarlyNameAttribute, EarlyNextAssemblyUsageOccurrence, EarlyNullStyle, EarlyObjectRole,
    EarlyOffsetCurve3d, EarlyOffsetSurface, EarlyOpenShell, EarlyOrganization,
    EarlyOrientedClosedShell, EarlyOrientedEdge, EarlyOverRidingStyledItem, EarlyParabola,
    EarlyParallelismTolerance, EarlyParametricRepresentationContext,
    EarlyPerpendicularityTolerance, EarlyPerson, EarlyPersonAndOrganization,
    EarlyPersonAndOrganizationRole, EarlyPersonalAddress, EarlyPlacedDatumTargetFeature,
    EarlyPlanarBox, EarlyPlanarExtent, EarlyPlane, EarlyPlaneAngleMeasureWithUnit, EarlyPointStyle,
    EarlyPointStyleId, EarlyPolyline, EarlyPreDefinedCurveFont, EarlyPreDefinedMarker,
    EarlyPreDefinedPointMarkerSymbol, EarlyPreDefinedSymbol, EarlyPreDefinedTerminatorSymbol,
    EarlyPresentationLayerAssignment, EarlyPresentationSet, EarlyPresentationSize,
    EarlyPresentationStyleAssignment, EarlyPresentationStyleByContext,
    EarlyPresentationStyleSelect, EarlyPresentedItemRepresentation, EarlyProduct,
    EarlyProductCategory, EarlyProductDefinition, EarlyProductDefinitionFormation,
    EarlyProductDefinitionFormationId, EarlyProductDefinitionFormationWithSpecifiedSource,
    EarlyProductDefinitionId, EarlyProductDefinitionRelationship, EarlyProductDefinitionShape,
    EarlyProductDefinitionShapeId, EarlyProductDefinitionWithAssociatedDocuments,
    EarlyQualifiedRepresentationItem, EarlyQuasiUniformCurve, EarlyQuasiUniformSurface,
    EarlyRatioMeasureWithUnit, EarlyRationalBSplineCurve, EarlyRationalBSplineSurface,
    EarlyRationalQuasiUniformCurve, EarlyRationalQuasiUniformSurface, EarlyRealRepresentationItem,
    EarlyRectangularTrimmedSurface, EarlyRepositionedTessellatedItem, EarlyRepresentationContext,
    EarlyRepresentationMap, EarlyRepresentationRelationship, EarlyRoleAssociation,
    EarlyRoundnessTolerance, EarlySecurityClassification, EarlySecurityClassificationLevel,
    EarlyShapeAspect, EarlyShapeAspectAssociativity, EarlyShapeAspectDerivingRelationship,
    EarlyShapeAspectRelationship, EarlyShapeDefinitionRepresentation,
    EarlyShapeDimensionRepresentation, EarlyShapeRepresentationRelationship,
    EarlyShapeRepresentationWithParameters, EarlyShellBasedSurfaceModel, EarlySource,
    EarlySourceItem, EarlySphericalSurface, EarlyStraightnessTolerance, EarlyStyledItem,
    EarlySurfaceOfLinearExtrusion, EarlySurfaceOfRevolution, EarlySurfaceProfileTolerance,
    EarlySurfaceSideStyle, EarlySurfaceSideStyleId, EarlySurfaceStyleBoundary,
    EarlySurfaceStyleFillArea, EarlySurfaceStyleFillAreaId, EarlySurfaceStyleParameterLine,
    EarlySurfaceStyleTransparent, EarlySurfaceStyleUsage, EarlySurfaceStyleUsageId,
    EarlySymbolColour, EarlySymbolStyle, EarlySymbolTarget, EarlySymmetryTolerance,
    EarlyTessellatedAnnotationOccurrence, EarlyTessellatedCurveSet, EarlyTessellatedGeometricSet,
    EarlyTessellatedShapeRepresentation, EarlyTessellatedShell, EarlyTessellatedSolid,
    EarlyTextLiteral, EarlyTextStyleForDefinedFont, EarlyTextStyleWithBoxCharacteristics,
    EarlyToleranceZone, EarlyToleranceZoneForm, EarlyToroidalSurface, EarlyTotalRunoutTolerance,
    EarlyTrimSelect, EarlyTrimmedCurve, EarlyTypeQualifier, EarlyUncertaintyMeasureWithUnit,
    EarlyValueFormatTypeQualifier, EarlyValueRepresentationItem, EarlyVector, EarlyVertexLoop,
    EarlyVertexPoint, EarlyViewVolume, EarlyViewVolumeId,
};

/// Transient L1 store, held on [`ReaderContext`](crate::reader::ReaderContext)
/// for one parse. Holds the read-side **L1→L2 correspondence** for every
/// entity migrated to the 2-layer path.
///
/// One `TypeId`-keyed table suffices (mirroring the reader's `IdMapCache`):
/// each L1 id type `K` gets its own bucket, `K::index()` addresses the `Vec`,
/// and the stored L2 arena id round-trips through its raw `u32` index
/// (`ArenaId::from_index`, the same erasure the `IdMapCache` uses) so buckets
/// of different L2 id types coexist. This is exactly the collision-free keying
/// that lets `id_cache` distinguish members the bespoke `viz_*_id_map` fields
/// could not — e.g. `surface_side_style` probes
/// `id_cache.get::<EarlySurfaceStyleFillAreaId>(r)` where the seven maps'
/// shared value type (`FoundedItemId`) would have collided in a single bucket.
/// The distinct `Early*Id` key types are generated per entity by `gen-early`
/// (in `generated/model.rs`).
///
/// The recorded value need not be the producer's own arena id — a producer may
/// record what its *consumers* resolve through it (e.g. `product_definition`
/// records the 2-hop `ProductId`), collapsing former multi-hop raw-id chains
/// into one typed probe.
#[derive(Default)]
pub(crate) struct EarlyModel {
    lowered: HashMap<TypeId, Vec<u32>>,
}

impl EarlyModel {
    /// Record that a migrated entity lowered to the L2 id `l2`, returning a
    /// fresh typed L1 id `K` addressing it. The caller registers the returned
    /// id in the reader's `id_cache` (keyed by file id) so a consumer can
    /// recover `l2` by L1 type via [`lookup_lowered`](Self::lookup_lowered).
    pub(crate) fn record_lowered<K: ArenaId, V: ArenaId>(&mut self, l2: V) -> K {
        let bucket = self.lowered.entry(TypeId::of::<K>()).or_default();
        let idx = bucket.len();
        bucket.push(u32::try_from(l2.index()).expect("early lowered value overflow"));
        K::from_index(u32::try_from(idx).expect("early lowered arena overflow"))
    }

    /// Recover the L2 id a typed L1 id `K` was recorded for. `V` must be the
    /// same L2 id type the producer recorded under `K` (each `K` bucket holds
    /// exactly one `V` by construction — the producer's `lower` is the only
    /// writer).
    pub(crate) fn lookup_lowered<K: ArenaId, V: ArenaId>(&self, id: K) -> V {
        V::from_index(self.lowered[&TypeId::of::<K>()][id.index()])
    }
}
