//! `serialize`: `EarlyModel` (L1) → Part21 text. Purely mechanical — one
//! `push_simple` per L1 node, attributes in EXPRESS positional order. All
//! serialize fns are now generated by `gen-early` (`super::generated::serialize`)
//! and re-exported here so the handlers keep their `serialize::serialize_*` paths.

pub(crate) use super::generated::serialize::{
    serialize_fill_area_style, serialize_point_style, serialize_surface_side_style,
    serialize_surface_style_fill_area, serialize_surface_style_usage, serialize_view_volume,
};
