//! `serialize`: `EarlyModel` (L1) → Part21 text. Purely mechanical — one
//! `push_simple` per L1 node, attributes in EXPRESS positional order. All
//! serialize fns are now generated by `gen-early` (`super::generated::serialize`)
//! and re-exported here so the handlers keep their `serialize::serialize_*` paths.

pub(crate) use super::generated::serialize::{
    serialize_address, serialize_application_context, serialize_application_protocol_definition,
    serialize_applied_approval_assignment, serialize_applied_date_and_time_assignment,
    serialize_applied_document_reference, serialize_applied_external_identification_assignment,
    serialize_applied_group_assignment, serialize_applied_person_and_organization_assignment,
    serialize_applied_security_classification_assignment, serialize_approval,
    serialize_approval_date_time, serialize_approval_person_organization, serialize_approval_role,
    serialize_approval_status, serialize_calendar_date, serialize_cc_design_approval,
    serialize_cc_design_date_and_time_assignment,
    serialize_cc_design_person_and_organization_assignment,
    serialize_cc_design_security_classification, serialize_colour_rgb,
    serialize_constructive_geometry_representation_relationship,
    serialize_context_dependent_shape_representation, serialize_coordinated_universal_time_offset,
    serialize_date_and_time, serialize_date_time_role, serialize_derived_unit,
    serialize_derived_unit_element, serialize_dimensional_exponents, serialize_document,
    serialize_document_file, serialize_document_product_equivalence,
    serialize_document_representation_type, serialize_document_type,
    serialize_draughting_pre_defined_colour, serialize_draughting_pre_defined_curve_font,
    serialize_fill_area_style, serialize_group, serialize_identification_role,
    serialize_local_time, serialize_mechanical_design_and_draughting_relationship,
    serialize_next_assembly_usage_occurrence, serialize_object_role, serialize_organization,
    serialize_person, serialize_person_and_organization, serialize_person_and_organization_role,
    serialize_personal_address, serialize_point_style, serialize_pre_defined_curve_font,
    serialize_pre_defined_marker, serialize_pre_defined_point_marker_symbol,
    serialize_pre_defined_symbol, serialize_pre_defined_terminator_symbol, serialize_product,
    serialize_product_definition, serialize_product_definition_formation,
    serialize_product_definition_formation_with_specified_source,
    serialize_product_definition_shape, serialize_product_definition_with_associated_documents,
    serialize_representation_relationship, serialize_role_association,
    serialize_security_classification, serialize_security_classification_level,
    serialize_shape_representation_relationship, serialize_surface_side_style,
    serialize_surface_style_fill_area, serialize_surface_style_usage, serialize_symbol_colour,
    serialize_view_volume,
};
