//! `serialize`: `EarlyModel` (L1) → Part21 text. Purely mechanical — one
//! `push_simple` per L1 node, attributes in EXPRESS positional order. All
//! serialize fns are now generated by `gen-early` (`super::generated::serialize`)
//! and re-exported here so the handlers keep their `serialize::serialize_*` paths.

pub(crate) use super::generated::serialize::{
    serialize_constructive_geometry_representation_relationship,
    serialize_context_dependent_shape_representation, serialize_fill_area_style,
    serialize_mechanical_design_and_draughting_relationship,
    serialize_next_assembly_usage_occurrence, serialize_point_style, serialize_product,
    serialize_product_definition, serialize_product_definition_formation,
    serialize_product_definition_formation_with_specified_source,
    serialize_product_definition_shape, serialize_product_definition_with_associated_documents,
    serialize_representation_relationship, serialize_shape_representation_relationship,
    serialize_surface_side_style, serialize_surface_style_fill_area, serialize_surface_style_usage,
    serialize_view_volume,
};
