//! Code emission: per-entity model/bind/serialize ([`emit_entity`]) and the
//! shared SELECT / ENUM / list / grid helpers.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use crate::classify::{Ctx, Kind, pascal};
use crate::expr::{bind_expr_full, field_ty, field_ty_full, serialize_expr_full, vec_elem_closure};
use crate::schema::{enum_members, select_members, strip_optional};

pub(crate) const HEADER: &str = "// DO NOT EDIT — generated by `cargo run -p gen-early` from schema/early.toml\n// + schema/mapping.toml. Hand-written lower/lift live in the sibling modules.\n\n";

/// Accumulated generator output: the three file bodies plus the cross-entity
/// tracking sets that decide which shared helpers to emit after the entity
/// loop ([`emit_entity`] fills it; `main` drains it).
pub(crate) struct GenOut {
    pub(crate) model: String,
    pub(crate) bind: String,
    pub(crate) serialize: String,
    pub(crate) used_enums: BTreeSet<String>,
    pub(crate) used_enum_lists: BTreeSet<String>,
    pub(crate) used_selects: BTreeSet<String>,
    pub(crate) used_select_lists: BTreeSet<String>,
    pub(crate) used_select_grids: BTreeSet<String>,
    pub(crate) any_bool: bool,
    pub(crate) any_logical_list: bool,
}

impl GenOut {
    pub(crate) fn new(head: &str) -> Self {
        Self {
            model: head.to_string(),
            bind: head.to_string(),
            serialize: head.to_string(),
            used_enums: BTreeSet::new(),
            used_enum_lists: BTreeSet::new(),
            used_selects: BTreeSet::new(),
            used_select_lists: BTreeSet::new(),
            used_select_grids: BTreeSet::new(),
            any_bool: false,
            any_logical_list: false,
        }
    }
}

/// Emit one entity's model struct + `Early*Id` + `bind_<entity>` +
/// `serialize_<entity>` into `out`, recording which shared helpers it needs
/// (extracted from the former inline loop in `main`).
pub(crate) fn emit_entity(ctx: &Ctx, ent_name: &str, out: &mut GenOut) {
    let type_name = format!("Early{}", pascal(ent_name));
    let step_name = ent_name.to_uppercase();
    // Complex (multi-part) entities take a separate path: bind reads per named
    // part, serialize emits a `WriterBody::Complex`. See `emit_complex_entity`.
    // A complex entity may be a synthetic name (a multi-supertype instance with
    // no single early.toml entity, e.g. `rational_quasi_uniform_curve`), so the
    // entity-exists assert is for the simple path only; the complex path
    // validates each part instead.
    if let Some(hint) = ctx.mapping.complex.get(ent_name) {
        if let Some(cases) = &hint.cases {
            emit_multi_case_complex(ctx, ent_name, &type_name, &step_name, cases, out);
        } else {
            emit_complex_entity(ctx, ent_name, &type_name, &step_name, hint, out);
        }
        return;
    }
    assert!(
        ctx.schema.entity.contains_key(ent_name),
        "gen-early: entity `{ent_name}` not in early.toml"
    );
    // Full Part21 positional attribute list (inherited supertype attrs
    // prepended, then own); see `EarlyToml::flattened_attrs`. Each entry is
    // (struct field name, kind, is-optional).
    // EXPRESS Derived (`*`) attrs (hand-authored in mapping `[derived]`): matched
    // by early.toml attr name (before the dedup below). A derived attr keeps its
    // positional slot (so later attrs read at the right Part21 index) but gets no
    // struct field / bind read, and serializes as `*`.
    let derived_set = ctx.mapping.derived.get(ent_name);
    let mut attrs: Vec<(String, Kind, bool, bool)> = ctx
        .schema
        .flattened_attrs(ent_name)
        .into_iter()
        .map(|a| {
            let (optional, inner) = strip_optional(&a.ty);
            let derived = derived_set.is_some_and(|d| d.contains(&a.name));
            (a.name.clone(), ctx.classify(inner, 0), optional, derived)
        })
        .collect();
    // Multiple inheritance can produce two distinct attrs sharing a name
    // (e.g. `document`'s `name` and `characterized_object`'s `name`); both are
    // faithful positional fields, so disambiguate the Rust field identifier
    // (`name`, `name_2`, …) — deterministic, first occurrence keeps the name.
    let mut used: BTreeSet<String> = BTreeSet::new();
    for (field, _, _, _) in &mut attrs {
        if used.contains(field) {
            let base = field.clone();
            let mut n = 2;
            while used.contains(&format!("{base}_{n}")) {
                n += 1;
            }
            *field = format!("{base}_{n}");
        }
        used.insert(field.clone());
    }
    let has_select = attrs
        .iter()
        .any(|(_, k, _, d)| !d && matches!(k, Kind::Select(_)));

    emit_model_and_id(ctx, &type_name, &step_name, &attrs, out);

    entity_bind(ent_name, &type_name, &step_name, &attrs, has_select, out);

    // `read_only` entities (read-back-only minority forms normalized away on
    // write) skip serialize: their handler `write` is `unreachable!()`.
    if !ctx.mapping.read_only.iter().any(|e| e == ent_name) {
        entity_serialize(ctx, ent_name, &type_name, &step_name, &attrs, out);
    }
}

/// Emit the `Early*` model struct + its `Early*Id` `id_cache` key (shared by the
/// simple and complex paths). `attrs` is the flat field list (derived fields
/// keep no struct field).
fn emit_model_and_id(
    ctx: &Ctx,
    type_name: &str,
    step_name: &str,
    attrs: &[(String, Kind, bool, bool)],
    out: &mut GenOut,
) {
    emit_struct_model(ctx, type_name, step_name, attrs, out);
    emit_id_only(type_name, step_name, out);
}

/// Emit just the `Early*` model struct (no Id). `attrs` is the flat field list
/// (derived fields keep no struct field). Shared by [`emit_model_and_id`] and
/// the multi-case enum path (inner per-case structs).
fn emit_struct_model(
    ctx: &Ctx,
    type_name: &str,
    step_name: &str,
    attrs: &[(String, Kind, bool, bool)],
    out: &mut GenOut,
) {
    // model struct. All-scalar shapes wider than 8 bytes get `Copy` so
    // by-value `lower`/`lift` adapters compile under clippy's
    // needless_pass_by_value. At ≤ 8 bytes `Copy` would instead flip the
    // existing by-reference signatures into trivially_copy_pass_by_ref.
    let scalar_size = |t: &str| -> Option<usize> {
        match t {
            "u64" | "i64" | "f64" => Some(8),
            "bool" => Some(1),
            "Option<u64>" | "Option<i64>" | "Option<f64>" => Some(16),
            "Option<bool>" => Some(2),
            _ => None,
        }
    };
    let all_copy = attrs
        .iter()
        .filter(|(_, _, _, d)| !d)
        .map(|(_, k, opt, _)| scalar_size(&field_ty_full(ctx, k, *opt)))
        .try_fold(0usize, |acc, s| s.map(|s| acc + s))
        .is_some_and(|total| total > 8);
    writeln!(out.model, "/// L1 `{step_name}` (generated).").unwrap();
    writeln!(
        out.model,
        "#[derive(Debug, Clone{}, PartialEq)]",
        if all_copy { ", Copy" } else { "" }
    )
    .unwrap();
    writeln!(out.model, "pub(crate) struct {type_name} {{").unwrap();
    for (field, k, opt, derived) in attrs {
        if *derived {
            continue; // Derived (`*`) slot: not stored data, no struct field.
        }
        writeln!(
            out.model,
            "    pub(crate) {}: {},",
            field,
            field_ty_full(ctx, k, *opt)
        )
        .unwrap();
    }
    writeln!(out.model, "}}\n").unwrap();
}

/// Emit just the typed `id_cache` key newtype + its `ArenaId` impl (the expanded
/// form of the former hand-written `early_id!` macro): a pure cache-key newtype
/// whose index addresses `EarlyModel`'s L1→L2 correspondence bucket. Shared by
/// the struct model path ([`emit_model_and_id`]) and the multi-case enum model
/// path ([`emit_multi_case_complex`]).
fn emit_id_only(type_name: &str, step_name: &str, out: &mut GenOut) {
    writeln!(
        out.model,
        "/// Typed `id_cache` key for `{step_name}` (file id → L1→L2 correspondence;\n/// see `EarlyModel`)."
    )
    .unwrap();
    // A key type is legitimately unused until its first consumer migrates, so
    // the (committed) generated output carries a targeted allow.
    writeln!(out.model, "#[allow(dead_code)]").unwrap();
    writeln!(
        out.model,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]"
    )
    .unwrap();
    writeln!(out.model, "pub(crate) struct {type_name}Id(pub u32);").unwrap();
    writeln!(out.model).unwrap();
    writeln!(
        out.model,
        "impl crate::ir::arena::ArenaId for {type_name}Id {{"
    )
    .unwrap();
    writeln!(out.model, "    fn index(&self) -> usize {{").unwrap();
    writeln!(out.model, "        self.0 as usize").unwrap();
    writeln!(out.model, "    }}").unwrap();
    writeln!(out.model, "    fn from_index(index: u32) -> Self {{").unwrap();
    writeln!(out.model, "        Self(index)").unwrap();
    writeln!(out.model, "    }}").unwrap();
    writeln!(out.model, "}}\n").unwrap();
}

/// Record which shared serialize helpers an attribute Kind needs (enum `_attr`,
/// `bool_attr`, list/grid helpers). Shared by the simple and complex emitters.
fn track_serialize_usage(k: &Kind, out: &mut GenOut) {
    match k {
        Kind::Bool => out.any_bool = true,
        Kind::Enum(alias) => {
            out.used_enums.insert(alias.clone());
        }
        Kind::Select(alias) => {
            out.used_selects.insert(alias.clone());
        }
        // `Vec<EarlyEnum>`: needs the enum model + `<alias>_attr` (via
        // used_enums) and a `<alias>_list` bind helper.
        Kind::Vec(inner) => match &**inner {
            Kind::Enum(alias) => {
                out.used_enums.insert(alias.clone());
                out.used_enum_lists.insert(alias.clone());
            }
            // `Vec<EarlySelect>`: needs bind_<select>/<alias>_emit (via
            // used_selects) and a `<alias>_list` bind helper.
            Kind::Select(alias) => {
                out.used_selects.insert(alias.clone());
                out.used_select_lists.insert(alias.clone());
            }
            // `Vec<Logical>`: the single `logical_list` bind helper.
            Kind::Logical => out.any_logical_list = true,
            // `Vec<Vec<EarlySelect>>`: needs bind_<select>/<alias>_emit
            // (via used_selects) and a `<alias>_grid` bind helper.
            Kind::Vec(i2) => {
                if let Kind::Select(alias) = &**i2 {
                    out.used_selects.insert(alias.clone());
                    out.used_select_grids.insert(alias.clone());
                }
            }
            _ => {}
        },
        _ => {}
    }
}

/// Emit model + Id + bind + serialize for a multi-part (complex) entity. Each
/// part of `hint.parts` contributes its `own_attrs` (in order); bind reads each
/// non-empty part once via `require_part_attrs` (shadowing `attrs`), serialize
/// emits a `WriterBody::Complex` via `push_complex`. Single-case only; a SELECT
/// part attr is rejected (not yet supported).
#[allow(clippy::too_many_lines)] // one cohesive codegen routine (model+bind+serialize)
fn emit_complex_entity(
    ctx: &Ctx,
    ent_name: &str,
    type_name: &str,
    step_name: &str,
    hint: &crate::mapping::ComplexHint,
    out: &mut GenOut,
) {
    let derived_set = ctx.mapping.derived.get(ent_name);
    let parts = hint
        .parts
        .as_ref()
        .expect("single-case complex must have `parts` (use `cases` for multi-case)");
    // (part_name, local_index, field, kind, optional, derived) per attr, in
    // part order, each part's own_attrs indexed locally from 0.
    let mut entries: Vec<(String, usize, String, Kind, bool, bool)> = Vec::new();
    for part in parts {
        // Hint part names are the wire (upper-cased) form; early.toml keys are
        // lower-cased. Look up own_attrs by the lower-cased name; keep the
        // upper-cased `part` for `require_part_attrs` / the emitted STEP token.
        // Every part must be a real entity (an empty supertype is fine, but a
        // typo'd part would silently yield no attrs) — assert existence here
        // since the complex path skips emit_entity's entity-exists assert.
        assert!(
            ctx.schema.entity.contains_key(&part.to_lowercase()),
            "gen-early: complex `{ent_name}` part `{part}` not in early.toml"
        );
        for (li, a) in ctx
            .schema
            .own_attrs(&part.to_lowercase())
            .into_iter()
            .enumerate()
        {
            let (optional, inner) = strip_optional(&a.ty);
            let derived = derived_set.is_some_and(|d| d.contains(&a.name));
            entries.push((
                part.clone(),
                li,
                a.name.clone(),
                ctx.classify(inner, 0),
                optional,
                derived,
            ));
        }
    }
    // Disambiguate duplicate field names across parts (same dedup as emit_entity).
    let mut used: BTreeSet<String> = BTreeSet::new();
    for e in &mut entries {
        if used.contains(&e.2) {
            let base = e.2.clone();
            let mut n = 2;
            while used.contains(&format!("{base}_{n}")) {
                n += 1;
            }
            e.2 = format!("{base}_{n}");
        }
        used.insert(e.2.clone());
    }
    assert!(
        !entries.iter().any(|e| matches!(e.3, Kind::Select(_))),
        "gen-early: complex entity `{ent_name}` has a SELECT attr — not yet supported"
    );

    let model_attrs: Vec<(String, Kind, bool, bool)> = entries
        .iter()
        .map(|(_, _, f, k, o, d)| (f.clone(), k.clone(), *o, *d))
        .collect();
    emit_model_and_id(ctx, type_name, step_name, &model_attrs, out);

    // bind: per-part `require_part_attrs` (shadow `attrs`) + per-field reads.
    writeln!(
        out.bind,
        "pub(crate) fn bind_{ent_name}(entity_id: u64, parts: &[crate::parser::entity::RawEntityPart]) -> Result<super::model::{type_name}, crate::ir::error::ConvertError> {{"
    )
    .unwrap();
    for part in parts {
        let fields: Vec<&(String, usize, String, Kind, bool, bool)> =
            entries.iter().filter(|e| &e.0 == part && !e.5).collect();
        if fields.is_empty() {
            continue; // empty / all-derived part: nothing to read.
        }
        writeln!(
            out.bind,
            "    let attrs = crate::reader::require_part_attrs(parts, \"{part}\", entity_id)?;"
        )
        .unwrap();
        for (_, li, field, k, opt, _) in fields {
            writeln!(
                out.bind,
                "    let {field} = {};",
                bind_expr_full(k, *li, field, *opt)
            )
            .unwrap();
        }
    }
    writeln!(out.bind, "    Ok(super::model::{type_name} {{").unwrap();
    for (_, _, field, _, _, derived) in &entries {
        if *derived {
            continue;
        }
        writeln!(out.bind, "        {field},").unwrap();
    }
    writeln!(out.bind, "    }})\n}}\n").unwrap();

    if ctx.mapping.read_only.iter().any(|e| e == ent_name) {
        return; // read_only: writer normalizes this form away — no serialize.
    }

    // serialize: `WriterBody::Complex`, parts in hint order. The `vec![..]`
    // parts literal is built once and reused by both the fresh-id `serialize_<e>`
    // (push_complex) and, for serialize_with_id entities, the reserved-id
    // `serialize_<e>_with_id` (push_complex_with_id) — identical bytes, no drift.
    let mut parts_lit = String::from("vec![\n");
    for part in parts {
        writeln!(parts_lit, "        (\"{part}\".into(), vec![").unwrap();
        for (_, _, field, k, opt, derived) in entries.iter().filter(|e| &e.0 == part) {
            if *derived {
                parts_lit.push_str("            crate::parser::entity::Attribute::Derived,\n");
                continue;
            }
            writeln!(
                parts_lit,
                "            {},",
                serialize_expr_full(k, field, *opt)
            )
            .unwrap();
            track_serialize_usage(k, out);
        }
        parts_lit.push_str("        ]),\n");
    }
    parts_lit.push_str("    ]");

    writeln!(
        out.serialize,
        "pub(crate) fn serialize_{ent_name}(buf: &mut crate::writer::buffer::WriteBuffer, l1: &super::model::{type_name}) -> u64 {{"
    )
    .unwrap();
    writeln!(out.serialize, "    buf.push_complex({parts_lit})\n}}\n").unwrap();

    if ctx.mapping.serialize_with_id.iter().any(|e| e == ent_name) {
        writeln!(
            out.serialize,
            "pub(crate) fn serialize_{ent_name}_with_id(buf: &mut crate::writer::buffer::WriteBuffer, id: u64, l1: &super::model::{type_name}) {{"
        )
        .unwrap();
        writeln!(
            out.serialize,
            "    buf.push_complex_with_id(id, {parts_lit});\n}}\n"
        )
        .unwrap();
    }
}

/// Collect one case's flat `(part, local_index, field, kind, optional, derived)`
/// entries (part order; each part's `own_attrs` indexed locally). `derived_attrs`
/// is the case-specific Derived (`*`) attr-name list. Field names are
/// disambiguated across parts (`name`, `name_2`, …). Mirrors the single-case
/// `emit_complex_entity` collection.
fn collect_case_entries(
    ctx: &Ctx,
    ent_name: &str,
    parts: &[String],
    derived_attrs: &[String],
) -> Vec<(String, usize, String, Kind, bool, bool)> {
    let mut entries: Vec<(String, usize, String, Kind, bool, bool)> = Vec::new();
    for part in parts {
        assert!(
            ctx.schema.entity.contains_key(&part.to_lowercase()),
            "gen-early: multi-case `{ent_name}` part `{part}` not in early.toml"
        );
        for (li, a) in ctx
            .schema
            .own_attrs(&part.to_lowercase())
            .into_iter()
            .enumerate()
        {
            let (optional, inner) = strip_optional(&a.ty);
            let derived = derived_attrs.contains(&a.name);
            entries.push((
                part.clone(),
                li,
                a.name.clone(),
                ctx.classify(inner, 0),
                optional,
                derived,
            ));
        }
    }
    let mut used: BTreeSet<String> = BTreeSet::new();
    for e in &mut entries {
        if used.contains(&e.2) {
            let base = e.2.clone();
            let mut n = 2;
            while used.contains(&format!("{base}_{n}")) {
                n += 1;
            }
            e.2 = format!("{base}_{n}");
        }
        used.insert(e.2.clone());
    }
    assert!(
        !entries.iter().any(|e| matches!(e.3, Kind::Select(_))),
        "gen-early: multi-case entity `{ent_name}` has a SELECT attr — not yet supported"
    );
    entries
}

/// Emit a **multi-case** complex entity ([`crate::mapping::ComplexHint::cases`]):
/// an L1 **enum** with one variant per case, each wrapping a per-case inner
/// struct (so the existing `serialize_expr_full` `l1.field` form is reused
/// verbatim — the match arm rebinds the inner struct as `l1`). bind selects the
/// case by part presence (`CaseHint::discriminant`; the no-discriminant case is
/// the fallback). serialize matches the variant.
#[allow(clippy::too_many_lines)] // one cohesive codegen routine (model+bind+serialize)
fn emit_multi_case_complex(
    ctx: &Ctx,
    ent_name: &str,
    type_name: &str,
    step_name: &str,
    cases: &std::collections::BTreeMap<String, crate::mapping::CaseHint>,
    out: &mut GenOut,
) {
    // Per case: (case key, variant pascal, inner struct type, hint, entries).
    let cases_data: Vec<(&String, String, String, &crate::mapping::CaseHint, _)> = cases
        .iter()
        .map(|(cn, ch)| {
            let variant = pascal(cn);
            let inner_type = format!("{type_name}{variant}");
            let entries = collect_case_entries(ctx, ent_name, &ch.parts, &ch.derived);
            (cn, variant, inner_type, ch, entries)
        })
        .collect();
    // Exact-set mode (any case has `match_parts`) dispatches by full part-set,
    // so every case is no-discriminant by design — the ≤1-fallback rule only
    // applies to single-part discriminant mode.
    let exact_mode = cases_data
        .iter()
        .any(|(_, _, _, ch, _)| ch.match_parts.is_some());
    assert!(
        exact_mode
            || cases_data
                .iter()
                .filter(|(_, _, _, ch, _)| ch.discriminant.is_none())
                .count()
                <= 1,
        "gen-early: multi-case `{ent_name}` must have at most one fallback (no-discriminant) case"
    );

    // 1. Inner per-case structs (reuse the struct-model emitter).
    for (_, _, inner_type, _, entries) in &cases_data {
        let model_attrs: Vec<(String, Kind, bool, bool)> = entries
            .iter()
            .map(|(_, _, f, k, o, d)| (f.clone(), k.clone(), *o, *d))
            .collect();
        emit_struct_model(ctx, inner_type, step_name, &model_attrs, out);
    }

    // 2. Outer enum (no Copy — an inner struct may hold a String).
    writeln!(out.model, "/// L1 `{step_name}` (generated, multi-case).").unwrap();
    writeln!(out.model, "#[derive(Debug, Clone, PartialEq)]").unwrap();
    writeln!(out.model, "pub(crate) enum {type_name} {{").unwrap();
    for (_, variant, inner_type, _, _) in &cases_data {
        writeln!(out.model, "    {variant}({inner_type}),").unwrap();
    }
    writeln!(out.model, "}}\n").unwrap();

    // 3. Id key.
    emit_id_only(type_name, step_name, out);

    // 4. bind: discriminant dispatch.
    writeln!(
        out.bind,
        "pub(crate) fn bind_{ent_name}(entity_id: u64, parts: &[crate::parser::entity::RawEntityPart]) -> Result<super::model::{type_name}, crate::ir::error::ConvertError> {{"
    )
    .unwrap();
    // Writes the per-part `let attrs`/`let field` reads for one case.
    let emit_case_reads =
        |bind: &mut String,
         ch: &crate::mapping::CaseHint,
         entries: &[(String, usize, String, Kind, bool, bool)]| {
            for part in &ch.parts {
                let fields: Vec<_> = entries.iter().filter(|e| &e.0 == part && !e.5).collect();
                if fields.is_empty() {
                    continue;
                }
                writeln!(
                bind,
                "    let attrs = crate::reader::require_part_attrs(parts, \"{part}\", entity_id)?;"
            )
            .unwrap();
                for (_, li, field, k, opt, _) in fields {
                    writeln!(
                        bind,
                        "    let {field} = {};",
                        bind_expr_full(k, *li, field, *opt)
                    )
                    .unwrap();
                }
            }
        };
    // The `Type::Variant(Inner { fields.. })` constructor expression.
    let case_ctor =
        |variant: &str, inner_type: &str, entries: &[(String, usize, String, Kind, bool, bool)]| {
            let fields: Vec<&str> = entries
                .iter()
                .filter(|e| !e.5)
                .map(|e| e.2.as_str())
                .collect();
            format!(
                "super::model::{type_name}::{variant}(super::model::{inner_type} {{ {} }})",
                fields.join(", ")
            )
        };
    // Exact-set mode (opt-in via any case's `match_parts`): dispatch by the
    // instance's distinct part-set == the case's set. Needed when a single
    // discriminant part can't separate cases (e.g. DRAUGHTING_MODEL A ⊂ B).
    // Dispatch already guarantees a distinct part-set, so `len + all-contained`
    // = set equality. (`exact_mode` computed above.)
    if exact_mode {
        writeln!(
            out.bind,
            "    let part_set: std::collections::BTreeSet<&str> = parts.iter().map(|p| p.name.as_str()).collect();"
        )
        .unwrap();
        for (_, variant, inner_type, ch, entries) in &cases_data {
            let set = ch.match_parts.as_ref().unwrap_or(&ch.parts);
            let n = set.len();
            let conds: Vec<String> = set
                .iter()
                .map(|p| format!("part_set.contains(\"{p}\")"))
                .collect();
            writeln!(
                out.bind,
                "    if part_set.len() == {n} && {} {{",
                conds.join(" && ")
            )
            .unwrap();
            emit_case_reads(&mut out.bind, ch, entries);
            writeln!(
                out.bind,
                "    return Ok({});",
                case_ctor(variant, inner_type, entries)
            )
            .unwrap();
            writeln!(out.bind, "    }}").unwrap();
        }
        writeln!(
            out.bind,
            "    Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: \"unsupported {step_name} complex case\".into() }})"
        )
        .unwrap();
        writeln!(out.bind, "}}\n").unwrap();
    } else {
        for (_, variant, inner_type, ch, entries) in &cases_data {
            let Some(disc) = &ch.discriminant else {
                continue;
            };
            writeln!(
                out.bind,
                "    if parts.iter().any(|p| p.name == \"{disc}\") {{"
            )
            .unwrap();
            emit_case_reads(&mut out.bind, ch, entries);
            writeln!(
                out.bind,
                "    return Ok({});",
                case_ctor(variant, inner_type, entries)
            )
            .unwrap();
            writeln!(out.bind, "    }}").unwrap();
        }
        if let Some((_, variant, inner_type, ch, entries)) = cases_data
            .iter()
            .find(|(_, _, _, ch, _)| ch.discriminant.is_none())
        {
            emit_case_reads(&mut out.bind, ch, entries);
            writeln!(
                out.bind,
                "    Ok({})",
                case_ctor(variant, inner_type, entries)
            )
            .unwrap();
        } else {
            writeln!(
                out.bind,
                "    Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: \"unsupported {step_name} complex case\".into() }})"
            )
            .unwrap();
        }
        writeln!(out.bind, "}}\n").unwrap();
    }

    // 5. serialize: build each variant's parts literal, match on variant.
    if ctx.mapping.read_only.iter().any(|e| e == ent_name) {
        return;
    }
    let variant_lits: Vec<(String, String)> = cases_data
        .iter()
        .map(|(_, variant, _, ch, entries)| {
            let mut parts_lit = String::from("vec![\n");
            for part in &ch.parts {
                writeln!(parts_lit, "        (\"{part}\".into(), vec![").unwrap();
                for (_, _, field, k, opt, derived) in entries.iter().filter(|e| &e.0 == part) {
                    if *derived {
                        parts_lit
                            .push_str("            crate::parser::entity::Attribute::Derived,\n");
                        continue;
                    }
                    writeln!(
                        parts_lit,
                        "            {},",
                        serialize_expr_full(k, field, *opt)
                    )
                    .unwrap();
                    track_serialize_usage(k, out);
                }
                parts_lit.push_str("        ]),\n");
            }
            parts_lit.push_str("    ]");
            (variant.clone(), parts_lit)
        })
        .collect();

    writeln!(
        out.serialize,
        "pub(crate) fn serialize_{ent_name}(buf: &mut crate::writer::buffer::WriteBuffer, l1: &super::model::{type_name}) -> u64 {{"
    )
    .unwrap();
    writeln!(out.serialize, "    match l1 {{").unwrap();
    for (variant, parts_lit) in &variant_lits {
        writeln!(
            out.serialize,
            "        super::model::{type_name}::{variant}(l1) => buf.push_complex({parts_lit}),"
        )
        .unwrap();
    }
    writeln!(out.serialize, "    }}\n}}\n").unwrap();

    if ctx.mapping.serialize_with_id.iter().any(|e| e == ent_name) {
        writeln!(
            out.serialize,
            "pub(crate) fn serialize_{ent_name}_with_id(buf: &mut crate::writer::buffer::WriteBuffer, id: u64, l1: &super::model::{type_name}) {{"
        )
        .unwrap();
        writeln!(out.serialize, "    match l1 {{").unwrap();
        for (variant, parts_lit) in &variant_lits {
            writeln!(
                out.serialize,
                "        super::model::{type_name}::{variant}(l1) => buf.push_complex_with_id(id, {parts_lit}),"
            )
            .unwrap();
        }
        writeln!(out.serialize, "    }}\n}}\n").unwrap();
    }
}

/// Emit a synthesized `Early*` enum + `bind_<sel>` / `<sel>_emit` for a mixed
/// SELECT. Enum members are recorded in `token_enums` for [`emit_token_enum`].
pub(crate) fn emit_select(
    ctx: &Ctx,
    sel: &str,
    model: &mut String,
    bind: &mut String,
    serialize: &mut String,
    token_enums: &mut BTreeSet<String>,
) {
    let hint = ctx.select_hint(sel);
    let rt = hint.rust_type.clone();
    // The synthesized enum lives in generated/model.rs; bind/serialize (sibling
    // modules) reference it through `super::model::`.
    let rtq = format!("super::model::{rt}");
    let aliased = ctx
        .schema
        .types
        .get(sel)
        .unwrap_or_else(|| panic!("gen-early: select `{sel}` not a type alias"))
        .aliased
        .clone();
    let members = select_members(aliased.trim())
        .unwrap_or_else(|| panic!("gen-early: select `{sel}` not a SELECT"));
    // (member name, L1 variant, member kind)
    let mems: Vec<(&str, String, Kind)> = members
        .iter()
        .map(|&m| {
            let v =
                hint.variants.get(m).cloned().unwrap_or_else(|| {
                    panic!("gen-early: [select.{sel}] missing variant for `{m}`")
                });
            (m, v, ctx.classify(m, 0))
        })
        .collect();
    let count = |pred: fn(&Kind) -> bool| mems.iter().filter(|(_, _, k)| pred(k)).count();
    assert!(
        count(|k| matches!(k, Kind::Ref)) <= 1,
        "gen-early: select `{sel}` has >1 entity member (cannot disambiguate refs)"
    );
    assert!(
        count(|k| matches!(k, Kind::Enum(_))) <= 1,
        "gen-early: select `{sel}` has >1 enum member (cannot disambiguate bare enums)"
    );
    let payload = |k: &Kind| -> String {
        match k {
            Kind::Ref => "u64".into(),
            Kind::Real => "f64".into(),
            Kind::Str => "String".into(),
            Kind::Enum(a) => ctx.enum_hint(a).rust_type.clone(),
            _ => panic!("gen-early: select `{sel}` member kind unsupported"),
        }
    };

    // model enum
    writeln!(model, "/// L1 mixed SELECT `{sel}` (generated).").unwrap();
    writeln!(model, "#[derive(Debug, Clone, PartialEq)]").unwrap();
    writeln!(model, "pub(crate) enum {rt} {{").unwrap();
    for (_, v, k) in &mems {
        writeln!(model, "    {v}({}),", payload(k)).unwrap();
    }
    writeln!(model, "}}\n").unwrap();

    hinted_select_bind(ctx, sel, &rtq, &mems, bind, token_enums);

    hinted_select_emit(sel, &rtq, &mems, serialize);
}

/// Emit a synthesized `Early*` enum + `bind_<sel>` / `<sel>_emit` for a
/// **hint-less** mixed SELECT (no `[select.*]`). Variant = `pascal(member)`,
/// member kind = [`Ctx::classify`]. Supported members: entity (≤1, bare `#N`),
/// scalar (real/int/str/bool), and hint-less ENUM (synth enum, token map inlined
/// so no `from_token` helper). Deferred shapes panic loudly (none reached by the
/// current generate-list): ≥2 entity (combined-ref), aggregation member, nested
/// mixed SELECT, or a hinted ENUM member.
pub(crate) fn emit_select_synth(
    ctx: &Ctx,
    sel: &str,
    model: &mut String,
    bind: &mut String,
    serialize: &mut String,
    emitted_models: &mut BTreeSet<String>,
    emitted_selects: &mut BTreeSet<String>,
) {
    // Dedup across the `used_selects` loop and recursive nested-select emission.
    if !emitted_selects.insert(sel.to_string()) {
        return;
    }
    let rt = format!("Early{}", pascal(sel));
    let rtq = format!("super::model::{rt}");
    let aliased = ctx
        .schema
        .types
        .get(sel)
        .unwrap_or_else(|| panic!("gen-early: select `{sel}` not a type alias"))
        .aliased
        .clone();
    let members = select_members(aliased.trim())
        .unwrap_or_else(|| panic!("gen-early: select `{sel}` not a SELECT"));
    // (member name, L1 variant, member kind)
    let mems: Vec<(&str, String, Kind)> = members
        .iter()
        .map(|&m| (m, pascal(m), ctx.classify(m, 0)))
        .collect();

    // Entity members can't be told apart from a bare `#N` at bind time, so all
    // of them collapse into one combined `EntityRef(u64)` variant; `lower`
    // resolves the actual entity type. (Scalar / enum members stay per-variant.)
    let has_ref = mems.iter().any(|(_, _, k)| matches!(k, Kind::Ref));
    // Aggregation members arrive as typed parameters `TAG((...))` per Part21
    // (e.g. `COMMON_DATUM_LIST((#1,#2))`, mirroring the hand-written reader in
    // src/entities/pmi.rs), so each keeps its own variant — only non-scalar
    // inners are deferred.
    for (m, _, k) in &mems {
        match k {
            Kind::Vec(inner)
                if matches!(**inner, Kind::Ref | Kind::Real | Kind::Int | Kind::Str) => {}
            // Aggregation of a supported mixed select (elements decode via
            // `bind_<inner>`, e.g. `maths_tuple` = `LIST OF maths_value`).
            Kind::Vec(inner) if matches!(&**inner, Kind::Select(s) if ctx.select_supported(s)) => {}
            Kind::Vec(_) => {
                panic!("gen-early: select `{sel}` member `{m}` is a non-scalar aggregation (v4.x)")
            }
            // Typed-only nested select: decoded by delegating to `bind_<nested>`.
            Kind::Select(nested) if ctx.select_typed_only(nested) => {}
            Kind::Select(_) => {
                panic!("gen-early: select `{sel}` member `{m}` is a nested mixed select (v4.x)")
            }
            Kind::Enum(a) if ctx.mapping.enums.contains_key(a) => panic!(
                "gen-early: select `{sel}` member `{m}` is a hinted enum in a hint-less select (v4.x)"
            ),
            _ => {}
        }
    }

    let payload = |k: &Kind| -> String {
        match k {
            Kind::Ref => "u64".into(),
            Kind::Real => "f64".into(),
            Kind::Int => "i64".into(),
            Kind::Bool => "bool".into(),
            // binary carries its hex digits verbatim, as a String.
            Kind::Str | Kind::Binary => "String".into(),
            Kind::Logical => "crate::ir::geometry::Logical".into(),
            // Synth ENUM / Typed-only nested select -> its own `Early*` type.
            Kind::Enum(a) | Kind::Select(a) => format!("super::model::Early{}", pascal(a)),
            // Typed aggregation member -> Vec of its (scalar/ref) inner.
            Kind::Vec(_) => field_ty(ctx, k),
        }
    };

    // synth enum models for ENUM members (deduped across selects / fields).
    for (_, _, k) in &mems {
        if let Kind::Enum(a) = k {
            write_synth_enum_model(ctx, a, model, emitted_models);
        }
    }
    // Recursively emit the nested SELECT members' own model/bind/serialize so
    // `bind_<nested>` / `<nested>_emit` exist — both direct nested members and
    // aggregation inners (`Vec<Select>`). Self-references (e.g. `maths_tuple` =
    // `LIST OF maths_value` inside `maths_value`) are deduped by the
    // `emitted_selects` entry guard.
    for (_, _, k) in &mems {
        let nested = match k {
            Kind::Select(nested) => Some(nested),
            Kind::Vec(inner) => match &**inner {
                Kind::Select(nested) => Some(nested),
                _ => None,
            },
            _ => None,
        };
        if let Some(nested) = nested {
            emit_select_synth(
                ctx,
                nested,
                model,
                bind,
                serialize,
                emitted_models,
                emitted_selects,
            );
        }
    }

    // model enum
    writeln!(model, "/// L1 mixed SELECT `{sel}` (generated, hint-less).").unwrap();
    writeln!(model, "#[derive(Debug, Clone, PartialEq)]").unwrap();
    writeln!(model, "pub(crate) enum {rt} {{").unwrap();
    if has_ref {
        writeln!(model, "    EntityRef(u64),").unwrap();
    }
    for (_, v, k) in &mems {
        if matches!(k, Kind::Ref) {
            continue; // collapsed into the combined `EntityRef` variant above.
        }
        writeln!(model, "    {v}({}),", payload(k)).unwrap();
    }
    writeln!(model, "}}\n").unwrap();

    synth_select_bind(ctx, sel, &rtq, &mems, has_ref, bind);

    synth_select_emit(ctx, sel, &rtq, &mems, has_ref, serialize);
}

/// `bind_<entity>` fn for one entity (split from [`emit_entity`]).
fn entity_bind(
    ent_name: &str,
    type_name: &str,
    step_name: &str,
    attrs: &[(String, Kind, bool, bool)],
    has_select: bool,
    out: &mut GenOut,
) {
    // bind fn. A `Select` field drops the whole entity on `None`, so when one
    // is present the return type is `Result<Option<…>>` and binding uses a
    // let-form with early `return Ok(None)`; otherwise the simple literal form.
    let ret = if has_select {
        format!("Result<Option<super::model::{type_name}>, crate::ir::error::ConvertError>")
    } else {
        format!("Result<super::model::{type_name}, crate::ir::error::ConvertError>")
    };
    writeln!(
        out.bind,
        "pub(crate) fn bind_{ent_name}(entity_id: u64, attrs: &[crate::parser::entity::Attribute]) -> {ret} {{"
    )
    .unwrap();
    writeln!(
        out.bind,
        "    crate::ir::attr::check_count(attrs, {}, entity_id, \"{step_name}\")?;",
        attrs.len()
    )
    .unwrap();
    if has_select {
        for (i, (field, k, opt, derived)) in attrs.iter().enumerate() {
            if *derived {
                continue; // Derived (`*`) slot: skipped, but `i` keeps the Part21 index.
            }
            match (k, opt) {
                // Optional SELECT: `$`/`*` -> None (entity survives); a present
                // but unrecognized form -> drop the whole entity (preserving
                // the required-select behavior for malformed input).
                (Kind::Select(sel), true) => {
                    writeln!(out.bind, "    let {field} = match &attrs[{i}] {{").unwrap();
                    writeln!(
                        out.bind,
                        "        crate::parser::entity::Attribute::Unset | crate::parser::entity::Attribute::Derived => None,"
                    )
                    .unwrap();
                    writeln!(
                        out.bind,
                        "        _ => match bind_{sel}(&attrs[{i}]) {{ Some(v) => Some(v), None => return Ok(None) }},"
                    )
                    .unwrap();
                    writeln!(out.bind, "    }};").unwrap();
                }
                // Required SELECT: drop the whole entity on an unrecognized form.
                (Kind::Select(sel), false) => {
                    writeln!(
                        out.bind,
                        "    let Some({field}) = bind_{sel}(&attrs[{i}]) else {{ return Ok(None); }};"
                    )
                    .unwrap();
                }
                _ => {
                    writeln!(
                        out.bind,
                        "    let {field} = {};",
                        bind_expr_full(k, i, field, *opt)
                    )
                    .unwrap();
                }
            }
        }
        writeln!(out.bind, "    Ok(Some(super::model::{type_name} {{").unwrap();
        for (field, _, _, derived) in attrs {
            if *derived {
                continue;
            }
            writeln!(out.bind, "        {field},").unwrap();
        }
        writeln!(out.bind, "    }}))\n}}\n").unwrap();
    } else {
        writeln!(out.bind, "    Ok(super::model::{type_name} {{").unwrap();
        for (i, (field, k, opt, derived)) in attrs.iter().enumerate() {
            if *derived {
                continue; // Derived (`*`) slot: no field; `i` keeps the Part21 index.
            }
            writeln!(
                out.bind,
                "        {field}: {},",
                bind_expr_full(k, i, field, *opt)
            )
            .unwrap();
        }
        writeln!(out.bind, "    }})\n}}\n").unwrap();
    }
}

/// `serialize_<entity>` fn + helper-usage tracking (split from [`emit_entity`]).
/// Entities listed in mapping `serialize_with_id` additionally get a
/// `serialize_<entity>_with_id` variant emitting under a pre-reserved id
/// (the writer's reserve-then-fill pattern).
fn entity_serialize(
    ctx: &Ctx,
    ent_name: &str,
    type_name: &str,
    step_name: &str,
    attrs: &[(String, Kind, bool, bool)],
    out: &mut GenOut,
) {
    // Attr expressions are shared between the plain and with_id variants.
    let mut attr_lines = String::new();
    // `l1` is read only by non-derived attr expressions; a 0-attr (or
    // all-derived) entity never touches it, so bind the param as `_l1` to
    // avoid an unused-variable warning.
    let l1_param = if attrs.iter().any(|(_, _, _, derived)| !derived) {
        "l1"
    } else {
        "_l1"
    };
    // serialize fn
    writeln!(
        out.serialize,
        "pub(crate) fn serialize_{ent_name}(buf: &mut crate::writer::buffer::WriteBuffer, {l1_param}: &super::model::{type_name}) -> u64 {{"
    )
    .unwrap();
    writeln!(out.serialize, "    buf.push_simple(\"{step_name}\", vec![").unwrap();
    for (field, k, opt, derived) in attrs {
        let line = if *derived {
            // Derived (`*`) slot: emit the Part21 omitted-attribute marker.
            "        crate::parser::entity::Attribute::Derived,".to_string()
        } else {
            format!("        {},", serialize_expr_full(k, field, *opt))
        };
        writeln!(out.serialize, "{line}").unwrap();
        attr_lines.push_str(&line);
        attr_lines.push('\n');
        if *derived {
            continue; // no helper-usage tracking for a `*` slot.
        }
        track_serialize_usage(k, out);
    }
    writeln!(out.serialize, "    ])\n}}\n").unwrap();

    if ctx.mapping.serialize_with_id.iter().any(|e| e == ent_name) {
        writeln!(
            out.serialize,
            "pub(crate) fn serialize_{ent_name}_with_id(buf: &mut crate::writer::buffer::WriteBuffer, id: u64, {l1_param}: &super::model::{type_name}) {{"
        )
        .unwrap();
        writeln!(
            out.serialize,
            "    buf.push_simple_with_id(id, \"{step_name}\", vec![\n{attr_lines}    ]);\n}}\n"
        )
        .unwrap();
    }
}

/// `bind_<sel>` for a hinted mixed SELECT (split from [`emit_select`]).
fn hinted_select_bind(
    ctx: &Ctx,
    sel: &str,
    rtq: &str,
    mems: &[(&str, String, Kind)],
    bind: &mut String,
    token_enums: &mut BTreeSet<String>,
) {
    // bind_<sel>
    if mems.iter().any(|(_, _, k)| matches!(k, Kind::Real)) {
        writeln!(bind, "#[allow(clippy::cast_precision_loss)]").unwrap();
    }
    writeln!(
        bind,
        "fn bind_{sel}(attr: &crate::parser::entity::Attribute) -> Option<{rtq}> {{"
    )
    .unwrap();
    writeln!(bind, "    match attr {{").unwrap();
    for (_, v, k) in mems {
        if matches!(k, Kind::Ref) {
            writeln!(
                bind,
                "        crate::parser::entity::Attribute::EntityRef(n) => Some({rtq}::{v}(*n)),"
            )
            .unwrap();
        }
    }
    if mems
        .iter()
        .any(|(_, _, k)| matches!(k, Kind::Enum(_) | Kind::Real | Kind::Str))
    {
        writeln!(
            bind,
            "        crate::parser::entity::Attribute::Typed {{ type_name, value }} => match (type_name.as_str(), value.as_ref()) {{"
        )
        .unwrap();
        for (m, v, k) in mems {
            let tag = m.to_uppercase();
            match k {
                Kind::Enum(a) => {
                    token_enums.insert(a.clone());
                    // Strict (no catch_all) token-enums return `Option`; a
                    // non-standard token → `None` → the SELECT drops the member.
                    if ctx.enum_hint(a).catch_all.is_some() {
                        writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::Enum(t)) => Some({rtq}::{v}({a}_from_token(t))),").unwrap();
                    } else {
                        writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::Enum(t)) => {a}_from_token(t).map({rtq}::{v}),").unwrap();
                    }
                }
                Kind::Real => {
                    writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::Real(x)) => Some({rtq}::{v}(*x)),").unwrap();
                    writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::Integer(x)) => Some({rtq}::{v}(*x as f64)),").unwrap();
                }
                Kind::Str => {
                    writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::String(s)) => Some({rtq}::{v}(s.clone())),").unwrap();
                }
                _ => {}
            }
        }
        writeln!(bind, "            _ => None,").unwrap();
        writeln!(bind, "        }},").unwrap();
    }
    for (_, v, k) in mems {
        if let Kind::Enum(a) = k {
            if ctx.enum_hint(a).catch_all.is_some() {
                writeln!(
                    bind,
                    "        crate::parser::entity::Attribute::Enum(t) => Some({rtq}::{v}({a}_from_token(t))),"
                )
                .unwrap();
            } else {
                writeln!(
                    bind,
                    "        crate::parser::entity::Attribute::Enum(t) => {a}_from_token(t).map({rtq}::{v}),"
                )
                .unwrap();
            }
        }
    }
    writeln!(bind, "        _ => None,").unwrap();
    writeln!(bind, "    }}\n}}\n").unwrap();
}

/// `<sel>_emit` for a hinted mixed SELECT (split from [`emit_select`]).
fn hinted_select_emit(sel: &str, rtq: &str, mems: &[(&str, String, Kind)], serialize: &mut String) {
    // <sel>_emit
    writeln!(
        serialize,
        "fn {sel}_emit(v: &{rtq}) -> crate::parser::entity::Attribute {{"
    )
    .unwrap();
    writeln!(serialize, "    match v {{").unwrap();
    for (m, v, k) in mems {
        let tag = m.to_uppercase();
        let arm = match k {
            Kind::Ref => {
                format!("{rtq}::{v}(step) => crate::parser::entity::Attribute::EntityRef(*step),")
            }
            Kind::Enum(a) => format!(
                "{rtq}::{v}(t) => crate::parser::entity::Attribute::Typed {{ type_name: \"{tag}\".into(), value: Box::new(crate::parser::entity::Attribute::Enum({a}_to_token(t))) }},"
            ),
            Kind::Real => format!(
                "{rtq}::{v}(x) => crate::parser::entity::Attribute::Typed {{ type_name: \"{tag}\".into(), value: Box::new(crate::parser::entity::Attribute::Real(*x)) }},"
            ),
            Kind::Str => format!(
                "{rtq}::{v}(s) => crate::parser::entity::Attribute::Typed {{ type_name: \"{tag}\".into(), value: Box::new(crate::parser::entity::Attribute::String(s.clone())) }},"
            ),
            _ => panic!("gen-early: select `{sel}` member kind unsupported"),
        };
        writeln!(serialize, "        {arm}").unwrap();
    }
    writeln!(serialize, "    }}\n}}\n").unwrap();
}

/// `bind_<sel>` for a synthesized mixed SELECT (split from [`emit_select_synth`]).
fn synth_select_bind(
    ctx: &Ctx,
    sel: &str,
    rtq: &str,
    mems: &[(&str, String, Kind)],
    has_ref: bool,
    bind: &mut String,
) {
    // bind_<sel>
    let needs_cast = mems.iter().any(|(_, _, k)| {
        matches!(k, Kind::Real) || matches!(k, Kind::Vec(i) if matches!(**i, Kind::Real))
    });
    if needs_cast {
        writeln!(bind, "#[allow(clippy::cast_precision_loss)]").unwrap();
    }
    writeln!(
        bind,
        "fn bind_{sel}(attr: &crate::parser::entity::Attribute) -> Option<{rtq}> {{"
    )
    .unwrap();
    writeln!(bind, "    match attr {{").unwrap();
    if has_ref {
        // All entity members share this one arm; `lower` resolves the type.
        writeln!(
            bind,
            "        crate::parser::entity::Attribute::EntityRef(n) => Some({rtq}::EntityRef(*n)),"
        )
        .unwrap();
    }
    if mems.iter().any(|(_, _, k)| {
        matches!(
            k,
            Kind::Real
                | Kind::Int
                | Kind::Str
                | Kind::Bool
                | Kind::Logical
                | Kind::Binary
                | Kind::Enum(_)
                | Kind::Select(_)
                | Kind::Vec(_)
        )
    }) {
        writeln!(
            bind,
            "        crate::parser::entity::Attribute::Typed {{ type_name, value }} => match (type_name.as_str(), value.as_ref()) {{"
        )
        .unwrap();
        synth_bind_typed_arms(ctx, rtq, mems, bind);
        // Typed-only nested select members: tags belong to the nested select, so
        // the outer match can't enumerate them — delegate the whole `attr` to
        // `bind_<nested>` (the `_ =>` arm). Selects with no nested member keep the
        // plain `_ => None` (byte-identical to pre-v4.18).
        if mems.iter().any(|(_, _, k)| matches!(k, Kind::Select(_))) {
            writeln!(bind, "            _ => {{").unwrap();
            for (_, v, k) in mems {
                if let Kind::Select(nested) = k {
                    writeln!(bind, "                if let Some(x) = bind_{nested}(attr) {{ return Some({rtq}::{v}(x)); }}").unwrap();
                }
            }
            writeln!(bind, "                None").unwrap();
            writeln!(bind, "            }},").unwrap();
        } else {
            writeln!(bind, "            _ => None,").unwrap();
        }
        writeln!(bind, "        }},").unwrap();
    }
    writeln!(bind, "        _ => None,").unwrap();
    writeln!(bind, "    }}\n}}\n").unwrap();
}

/// The per-member `("TAG", ..) => ..` arms of the Typed block (split from
/// [`synth_select_bind`]).
fn synth_bind_typed_arms(ctx: &Ctx, rtq: &str, mems: &[(&str, String, Kind)], bind: &mut String) {
    for (m, v, k) in mems {
        let tag = m.to_uppercase();
        match k {
            Kind::Real => {
                writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::Real(x)) => Some({rtq}::{v}(*x)),").unwrap();
                writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::Integer(x)) => Some({rtq}::{v}(*x as f64)),").unwrap();
            }
            Kind::Int => {
                writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::Integer(x)) => Some({rtq}::{v}(*x)),").unwrap();
            }
            Kind::Str => {
                writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::String(s)) => Some({rtq}::{v}(s.clone())),").unwrap();
            }
            Kind::Bool => {
                writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::Enum(t)) => Some({rtq}::{v}(t.as_str() == \"T\")),").unwrap();
            }
            Kind::Binary => {
                writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::Binary(s)) => Some({rtq}::{v}(s.clone())),").unwrap();
            }
            Kind::Logical => {
                writeln!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::Enum(t)) => Some({rtq}::{v}(match t.as_str() {{ \"T\" => crate::ir::geometry::Logical::True, \"F\" => crate::ir::geometry::Logical::False, _ => crate::ir::geometry::Logical::Unknown }})),").unwrap();
            }
            // Typed aggregation member `TAG((...))`: decode each element by
            // the (scalar/ref) inner kind; a mismatched element drops the value.
            Kind::Vec(inner) => {
                writeln!(
                    bind,
                    "            (\"{tag}\", crate::parser::entity::Attribute::List(items)) => {{"
                )
                .unwrap();
                writeln!(
                    bind,
                    "                let mut out = Vec::with_capacity(items.len());"
                )
                .unwrap();
                writeln!(bind, "                for it in items {{").unwrap();
                writeln!(bind, "                    match it {{").unwrap();
                match &**inner {
                    Kind::Ref => {
                        writeln!(bind, "                        crate::parser::entity::Attribute::EntityRef(n) => out.push(*n),").unwrap();
                    }
                    Kind::Real => {
                        writeln!(bind, "                        crate::parser::entity::Attribute::Real(x) => out.push(*x),").unwrap();
                        writeln!(bind, "                        crate::parser::entity::Attribute::Integer(x) => out.push(*x as f64),").unwrap();
                    }
                    Kind::Int => {
                        writeln!(bind, "                        crate::parser::entity::Attribute::Integer(x) => out.push(*x),").unwrap();
                    }
                    Kind::Str => {
                        writeln!(bind, "                        crate::parser::entity::Attribute::String(s) => out.push(s.clone()),").unwrap();
                    }
                    // mixed-select inner: each element is a full select
                    // value, decoded by its own (possibly self-recursive)
                    // `bind_<inner>`.
                    Kind::Select(inner_sel) => {
                        writeln!(
                            bind,
                            "                        it => match bind_{inner_sel}(it) {{"
                        )
                        .unwrap();
                        writeln!(bind, "                            Some(x) => out.push(x),")
                            .unwrap();
                        writeln!(bind, "                            None => return None,").unwrap();
                        writeln!(bind, "                        }},").unwrap();
                    }
                    _ => unreachable!("agg inners are restricted to ref/scalar/select"),
                }
                // the select-inner arm above is irrefutable; only the
                // scalar/ref inners need the explicit mismatch arm.
                if !matches!(&**inner, Kind::Select(_)) {
                    writeln!(bind, "                        _ => return None,").unwrap();
                }
                writeln!(bind, "                    }}").unwrap();
                writeln!(bind, "                }}").unwrap();
                writeln!(bind, "                Some({rtq}::{v}(out))").unwrap();
                writeln!(bind, "            }}").unwrap();
            }
            Kind::Enum(a) => {
                let etype = format!("super::model::Early{}", pascal(a));
                write!(bind, "            (\"{tag}\", crate::parser::entity::Attribute::Enum(t)) => match t.as_str() {{").unwrap();
                for (etag, evar) in synth_enum_members(ctx, a) {
                    write!(bind, " \"{etag}\" => Some({rtq}::{v}({etype}::{evar})),").unwrap();
                }
                writeln!(bind, " _ => None }},").unwrap();
            }
            _ => {}
        }
    }
}

/// `<sel>_emit` for a synthesized mixed SELECT (split from [`emit_select_synth`]).
fn synth_select_emit(
    ctx: &Ctx,
    sel: &str,
    rtq: &str,
    mems: &[(&str, String, Kind)],
    has_ref: bool,
    serialize: &mut String,
) {
    // <sel>_emit
    writeln!(
        serialize,
        "fn {sel}_emit(v: &{rtq}) -> crate::parser::entity::Attribute {{"
    )
    .unwrap();
    writeln!(serialize, "    match v {{").unwrap();
    if has_ref {
        // The combined entity-ref variant emits the bare `#N` back.
        writeln!(
            serialize,
            "        {rtq}::EntityRef(step) => crate::parser::entity::Attribute::EntityRef(*step),"
        )
        .unwrap();
    }
    for (m, v, k) in mems {
        if matches!(k, Kind::Ref) {
            continue; // handled by the combined `EntityRef` arm above.
        }
        let tag = m.to_uppercase();
        let arm = match k {
            Kind::Real => format!(
                "{rtq}::{v}(x) => crate::parser::entity::Attribute::Typed {{ type_name: \"{tag}\".into(), value: Box::new(crate::parser::entity::Attribute::Real(*x)) }},"
            ),
            Kind::Int => format!(
                "{rtq}::{v}(x) => crate::parser::entity::Attribute::Typed {{ type_name: \"{tag}\".into(), value: Box::new(crate::parser::entity::Attribute::Integer(*x)) }},"
            ),
            Kind::Str => format!(
                "{rtq}::{v}(s) => crate::parser::entity::Attribute::Typed {{ type_name: \"{tag}\".into(), value: Box::new(crate::parser::entity::Attribute::String(s.clone())) }},"
            ),
            Kind::Bool => format!(
                "{rtq}::{v}(b) => crate::parser::entity::Attribute::Typed {{ type_name: \"{tag}\".into(), value: Box::new(crate::parser::entity::Attribute::Enum(if *b {{ \"T\" }} else {{ \"F\" }}.into())) }},"
            ),
            Kind::Binary => format!(
                "{rtq}::{v}(s) => crate::parser::entity::Attribute::Typed {{ type_name: \"{tag}\".into(), value: Box::new(crate::parser::entity::Attribute::Binary(s.clone())) }},"
            ),
            Kind::Logical => format!(
                "{rtq}::{v}(l) => crate::parser::entity::Attribute::Typed {{ type_name: \"{tag}\".into(), value: Box::new(crate::parser::entity::Attribute::Enum(crate::ir::attr::logical_to_step(*l).into())) }},"
            ),
            Kind::Enum(a) => {
                let etype = format!("super::model::Early{}", pascal(a));
                let mut arms = String::new();
                for (etag, evar) in synth_enum_members(ctx, a) {
                    write!(arms, " {etype}::{evar} => \"{etag}\",").unwrap();
                }
                format!(
                    "{rtq}::{v}(e) => crate::parser::entity::Attribute::Typed {{ type_name: \"{tag}\".into(), value: Box::new(crate::parser::entity::Attribute::Enum(match e {{{arms} }}.into())) }},"
                )
            }
            // Typed-only nested select: delegate to its `<nested>_emit`.
            Kind::Select(nested) => {
                format!("{rtq}::{v}(x) => {nested}_emit(x),")
            }
            // Typed aggregation member: emit `TAG((...))` back.
            Kind::Vec(inner) => {
                let elem = vec_elem_closure(inner);
                format!(
                    "{rtq}::{v}(xs) => crate::parser::entity::Attribute::Typed {{ type_name: \"{tag}\".into(), value: Box::new(crate::parser::entity::Attribute::List(xs.iter().map({elem}).collect())) }},"
                )
            }
            Kind::Ref => unreachable!("ref members are skipped above (combined EntityRef arm)"),
        };
        writeln!(serialize, "        {arm}").unwrap();
    }
    writeln!(serialize, "    }}\n}}\n").unwrap();
}

/// Emit token-based helpers (`<enum>_from_token` in bind, `<enum>_to_token` in
/// serialize) for a `catch_all` ENUM used as a SELECT member.
pub(crate) fn emit_token_enum(ctx: &Ctx, alias: &str, bind: &mut String, serialize: &mut String) {
    let h = ctx.enum_hint(alias);
    let rt = &h.rust_type;
    // With `catch_all`, an unknown token is preserved verbatim (`_from_token`
    // is infallible). Without it, the enum is strict: `_from_token` returns
    // `Option` (`None` = non-standard token) and the SELECT bind drops the
    // member — the owning handler surfaces the drop as NORM.
    if let Some(catch) = h.catch_all.as_ref() {
        writeln!(bind, "fn {alias}_from_token(t: &str) -> {rt} {{").unwrap();
        writeln!(bind, "    match t {{").unwrap();
        for (member, variant) in &h.variants {
            writeln!(
                bind,
                "        \"{}\" => {rt}::{variant},",
                member.to_uppercase()
            )
            .unwrap();
        }
        writeln!(bind, "        other => {rt}::{catch}(other.to_owned()),").unwrap();
        writeln!(bind, "    }}\n}}\n").unwrap();
    } else {
        writeln!(bind, "fn {alias}_from_token(t: &str) -> Option<{rt}> {{").unwrap();
        writeln!(bind, "    match t {{").unwrap();
        for (member, variant) in &h.variants {
            writeln!(
                bind,
                "        \"{}\" => Some({rt}::{variant}),",
                member.to_uppercase()
            )
            .unwrap();
        }
        writeln!(bind, "        _ => None,").unwrap();
        writeln!(bind, "    }}\n}}\n").unwrap();
    }

    writeln!(serialize, "fn {alias}_to_token(v: &{rt}) -> String {{").unwrap();
    writeln!(serialize, "    match v {{").unwrap();
    for (member, variant) in &h.variants {
        writeln!(
            serialize,
            "        {rt}::{variant} => \"{}\".into(),",
            member.to_uppercase()
        )
        .unwrap();
    }
    if let Some(catch) = h.catch_all.as_ref() {
        writeln!(serialize, "        {rt}::{catch}(s) => s.clone(),").unwrap();
    }
    writeln!(serialize, "    }}\n}}\n").unwrap();
}

/// Resolve a hint-less ENUM alias to its `(STEP token, Rust variant)` members.
pub(crate) fn synth_enum_members(ctx: &Ctx, alias: &str) -> Vec<(String, String)> {
    let aliased = ctx
        .schema
        .types
        .get(alias)
        .unwrap_or_else(|| panic!("gen-early: enum `{alias}` not a type alias"))
        .aliased
        .clone();
    enum_members(aliased.trim())
        .unwrap_or_else(|| panic!("gen-early: enum `{alias}` not an ENUM"))
        .iter()
        .map(|m| (m.to_uppercase(), pascal(m)))
        .collect()
}

/// Emit the synthesized `Early*` enum *model definition* once (deduped via
/// `emitted_models`). Shared by standalone-field ENUMs and hint-less SELECT
/// members so a model used both ways is defined exactly once.
pub(crate) fn write_synth_enum_model(
    ctx: &Ctx,
    alias: &str,
    model: &mut String,
    emitted_models: &mut BTreeSet<String>,
) {
    if !emitted_models.insert(alias.to_string()) {
        return;
    }
    let rt = format!("Early{}", pascal(alias));
    // Fieldless (unit variants) -> `Copy`, so the by-value `<alias>_attr`
    // serialize helper compiles for non-trivial entities too.
    writeln!(model, "/// L1 ENUM `{alias}` (generated).").unwrap();
    writeln!(model, "#[derive(Debug, Clone, Copy, PartialEq)]").unwrap();
    writeln!(model, "pub(crate) enum {rt} {{").unwrap();
    for (_, v) in synth_enum_members(ctx, alias) {
        writeln!(model, "    {v},").unwrap();
    }
    writeln!(model, "}}\n").unwrap();
}

/// Emit a synthesized `Early*` enum (model def + `bind_<alias>` / `<alias>_attr`)
/// for a hint-less standalone-field ENUM. Variant = `pascal(member)`, STEP token
/// = `member.to_uppercase()`. Strict: an unknown token errors (EXPRESS ENUMs are
/// closed). Mirrors the hinted path but with a generated type instead of L2 reuse.
pub(crate) fn emit_synth_enum(
    ctx: &Ctx,
    alias: &str,
    model: &mut String,
    bind: &mut String,
    serialize: &mut String,
    emitted_models: &mut BTreeSet<String>,
) {
    let rt = format!("Early{}", pascal(alias));
    let mems = synth_enum_members(ctx, alias);
    write_synth_enum_model(ctx, alias, model, emitted_models);

    // bind helper
    writeln!(
        bind,
        "fn bind_{alias}(attrs: &[crate::parser::entity::Attribute], index: usize, entity_id: u64, field: &'static str) -> Result<super::model::{rt}, crate::ir::error::ConvertError> {{"
    )
    .unwrap();
    writeln!(
        bind,
        "    match crate::ir::attr::read_enum(attrs, index, entity_id, field)? {{"
    )
    .unwrap();
    for (tag, v) in &mems {
        writeln!(bind, "        \"{tag}\" => Ok(super::model::{rt}::{v}),").unwrap();
    }
    writeln!(
        bind,
        "        other => Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: format!(\"{{field}}: unknown {alias} '.{{other}}.'\") }}),"
    )
    .unwrap();
    writeln!(bind, "    }}\n}}\n").unwrap();

    // serialize helper
    writeln!(
        serialize,
        "fn {alias}_attr(v: super::model::{rt}) -> crate::parser::entity::Attribute {{"
    )
    .unwrap();
    writeln!(
        serialize,
        "    crate::parser::entity::Attribute::Enum(match v {{"
    )
    .unwrap();
    for (tag, v) in &mems {
        writeln!(serialize, "        super::model::{rt}::{v} => \"{tag}\",").unwrap();
    }
    writeln!(serialize, "    }}.into())\n}}\n").unwrap();
}

/// Emit `<alias>_list(attrs, index, ..) -> Result<Vec<EnumType>>` for an ENUM
/// used inside a `Vec<…>`: reads the `List`, decoding each `Enum` element to a
/// variant (mirrors the standalone bind decode, per element). Works for hinted
/// (L2 reuse, with default) and hint-less (synth `Early*`, strict) enums.
pub(crate) fn emit_enum_list(ctx: &Ctx, alias: &str, bind: &mut String) {
    let (et, pairs, default): (String, Vec<(String, String)>, Option<String>) =
        match ctx.mapping.enums.get(alias) {
            Some(h) => (
                h.rust_type.clone(),
                h.variants
                    .iter()
                    .map(|(m, v)| (m.to_uppercase(), v.clone()))
                    .collect(),
                h.default.clone(),
            ),
            None => (
                format!("super::model::Early{}", pascal(alias)),
                synth_enum_members(ctx, alias),
                None,
            ),
        };
    writeln!(
        bind,
        "fn {alias}_list(attrs: &[crate::parser::entity::Attribute], index: usize, entity_id: u64, field: &'static str) -> Result<Vec<{et}>, crate::ir::error::ConvertError> {{"
    )
    .unwrap();
    writeln!(
        bind,
        "    let Some(crate::parser::entity::Attribute::List(items)) = attrs.get(index) else {{ return Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: format!(\"{{field}}: expected list\") }}); }};"
    )
    .unwrap();
    writeln!(bind, "    let mut out = Vec::with_capacity(items.len());").unwrap();
    writeln!(bind, "    for item in items {{").unwrap();
    writeln!(
        bind,
        "        let crate::parser::entity::Attribute::Enum(t) = item else {{ return Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: format!(\"{{field}}: expected enum in list\") }}); }};"
    )
    .unwrap();
    writeln!(bind, "        out.push(match t.as_str() {{").unwrap();
    for (tok, var) in &pairs {
        if default.as_ref() == Some(var) {
            continue; // covered by the catch-all below (avoids match_same_arms)
        }
        writeln!(bind, "            \"{tok}\" => {et}::{var},").unwrap();
    }
    if let Some(d) = &default {
        writeln!(bind, "            _ => {et}::{d},").unwrap();
    } else {
        writeln!(
            bind,
            "            other => return Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: format!(\"{{field}}: unknown {alias} '.{{other}}.'\") }}),"
        )
        .unwrap();
    }
    writeln!(bind, "        }});").unwrap();
    writeln!(bind, "    }}").unwrap();
    writeln!(bind, "    Ok(out)\n}}\n").unwrap();
}

/// Emit `<alias>_list(attrs, index, ..) -> Result<Vec<SelectType>>` for a SELECT
/// used inside a `Vec<…>`: reads the `List`, decoding each element via the
/// standalone `bind_<alias>` (which returns `Option`); an unrecognized element
/// errors. Mirrors [`emit_enum_list`] but for selects.
pub(crate) fn emit_select_list(ctx: &Ctx, alias: &str, bind: &mut String) {
    // The hinted `rust_type` is a synthesized `Early*` enum living in
    // `generated/model.rs`; qualify it for the `generated/bind.rs` scope (matching
    // the standalone `bind_<alias>` and the hintless `None` branch).
    let st = match ctx.mapping.selects.get(alias) {
        Some(h) => format!("super::model::{}", h.rust_type),
        None => format!("super::model::Early{}", pascal(alias)),
    };
    writeln!(
        bind,
        "fn {alias}_list(attrs: &[crate::parser::entity::Attribute], index: usize, entity_id: u64, field: &'static str) -> Result<Vec<{st}>, crate::ir::error::ConvertError> {{"
    )
    .unwrap();
    writeln!(
        bind,
        "    let Some(crate::parser::entity::Attribute::List(items)) = attrs.get(index) else {{ return Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: format!(\"{{field}}: expected list\") }}); }};"
    )
    .unwrap();
    writeln!(bind, "    let mut out = Vec::with_capacity(items.len());").unwrap();
    writeln!(bind, "    for item in items {{").unwrap();
    writeln!(
        bind,
        "        match bind_{alias}(item) {{ Some(v) => out.push(v), None => return Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: format!(\"{{field}}: unrecognized {alias} in list\") }}) }}"
    )
    .unwrap();
    writeln!(bind, "    }}").unwrap();
    writeln!(bind, "    Ok(out)\n}}\n").unwrap();
}

/// Emit a `<alias>_grid(attrs, index, ..) -> Result<Vec<Vec<Early..>>>` bind
/// helper for a standalone 2-level aggregation whose inner is a mixed SELECT
/// (e.g. `SET OF LIST OF maths_value`): outer `List` of row `List`s, each
/// element decoded by `bind_<alias>` ([`emit_select_list`]'s grid analogue).
pub(crate) fn emit_select_grid(ctx: &Ctx, alias: &str, bind: &mut String) {
    let st = match ctx.mapping.selects.get(alias) {
        Some(h) => format!("super::model::{}", h.rust_type),
        None => format!("super::model::Early{}", pascal(alias)),
    };
    writeln!(
        bind,
        "fn {alias}_grid(attrs: &[crate::parser::entity::Attribute], index: usize, entity_id: u64, field: &'static str) -> Result<Vec<Vec<{st}>>, crate::ir::error::ConvertError> {{"
    )
    .unwrap();
    writeln!(
        bind,
        "    let Some(crate::parser::entity::Attribute::List(rows)) = attrs.get(index) else {{ return Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: format!(\"{{field}}: expected list\") }}); }};"
    )
    .unwrap();
    writeln!(bind, "    let mut grid = Vec::with_capacity(rows.len());").unwrap();
    writeln!(bind, "    for row in rows {{").unwrap();
    writeln!(
        bind,
        "        let crate::parser::entity::Attribute::List(items) = row else {{ return Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: format!(\"{{field}}: expected inner list\") }}); }};"
    )
    .unwrap();
    writeln!(
        bind,
        "        let mut out = Vec::with_capacity(items.len());"
    )
    .unwrap();
    writeln!(bind, "        for item in items {{").unwrap();
    writeln!(
        bind,
        "            match bind_{alias}(item) {{ Some(v) => out.push(v), None => return Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: format!(\"{{field}}: unrecognized {alias} in grid\") }}) }}"
    )
    .unwrap();
    writeln!(bind, "        }}").unwrap();
    writeln!(bind, "        grid.push(out);").unwrap();
    writeln!(bind, "    }}").unwrap();
    writeln!(bind, "    Ok(grid)\n}}\n").unwrap();
}

/// Emit the single `logical_list(attrs, index, ..) -> Result<Vec<Logical>>`
/// helper: reads the `List`, mapping each `Enum` element via the same lenient
/// `.T./.F./.U.` decode as `read_logical`.
pub(crate) fn emit_logical_list(bind: &mut String) {
    writeln!(
        bind,
        "fn logical_list(attrs: &[crate::parser::entity::Attribute], index: usize, entity_id: u64, field: &'static str) -> Result<Vec<crate::ir::geometry::Logical>, crate::ir::error::ConvertError> {{"
    )
    .unwrap();
    writeln!(
        bind,
        "    let Some(crate::parser::entity::Attribute::List(items)) = attrs.get(index) else {{ return Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: format!(\"{{field}}: expected list\") }}); }};"
    )
    .unwrap();
    writeln!(bind, "    let mut out = Vec::with_capacity(items.len());").unwrap();
    writeln!(bind, "    for item in items {{").unwrap();
    writeln!(
        bind,
        "        let crate::parser::entity::Attribute::Enum(t) = item else {{ return Err(crate::ir::error::ConvertError::UnexpectedEntityForm {{ entity_id, detail: format!(\"{{field}}: expected logical in list\") }}); }};"
    )
    .unwrap();
    writeln!(
        bind,
        "        out.push(match t.as_str() {{ \"T\" => crate::ir::geometry::Logical::True, \"F\" => crate::ir::geometry::Logical::False, _ => crate::ir::geometry::Logical::Unknown }});"
    )
    .unwrap();
    writeln!(bind, "    }}").unwrap();
    writeln!(bind, "    Ok(out)\n}}\n").unwrap();
}
#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::*;
    use crate::expr::{bind_expr, serialize_expr};
    use crate::schema::{EarlyToml, Entity, TypeDef};
    use crate::testutil::*;

    /// One entity through [`emit_entity`] (extraction made this testable —
    /// previously inline in `main`): model struct + `Early*Id` + `ArenaId` impl
    /// + bind/serialize fns land in `GenOut`.
    #[test]
    fn emit_entity_model_id_bind_serialize() {
        let ctx = ctx_from(schema());
        let mut out = GenOut::new("");
        emit_entity(&ctx, "point_style", &mut out);
        // model: the struct and its typed id-cache key.
        assert!(out.model.contains("pub(crate) struct EarlyPointStyle {"));
        assert!(
            out.model
                .contains("pub(crate) struct EarlyPointStyleId(pub u32);")
        );
        assert!(
            out.model
                .contains("impl crate::ir::arena::ArenaId for EarlyPointStyleId")
        );
        assert!(out.model.contains("fn from_index(index: u32) -> Self"));
        // bind / serialize fns.
        assert!(out.bind.contains("pub(crate) fn bind_point_style("));
        assert!(
            out.serialize
                .contains("pub(crate) fn serialize_point_style(")
        );
        // tracking: point_style uses the two hinted mixed selects.
        assert!(out.used_selects.contains("marker_select"));
        assert!(out.used_selects.contains("size_select"));
    }

    /// Multi-case complex (`cases`): enum L1 with per-case inner structs,
    /// part-presence-discriminated bind, per-variant serialize with case-specific
    /// derived. Exercises `emit_multi_case_complex` via `LENGTH_UNIT` (SI vs CBU).
    #[test]
    fn multi_case_complex_length_unit() {
        use crate::mapping::{CaseHint, ComplexHint};
        let mut ctx = ctx_from(schema());
        let mut cases = BTreeMap::new();
        cases.insert(
            "si".to_string(),
            CaseHint {
                parts: vec!["LENGTH_UNIT".into(), "NAMED_UNIT".into(), "SI_UNIT".into()],
                derived: vec!["dimensions".into()],
                discriminant: None,
                match_parts: None,
            },
        );
        cases.insert(
            "cbu".to_string(),
            CaseHint {
                parts: vec![
                    "CONVERSION_BASED_UNIT".into(),
                    "LENGTH_UNIT".into(),
                    "NAMED_UNIT".into(),
                ],
                derived: vec![],
                discriminant: Some("CONVERSION_BASED_UNIT".into()),
                match_parts: None,
            },
        );
        ctx.mapping.complex.insert(
            "length_unit".to_string(),
            ComplexHint {
                parts: None,
                cases: Some(cases),
            },
        );
        let mut out = GenOut::new("");
        emit_entity(&ctx, "length_unit", &mut out);
        // enum + per-case inner structs.
        assert!(out.model.contains("pub(crate) enum EarlyLengthUnit {"));
        assert!(out.model.contains("Si(EarlyLengthUnitSi)"));
        assert!(out.model.contains("Cbu(EarlyLengthUnitCbu)"));
        assert!(out.model.contains("pub(crate) struct EarlyLengthUnitCbu {"));
        assert!(out.model.contains("conversion_factor: u64"));
        // bind: part-presence discriminant.
        assert!(
            out.bind
                .contains("parts.iter().any(|p| p.name == \"CONVERSION_BASED_UNIT\")")
        );
        assert!(out.bind.contains("EarlyLengthUnit::Cbu"));
        assert!(out.bind.contains("EarlyLengthUnit::Si"));
        // serialize: per-variant match; SI dimensions = Derived, CBU = explicit ref.
        assert!(
            out.serialize
                .contains("super::model::EarlyLengthUnit::Si(l1) => buf.push_complex")
        );
        assert!(
            out.serialize
                .contains("crate::parser::entity::Attribute::Derived")
        );
        assert!(
            out.serialize
                .contains("super::model::EarlyLengthUnit::Cbu(l1) => buf.push_complex")
        );
    }

    /// Exact part-set dispatch (`match_parts`): the `DRAUGHTING_MODEL` A/B/C forms
    /// where A ⊂ B share a leading part so single-part discriminant can't
    /// separate them. Bind must use `part_set` length+membership equality, with
    /// distinct length guards (4 vs 6) so A and B never collide.
    #[test]
    fn multi_case_complex_exact_match() {
        use crate::mapping::{CaseHint, ComplexHint};
        let mut ctx = ctx_from(schema());
        let mk = |parts: Vec<&str>| CaseHint {
            parts: parts.iter().map(|s| (*s).to_string()).collect(),
            derived: vec![],
            discriminant: None,
            match_parts: Some(parts.iter().map(|s| (*s).to_string()).collect()),
        };
        let mut cases = BTreeMap::new();
        cases.insert(
            "characterized".to_string(),
            mk(vec![
                "CHARACTERIZED_OBJECT",
                "CHARACTERIZED_REPRESENTATION",
                "DRAUGHTING_MODEL",
                "REPRESENTATION",
            ]),
        );
        cases.insert(
            "characterized_shape_tessellated".to_string(),
            mk(vec![
                "CHARACTERIZED_OBJECT",
                "CHARACTERIZED_REPRESENTATION",
                "DRAUGHTING_MODEL",
                "REPRESENTATION",
                "SHAPE_REPRESENTATION",
                "TESSELLATED_SHAPE_REPRESENTATION",
            ]),
        );
        cases.insert(
            "shape_tessellated".to_string(),
            mk(vec![
                "DRAUGHTING_MODEL",
                "REPRESENTATION",
                "SHAPE_REPRESENTATION",
                "TESSELLATED_SHAPE_REPRESENTATION",
            ]),
        );
        ctx.mapping.complex.insert(
            "characterized_object_complex".to_string(),
            ComplexHint {
                parts: None,
                cases: Some(cases),
            },
        );
        let mut out = GenOut::new("");
        emit_entity(&ctx, "characterized_object_complex", &mut out);
        // exact-set dispatch with distinct length guards (A=4 vs B=6).
        assert!(
            out.bind
                .contains("let part_set: std::collections::BTreeSet")
        );
        assert!(out.bind.contains("part_set.len() == 4 &&"));
        assert!(out.bind.contains("part_set.len() == 6 &&"));
        assert!(
            out.bind
                .contains("part_set.contains(\"TESSELLATED_SHAPE_REPRESENTATION\")")
        );
        // no single-part discriminant form leaked.
        assert!(!out.bind.contains("parts.iter().any(|p| p.name =="));
        assert!(
            out.model
                .contains("pub(crate) enum EarlyCharacterizedObjectComplex {")
        );
    }

    /// Hint-less ENUM auto-synthesis: model enum + strict bind/serialize helpers.
    #[test]
    fn synth_enum_emits_expected() {
        // `actuated_direction` is hint-less (no [enum.*] in mapping.toml).
        let ctx = ctx_from(schema());
        let (mut m, mut b, mut s) = (String::new(), String::new(), String::new());
        emit_synth_enum(
            &ctx,
            "actuated_direction",
            &mut m,
            &mut b,
            &mut s,
            &mut BTreeSet::new(),
        );
        assert!(m.contains("pub(crate) enum EarlyActuatedDirection"));
        assert!(m.contains("Bidirectional"));
        assert!(m.contains("NotActuated"));
        assert!(
            b.contains("\"NOT_ACTUATED\" => Ok(super::model::EarlyActuatedDirection::NotActuated)")
        );
        assert!(
            s.contains("super::model::EarlyActuatedDirection::NotActuated => \"NOT_ACTUATED\"")
        );
    }

    /// Hint-less SELECT with two string members — each disambiguated by its tag.
    #[test]
    fn synth_select_strings() {
        let (m, b, s) = synth_select("source_item");
        assert!(m.contains("pub(crate) enum EarlySourceItem"));
        assert!(m.contains("Identifier(String)"));
        assert!(m.contains("Message(String)"));
        assert!(b.contains(
            "(\"IDENTIFIER\", crate::parser::entity::Attribute::String(s)) => Some(super::model::EarlySourceItem::Identifier(s.clone())),"
        ));
        assert!(s.contains("EarlySourceItem::Message(s) =>"));
    }

    /// Hint-less SELECT with real members (measures) — `Real`/`Integer` accepted.
    #[test]
    fn synth_select_reals() {
        let (m, b, _) = synth_select("tolerance_deviation_select");
        assert!(m.contains("CurveToleranceDeviation(f64)"));
        assert!(b.contains("#[allow(clippy::cast_precision_loss)]"));
        assert!(b.contains("crate::parser::entity::Attribute::Integer(x)) => Some(super::model::EarlyToleranceDeviationSelect::"));
    }

    /// Hint-less SELECT with an ENUM member — synth enum model + inlined token map.
    #[test]
    fn synth_select_enum_member() {
        let (m, b, s) = synth_select("gps_filtration_type");
        // the member enum's model is emitted...
        assert!(m.contains("pub(crate) enum EarlyGeometricToleranceModifier"));
        // ...and the token map is inlined into the select's bind/serialize.
        assert!(b.contains("=> match t.as_str() {"));
        assert!(b.contains("=> Some(super::model::EarlyGpsFiltrationType::"));
        assert!(s.contains("super::model::EarlyGeometricToleranceModifier::"));
    }

    /// ≥2 entity members can't be told apart from a bare `#N`, so they collapse
    /// into one combined `EntityRef(u64)` variant (`lower` resolves the type);
    /// scalar members stay per-variant. `trim_condition_select` =
    /// `SELECT(generalized_surface_select` [all-entity → ref], `length_measure`,
    /// `plane_angle_measure`, `solid_model` [ref]) — two entity members.
    #[test]
    fn synth_select_multi_entity_combined() {
        let (m, b, s) = synth_select("trim_condition_select");
        // the two entity members merge into one combined variant...
        assert!(m.contains("pub(crate) enum EarlyTrimConditionSelect"));
        assert!(m.contains("EntityRef(u64)"));
        // ...and the scalar members keep their own variants.
        assert!(m.contains("LengthMeasure(f64)"));
        assert!(m.contains("PlaneAngleMeasure(f64)"));
        // no per-entity variant survives (collapsed).
        assert!(!m.contains("GeneralizedSurfaceSelect("));
        assert!(!m.contains("SolidModel("));
        // exactly one bind arm consumes the bare `#N`.
        let arm = "crate::parser::entity::Attribute::EntityRef(n) => Some(super::model::EarlyTrimConditionSelect::EntityRef(*n))";
        assert_eq!(b.matches(arm).count(), 1);
        assert!(s.contains(
            "super::model::EarlyTrimConditionSelect::EntityRef(step) => crate::parser::entity::Attribute::EntityRef(*step)"
        ));
    }

    /// Aggregation members arrive as typed parameters `TAG((...))` per Part21,
    /// so each keeps its own variant (no combined `Aggregate`).
    /// `item_identified_representation_usage_select` =
    /// `SELECT(list_representation_item`, `representation_item`, `set_representation_item`)
    /// — one entity ref (collapses to `EntityRef`) + two typed aggregates.
    #[test]
    fn synth_select_typed_aggregate_members() {
        let (m, b, s) = synth_select("item_identified_representation_usage_select");
        // the ref member still collapses; the aggregates stay per-variant.
        assert!(m.contains("EntityRef(u64)"));
        assert!(m.contains("ListRepresentationItem(Vec<u64>)"));
        assert!(m.contains("SetRepresentationItem(Vec<u64>)"));
        assert!(!m.contains("Aggregate("));
        // bind: one tagged List arm per aggregate member, no bare-List arm.
        assert!(b.contains(
            "(\"LIST_REPRESENTATION_ITEM\", crate::parser::entity::Attribute::List(items)) =>"
        ));
        assert!(b.contains(
            "(\"SET_REPRESENTATION_ITEM\", crate::parser::entity::Attribute::List(items)) =>"
        ));
        assert!(!b.contains("        crate::parser::entity::Attribute::List(items) =>"));
        assert!(b.contains("crate::parser::entity::Attribute::EntityRef(n) => out.push(*n),"));
        // serialize: the tag is wrapped back around the list.
        assert!(s.contains(
            "ListRepresentationItem(xs) => crate::parser::entity::Attribute::Typed { type_name: \"LIST_REPRESENTATION_ITEM\".into(), value: Box::new(crate::parser::entity::Attribute::List(xs.iter().map(|&s| crate::parser::entity::Attribute::EntityRef(s)).collect())) }"
        ));
    }

    /// ★Cross-validation against real-file-proven hand-written code:
    /// `datum_or_common_datum` = `SELECT(common_datum_list` [agg], datum [ref]).
    /// The generated bind must match `Typed{"COMMON_DATUM_LIST", List}` — the
    /// exact form the hand-written reader for NIST files matches
    /// (src/entities/pmi.rs, `type_name == "COMMON_DATUM_LIST"`).
    #[test]
    fn synth_select_datum_or_common_datum() {
        let (m, b, s) = synth_select("datum_or_common_datum");
        assert!(m.contains("EntityRef(u64)"));
        assert!(m.contains("CommonDatumList(Vec<u64>)"));
        assert!(
            b.contains("(\"COMMON_DATUM_LIST\", crate::parser::entity::Attribute::List(items)) =>")
        );
        assert!(s.contains("type_name: \"COMMON_DATUM_LIST\".into()"));
    }

    /// Typed-aggregate edge cases: an agg-only select gets one Typed arm per
    /// member (no empty match); a real-inner agg keeps the integer promotion
    /// (and its cast allow); `maths_value` stays deferred (Vec(Select) member).
    #[test]
    fn synth_select_typed_aggregate_edges() {
        // compound_item_definition = SELECT(list_repr_item, set_repr_item) — agg only.
        let (_, b, _) = synth_select("compound_item_definition");
        assert!(b.contains(
            "(\"LIST_REPRESENTATION_ITEM\", crate::parser::entity::Attribute::List(items)) =>"
        ));
        assert!(b.contains(
            "(\"SET_REPRESENTATION_ITEM\", crate::parser::entity::Attribute::List(items)) =>"
        ));
        // spatial_rotation = SELECT(rotation_about_direction [ref], ypr_rotation [LIST OF real]).
        let (m2, b2, _) = synth_select("spatial_rotation");
        assert!(m2.contains("YprRotation(Vec<f64>)"));
        assert!(b2.contains("#[allow(clippy::cast_precision_loss)]"));
        assert!(
            b2.contains("crate::parser::entity::Attribute::Integer(x) => out.push(*x as f64),")
        );
        // maths_value is supported as of v4.21 (recursive Vec(Select) member).
        assert!(ctx_from(schema()).select_supported("maths_value"));
    }

    /// A scalar-only nested SELECT member (`measure_value` = 42 scalar measures)
    /// is decoded by delegating to its own `bind_measure_value` from the outer
    /// Typed `_ =>` arm; the nested select is emitted recursively.
    /// `measured_value_select` = `SELECT(boolean_value` [Bool], `measure_value`
    /// [nested SELECT], `plane_angle_and_length_pair` [ref], `plane_angle_and_ratio_pair`
    /// [ref]) — two refs collapse to `EntityRef`, the nested becomes `MeasureValue`.
    #[test]
    fn synth_select_nested_typed_only_delegates() {
        let (m, b, s) = synth_select("measured_value_select");
        // outer variants: combined ref + bool + nested-select payload.
        assert!(m.contains("pub(crate) enum EarlyMeasuredValueSelect"));
        assert!(m.contains("EntityRef(u64)"));
        assert!(m.contains("BooleanValue(bool)"));
        assert!(m.contains("MeasureValue(super::model::EarlyMeasureValue)"));
        // the nested select is emitted recursively (its own model + bind).
        assert!(m.contains("pub(crate) enum EarlyMeasureValue"));
        assert!(b.contains("fn bind_measure_value("));
        // outer bind delegates the whole attr to the nested decoder.
        assert!(b.contains(
            "if let Some(x) = bind_measure_value(attr) { return Some(super::model::EarlyMeasuredValueSelect::MeasureValue(x)); }"
        ));
        // serialize delegates to the nested emitter.
        assert!(s.contains(
            "super::model::EarlyMeasuredValueSelect::MeasureValue(x) => measure_value_emit(x),"
        ));
    }

    /// A nested mixed SELECT member with a *ref* member is still deferred — its
    /// bare `#N` values would be ambiguous with the outer's. The real schema has
    /// no such case left (coverage 100%), so this uses a synthetic schema:
    /// outer = SELECT(real, `bad_nested`), `bad_nested` = SELECT(thing [entity], real).
    #[test]
    #[should_panic(expected = "nested mixed select")]
    fn synth_select_nested_mixed_panics() {
        let mut entity = BTreeMap::new();
        entity.insert(
            "thing".to_string(),
            Entity {
                parents: vec![],
                own_attrs: vec![],
                redeclared_attrs: vec![],
            },
        );
        let mut types = BTreeMap::new();
        types.insert(
            "bad_nested".to_string(),
            TypeDef {
                aliased: "SELECT(thing, real)".to_string(),
            },
        );
        types.insert(
            "outer_sel".to_string(),
            TypeDef {
                aliased: "SELECT(real, bad_nested)".to_string(),
            },
        );
        let ctx = ctx_from(EarlyToml { entity, types });
        let (mut m, mut b, mut s) = (String::new(), String::new(), String::new());
        emit_select_synth(
            &ctx,
            "outer_sel",
            &mut m,
            &mut b,
            &mut s,
            &mut BTreeSet::new(),
            &mut BTreeSet::new(),
        );
    }

    /// ★maths completion (v4.21): self-recursive `maths_value` via `Vec` (no Box)
    /// + recursive nested emission + tagged-list element decode.
    #[test]
    fn synth_select_maths_value_recursive() {
        let ctx = ctx_from(schema());
        assert!(ctx.select_supported("maths_value"));
        assert!(ctx.select_supported("maths_expression"));
        assert!(ctx.select_supported("atom_based_value"));
        let (m, b, s) = synth_select("maths_value");
        assert!(m.contains("pub(crate) enum EarlyMathsValue"));
        assert!(m.contains("EntityRef(u64)")); // generic_expression
        assert!(m.contains("MathsTuple(Vec<EarlyMathsValue>)")); // self-recursive via Vec
        assert!(m.contains("AtomBasedValue(super::model::EarlyAtomBasedValue)"));
        // the nested select is emitted recursively, incl. its own self-recursion.
        assert!(m.contains("pub(crate) enum EarlyAtomBasedValue"));
        assert!(m.contains("AtomBasedTuple(Vec<EarlyAtomBasedValue>)"));
        // bind: tagged list arm decodes elements via the (self-recursive) bind.
        assert!(b.contains("(\"MATHS_TUPLE\", crate::parser::entity::Attribute::List(items)) =>"));
        assert!(b.contains("it => match bind_maths_value(it) {"));
        // the Typed `_ =>` arm delegates to the nested decoder.
        assert!(b.contains("if let Some(x) = bind_atom_based_value(attr)"));
        // serialize wraps the tag back around the recursive list.
        assert!(s.contains(
            "MathsTuple(xs) => crate::parser::entity::Attribute::Typed { type_name: \"MATHS_TUPLE\".into()"
        ));
        assert!(s.contains("map(maths_value_emit)"));
    }

    /// Standalone 2-level aggregation of a mixed select (`finite_function.pairs`
    /// = `SET OF LIST OF maths_value`): `<alias>_grid` helper + nested `List`.
    #[test]
    fn grid_of_select_codegen() {
        let ctx = ctx_from(schema());
        let g = Kind::Vec(Box::new(Kind::Vec(Box::new(Kind::Select(
            "maths_value".into(),
        )))));
        assert!(ctx.emittable(&g, false));
        assert!(!ctx.emittable(&g, true)); // optional grid stays deferred
        assert!(bind_expr(&g, 1, "x").contains("maths_value_grid(attrs, 1"));
        let s = serialize_expr(&g, "pairs");
        assert_eq!(
            s.matches("crate::parser::entity::Attribute::List(").count(),
            2
        );
        assert!(s.contains("map(maths_value_emit)"));
        // the generated helper decodes each grid element via bind_<select>.
        let mut helper = String::new();
        emit_select_grid(&ctx, "maths_value", &mut helper);
        assert!(helper.contains("fn maths_value_grid("));
        assert!(helper.contains("Result<Vec<Vec<super::model::EarlyMathsValue>>"));
        assert!(helper.contains("bind_maths_value(item)"));
    }

    /// `binary` / `logical` as SELECT members (v4.19): `maths_simple_atom` =
    /// `SELECT(maths_binary`, `maths_boolean`, `maths_integer`, `maths_logical`,
    /// `maths_number`, `maths_real`, `maths_string`). Each is a `Typed{tag, ..}`.
    #[test]
    fn synth_select_binary_logical_members() {
        assert!(ctx_from(schema()).select_supported("maths_simple_atom"));
        let (m, b, s) = synth_select("maths_simple_atom");
        // payloads: binary -> String, logical -> the IR Logical type.
        assert!(m.contains("MathsBinary(String)"));
        assert!(m.contains("MathsLogical(crate::ir::geometry::Logical)"));
        assert!(m.contains("MathsReal(f64)"));
        // bind decodes by tag: Binary attr / logical token.
        assert!(b.contains(
            "(\"MATHS_BINARY\", crate::parser::entity::Attribute::Binary(s)) => Some(super::model::EarlyMathsSimpleAtom::MathsBinary(s.clone())),"
        ));
        assert!(b.contains("\"T\" => crate::ir::geometry::Logical::True"));
        // serialize round-trips them.
        assert!(s.contains(
            "super::model::EarlyMathsSimpleAtom::MathsBinary(s) => crate::parser::entity::Attribute::Typed"
        ));
        assert!(s.contains("crate::parser::entity::Attribute::Binary(s.clone())"));
        assert!(s.contains("crate::ir::attr::logical_to_step(*l)"));
    }

    /// `maths_atom` = `SELECT(maths_enum_atom`, `maths_simple_atom`) — both Typed-only
    /// nested selects → outer bind delegates to each `bind_<nested>` (2 nested),
    /// and both nested selects are emitted recursively.
    #[test]
    fn synth_select_maths_atom_two_nested() {
        assert!(ctx_from(schema()).select_supported("maths_atom"));
        let (m, b, _) = synth_select("maths_atom");
        assert!(m.contains("MathsEnumAtom(super::model::EarlyMathsEnumAtom)"));
        assert!(m.contains("MathsSimpleAtom(super::model::EarlyMathsSimpleAtom)"));
        // both nested decoders are delegated to and emitted.
        assert!(b.contains("if let Some(x) = bind_maths_enum_atom(attr)"));
        assert!(b.contains("if let Some(x) = bind_maths_simple_atom(attr)"));
        assert!(b.contains("fn bind_maths_simple_atom("));
    }

    /// `Vec<EarlyEnum>` (aggregation of enum): list-decode helper + per-element
    /// `<alias>_attr` serialize.
    #[test]
    fn vec_enum_codegen() {
        let ctx = empty_ctx();
        let venum = Kind::Vec(Box::new(Kind::Enum("foo".into())));
        assert!(ctx.emittable(&venum, false));
        assert!(bind_expr(&venum, 1, "x").contains("foo_list(attrs, 1, entity_id"));
        assert!(serialize_expr(&venum, "y").contains("|e| foo_attr(e.clone())"));
        // the generated list helper decodes each Enum element to a variant.
        let mut b = String::new();
        emit_enum_list(&ctx_from(schema()), "summary_report_style_type", &mut b);
        assert!(b.contains(
            "fn summary_report_style_type_list(attrs: &[crate::parser::entity::Attribute]"
        ));
        assert!(b.contains("Vec<super::model::EarlySummaryReportStyleType>"));
        assert!(
            b.contains("\"CONCLUSION\" => super::model::EarlySummaryReportStyleType::Conclusion,")
        );
    }

    /// `Vec<EarlySelect>` (aggregation of select): list-decode helper reusing
    /// `bind_<select>` + `<alias>_emit` per element.
    #[test]
    fn vec_select_codegen() {
        let ctx = ctx_from(schema());
        // a supported (scalar-member) mixed select is emittable inside a Vec.
        let vsel = Kind::Vec(Box::new(Kind::Select("tolerance_deviation_select".into())));
        assert!(ctx.emittable(&vsel, false));
        assert!(bind_expr(&vsel, 2, "x").contains("tolerance_deviation_select_list(attrs, 2"));
        assert!(serialize_expr(&vsel, "y").contains(".map(tolerance_deviation_select_emit)"));
        // the generated list helper decodes each element via bind_<select>.
        let mut b = String::new();
        emit_select_list(&ctx, "tolerance_deviation_select", &mut b);
        assert!(b.contains("fn tolerance_deviation_select_list("));
        assert!(b.contains("Vec<super::model::EarlyToleranceDeviationSelect>"));
        assert!(b.contains("bind_tolerance_deviation_select(item)"));
    }

    /// `Vec<Logical>` (v4.12): single `logical_list` decode helper + per-element
    /// `logical_to_step` serialize.
    #[test]
    fn vec_logical_codegen() {
        let ctx = empty_ctx();
        let vlog = Kind::Vec(Box::new(Kind::Logical));
        assert!(ctx.emittable(&vlog, false));
        assert!(bind_expr(&vlog, 1, "x").contains("logical_list(attrs, 1"));
        let s = serialize_expr(&vlog, "y");
        assert!(s.contains(
            "|&l| crate::parser::entity::Attribute::Enum(crate::ir::attr::logical_to_step(l)"
        ));
        let mut b = String::new();
        emit_logical_list(&mut b);
        assert!(b.contains("fn logical_list("));
        assert!(b.contains("Vec<crate::ir::geometry::Logical>"));
        assert!(b.contains("\"T\" => crate::ir::geometry::Logical::True"));
    }
}
