//! Bakes the per-target output `SchemaProfile` data into
//! `src/early/generated/profile.rs`.
//!
//! Source = the curated output profiles `schema/<target>.toml` (produced by
//! step-io-blueprint's `profile_export`). Each profile lists the entities
//! legal in one target IS edition plus its FILE_SCHEMA / APD header values.
//!
//! The write-side projection (`early/profile.rs`, consumed in a later batch)
//! compares each emitted `WriteBuffer` entity name against the per-target legal
//! set. Those names are UPPER-case wire form (`CARTESIAN_POINT`), while profile
//! toml keys are lower-case EXPRESS names — so the baked set is upper-cased here
//! to match what the projection actually sees.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use serde::Deserialize;

use crate::schema::Entity;

/// Curated output targets: `(profile toml stem, generated const prefix)`.
const TARGETS: &[(&str, &str)] = &[
    ("ap214e3", "AP214E3"),
    ("ap242e2", "AP242E2"),
    ("ap203e2", "AP203E2"),
];

#[derive(Deserialize)]
struct ProfileToml {
    meta: ProfileMeta,
    /// Entity blocks — only the keys (legal entity names) are needed here.
    #[serde(default)]
    entity: BTreeMap<String, Entity>,
}

#[derive(Deserialize)]
struct ProfileMeta {
    file_schema: Vec<String>,
    apd: ProfileApd,
}

#[derive(Deserialize)]
struct ProfileApd {
    status: String,
    name: String,
    year: i64,
}

/// Read the target profile tomls and return the full `profile.rs` content
/// (own header included — these tomls, not early.toml, are the source).
pub(crate) fn emit_profiles(root: &str) -> String {
    let mut out = String::from(
        "// DO NOT EDIT — generated by `cargo run -p gen-early` from schema/<target>.toml\n\
         // (output SchemaProfiles produced by step-io-blueprint). Consumed by the\n\
         // write-side projection. Entity names are UPPER wire form (match the writer).\n\
         #![allow(dead_code)] // data tables; some targets may be unwired in early batches\n\
         #![allow(clippy::doc_markdown)] // STEP entity names in doc comments are bare tokens\n\n",
    );
    for (stem, prefix) in TARGETS {
        let path = format!("{root}/schema/{stem}.toml");
        let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
        let prof: ProfileToml =
            toml::from_str(&text).unwrap_or_else(|e| panic!("parse {path}: {e}"));

        writeln!(
            out,
            "/// Entities legal in {stem} output (UPPER wire form, sorted). Absence = illegal.",
        )
        .unwrap();
        writeln!(out, "pub(crate) const {prefix}_LEGAL: &[&str] = &[").unwrap();
        // Sort in UPPER-case order (not the lower-case BTreeMap order): the
        // consumer binary_searches the upper-case names, and `_` orders
        // differently vs letters between the two cases.
        let mut upper: Vec<String> = prof.entity.keys().map(|n| n.to_uppercase()).collect();
        upper.sort();
        upper.dedup();
        for name in &upper {
            writeln!(out, "    \"{name}\",").unwrap();
        }
        writeln!(out, "];\n").unwrap();

        writeln!(
            out,
            "/// FILE_SCHEMA descriptor string(s) for {stem} output."
        )
        .unwrap();
        writeln!(out, "pub(crate) const {prefix}_FILE_SCHEMA: &[&str] = &[").unwrap();
        for s in &prof.meta.file_schema {
            writeln!(out, "    {s:?},").unwrap();
        }
        writeln!(out, "];\n").unwrap();

        writeln!(
            out,
            "/// APPLICATION_PROTOCOL_DEFINITION (status, application, year) for {stem}.",
        )
        .unwrap();
        writeln!(
            out,
            "pub(crate) const {prefix}_APD: (&str, &str, i64) = ({:?}, {:?}, {});\n",
            prof.meta.apd.status, prof.meta.apd.name, prof.meta.apd.year,
        )
        .unwrap();
    }
    out
}
