//! STEP (ISO 10303) file I/O.
//!
//! [`read`] parses STEP source into the schema-faithful [`StepModel`] together
//! with a provenance [`Report`] (what was kept, normalized, or dropped and why);
//! [`write`] emits a model back to STEP text. The model, read, and write code is
//! generated by the `codegen` crate from the schema (`schema/universal.toml`).

#[cfg(feature = "gen")]
pub mod generated;
#[cfg(feature = "gen")]
pub mod normalize;
pub mod parser;

#[cfg(feature = "gen")]
pub use generated::model::Model as StepModel;
#[cfg(feature = "gen")]
pub use normalize::{DropKind, DropReason, ReadError, Report, read, write};
pub use parser::{
    Attribute, EntityGraph, LexError, LexErrorKind, Lexer, NonEmptyStringList, ParseError,
    ParseWarning, Parser, RawEntity, RawEntityPart, SchemaClass, Span, StepSchema, Token,
    TokenKind, parse, parse_bytes, tokenize,
};
