//! STEP (ISO 10303) file I/O.
//!
//! [`read`] parses STEP source into the schema-faithful [`StepModel`] together
//! with a provenance [`Report`] (what was kept, normalized, or dropped and why);
//! [`write`] emits a model back to STEP text. The model, read, and write code is
//! generated by the `codegen` crate from the schema (`schema/universal.toml`).

pub mod generated;
pub mod normalize;
pub mod parser;

pub use generated::model::StepModel;
pub use normalize::{DropKind, DropReason, Report, read, write};
pub use parser::{
    Attribute, Error, Graph, LexError, LexErrorKind, Lexer, NonEmptyStringList, ParseWarning,
    Parser, RawEntity, RawEntityPart, SchemaClass, Span, StepSchema, Token, TokenKind, parse,
    parse_bytes, tokenize,
};

/// Crate-wide result alias: the only fallible public entry point ([`read`])
/// fails with [`Error`].
pub type Result<T> = std::result::Result<T, Error>;
